### ISSUE TITLE
neocomplete preview window alternative

### ISSUE THREAD

**Issue by Netherdrake** [Shougo/neocomplete.vim#120]
Hi,

My issue is as follows:
http://stackoverflow.com/questions/20164541/golang-vim-autocomplete-hints

I am wondering if you know how could I achieve this.

Thanks, your plugin is awesome!

**Comment by sirfz** [comment]
Is there a specific configuration for echodoc with jedi? Doesn't seem to work for me. (tried with increased cmdheight and also noshowmode). Ctrl+y doesn't display anything.

**Comment by Shougo** [comment]
jedi does not support echodoc.
To support it, you must write Vim script code like neocomplete.
