### ISSUE TITLE
Dictionary completion not working

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#138]
Thanks to your help and patience regarding this [issue](https://github.com/Shougo/neocomplete.vim/issues/81) I managed to get tex command completion using a dict file. So if, for instance, I type

```
 \var
```

and have `\varepsilon` in my `tex.dict` file then it completes to

```
  \varepsilon
```

However I think that yesterday (or at least within this week) this completion stopped working. Here are my relevant neocomplete settings

```
let g:neocomplete#sources#dictionary#dictionaries = {
        \ 'default' : '',
        \ 'tex' : $DOTVIM.'/ftplugin/tex/tex_dictionary.dict'
        \ }

if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer', 'dictionary', 'ultisnips', 'file',
            \ 'omni']

if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns._ = '^\\\?\h\w*$'
let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w*:\%(\w*_\w*\)\?'}
let keyword_patterns2 = {'tex' : '\h\w*'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)
call neocomplete#custom#source('ultisnips', 'keyword_patterns',
        \ keyword_patterns2)
```

The strange thing is that the dictionary cache file is properly created and the entries (such as `\varepsilon`) are all there. I noticed that they are saved with a double backslash though (maybe this was always the case):

```
 {'\\varepsilon'} 
```

Maybe this [commit](https://github.com/Shougo/neocomplete.vim/commit/bfc528d72fa836c11aa97e1aee8f3eb4c0f8202d) changed something?

**Comment by godhelpjun** [comment]
yeah,I agree with @yeah-shy,It's  the dll version of  lua problem.  if things not work properly,you should try another version of lua.dll .you can get it for the upstream,i.e,sourceforge.net
