### ISSUE TITLE
Switch between results with <tab> (and <s-tab>), validate with <enter>

### ISSUE THREAD

**Issue by choucavalier** [Shougo/neocomplete.vim#197]
I don't know if it's me or the documentation but I can't get what I want.

I'd like to be able to switch between propositions using <tab>. But when I press that, it's just inserting some spaces (and not completing).
`inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"`

Plus, I'd like to be able to validate using <enter> without creating a new line... (this is happening, when I try to validate a proposition using <enter> it completes but then creates a new line (carriage return).

**Comment by miguelmota** [comment]
@toogy did you ever find a solution for tab completion? I can't get it to work.

**Comment by toogy** [comment]
@miguelmota: I'm using YouCompleteMe now. You should try it sometime ^.^
