### ISSUE TITLE
manual complete auto select

### ISSUE THREAD

**Issue by Konfekt** [Shougo/neocomplete.vim#212]
How can one force `neocomplete#start_manual_complete()` to complete by the first popup menu entry?
If we put

```
let g:neocomplete#disable_auto_complete = 1
let g:neocomplete#enable_auto_select = 0
```

then `neocomplete#start_manual_complete()` will only select it, but not complete the typed word.

**Comment by kristijanhusak** [comment]
@Shougo 
This works for me as Konfekt requested, but i would like to avoid that type of functionality.

I need to show the popup, but not select the first entry, so i can continue to type and see other entries in the complete list.

Setting  `let g:neocomplete#enable_auto_select` to both 1 or 0 is not working.

**Comment by Shougo** [comment]
OK.

**Comment by kristijanhusak** [comment]
Thanks, it works!
