### ISSUE TITLE
Allow set paste

### ISSUE THREAD

**Issue by schickling** [Shougo/neocomplete.vim#263]
It would be convenient if the option `set paste` would be allowed. I'm using vim inside a terminal on mac and often find myself inserting a snippet from my clipboard while I'm in insert mode. The indentation of the inserted code get's completely messed up.

I know I could use `ctrl + o` and `p` but inserting via `cmd + v` feels much more natural.

**Comment by steadystatic** [comment]
I don't use `:set paste` in .vimrc just toggle it temporarily when I want to paste from CodePen etc into Vim...I like the workaround and have been using that method but I still forget and then my undo tree takes FOREVER to undo and re-paste properly. Any other way to make this less painful?

**Comment by Shougo** [comment]
My config for paste option:

```vim
autocmd InsertLeave *
      \ if &paste | set nopaste mouse=a | echo 'nopaste' | endif |
      \ if &l:diff | diffupdate | endif
```

**Comment by petervaro** [comment]
> No. some Vimmers use `:set paste` in wrong settings.

Can you explain what was in your mind? I don't really understand your problem here, not to mention the fact, that if `set paste` is not conflicting with `neocomplete` why are you forcing your views on the users?

**Comment by petervaro** [comment]
> You should not use `set paste` in normal state.

Don't get me wrong, I agree with you on this one, however I still think trusting the user and letting him/her do mistakes (aka giving the freedom of choice to the user) is more important in this case than forcing him/her to do the right thing -- which otherwise is only our opinion and not the absolute truth.

> It ignores the mappings and auto completion plugin like neocomplete.

Now this is where things are getting more interesting. How does `set paste` ignore mappings? And how does it interfere with `neocomplete`?

**Comment by Shougo** [comment]
Paste mode behaves "the inputted text is inserted as is".
So, the mappings are disabled.
Because, if the mappings works in insert mode, your pasted text will be broken.
So the auto completion plugin is disabled in insert mode.
If the plugin works in insert mode, your pasted text will be broken.

**Comment by petervaro** [comment]
👍 Perfectly makes sense, thanks for the headsup!

**Comment by msghovm** [comment]
Hi,
I'm agree with the plugin disabled in paste mode to avoid weird effects.
But your check is wrong to see if we're in paste mode or not.
I haven't "set paste" in my vimrc, but "setlocal paste!" mapper on ladder'pp'. (and a map to NeoCompleteToggle)
I wasn't hopping to have the plugin working in paste mode, but this check disable the plugin even if i'm not in paste mode when i try to toggle it in enabled state.
Is it possible to check if there is the '!' char after 'paste', and stop disabling the plugin in this case?
