### ISSUE TITLE
g:neocomplete#sources#dictionary#dictionaries not reading comma separated values

### ISSUE THREAD

**Issue by psaia** [Shougo/neocomplete.vim#269]
##### Issue 1:

Unless I'm misunderstanding the docs, the following should be valid:

``` vimscript
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'javascript' : $HOME.'/.vim/dict/vim-node-dict/dict/node.dict,'.$HOME.'/.vim/dict/vim-dict/dict/javascript.dic'
\ }

```

However, only the first path is read (node.dict) and the latter (javascript.dic) is ignored.
##### Issue 2:

Also, perhaps unrelated, the description states "If this variable is empty, neocomplete uses 'dictionary' option.". Does this mean if the following is set:

```
au FileType javascript set dictionary+=$HOME.'/.vim/dict/vim-node-dict/dict/node.dict'
au FileType javascript set dictionary+=$HOME.'/.vim/dict/vim-dict/dict/javascript.dic'
```

 Then this will inherit from `dictionary`? If so this also seems to be untrue.

```
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'javascript' : ''
\ }
```

**Comment by wewea** [comment]
if only load the first dict, because there a extra space between two dict path. try to delete it.
