### ISSUE TITLE
neovim "It requires "if_lua" enabled Vim"

### ISSUE THREAD

**Issue by JBKahn** [Shougo/neocomplete.vim#276]
I'm not sure if this is an issue with the way I installed neovim but I have 'vim-nox' on my computer (ubuntu 14.04). I can start vim without hitting the `It requires "if_lua" enabled Vim(7.3.885 or above).`. I thought that neovim already supported this. Is there something I'm supposed to do to make this work with neovim? is it neovim compatible?

**Comment by yoshuawuyts** [comment]
Actually it appears to support `if_lua` now. -- [neovim wiki](https://github.com/neovim/neovim/wiki/Differences-from-vim#plugin-compatibility-layer-872-895-1130)

**Comment by Shougo** [comment]
Oh, really?  Thanks.  I wil check it.

**Comment by Shougo** [comment]
Unfortunatelly, neovim does not support if_lua/if_ruby now.

**Comment by chixq** [comment]
So we can't use neovim with neocomplete right?
Is if_lua support on the roadmap ?

**Comment by Shougo** [comment]
Yes.

> Is if_lua support on the roadmap ?

It is on the road map.  But it is low priority...
I may create new completion plugin for neovim.

**Comment by lazywei** [comment]
Hi @Shougo , So before the `deoplete` releasing, NeoVim user can only use neocomplcache? Is there any significant drawback / pitfalls for using neocomplcache? I saw its README says it is not maintained well?

**Comment by Shougo** [comment]
Yes, neocomplcache is not maintained well.
I don't want to extend it.
