### ISSUE TITLE
Neoinclude plugin?

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#285]
These [lines](https://github.com/Shougo/neocomplete.vim/blob/master/doc/neocomplete.txt#L176-L177) in the docs say:

> If you want to complete from include files or include files, you need to
>     install the neoinclude plugin (https://github.com/Shougo/neoinclude.vim).

Is there a neoinclude plugin? I cannot find it.

**Comment by Shougo** [comment]
neoinclude is available.

https://github.com/Shougo/neoinclude.vim

**Comment by petobens** [comment]
Great! Thank you!!!

**Comment by petobens** [comment]
Hi @Shougo  I think the heading of the repository need a minor change from:

>Include completion framework for neoinclude/deoplete 

to 
>Include completion framework for neocomplete/deoplete

**Comment by Shougo** [comment]
Thanks.  Fixed.
