### ISSUE TITLE
Conflict with latex-suite

### ISSUE THREAD

**Issue by mynoduesp** [Shougo/neocomplete.vim#289]
Latex-suite provides autocompletion for citation commands with the option to navigate references.  As an example, in order to insert `\cite{Smith14}`, one can type `\citet{S<F9>`

With neocomplete, this instead produces `\cite{Smith1(neocomplete_start_auto_complete)}4`.

I have tried mapping <F10> to <F9> with added NeoCompleteLock/NeoCompleteUnlock without sucess.

**Comment by joelfrederico** [comment]
Sorry for the newbie question, but how can I conditionally disable neocomplete so that it is enabled on everything except *.tex files?

**Comment by Shougo** [comment]
You can use `:NeoCompleteLock` command in tex filetype buffers.

**Comment by joelfrederico** [comment]
Interestingly- I think this was vim-latex's fault. I've got mine working, now that I ported vim-latex to work with vim +python3.
