### ISSUE TITLE
b:neocomplete#fallback_mappings

### ISSUE THREAD

**Issue by Konfekt** [Shougo/neocomplete.vim#306]
How about making `g:neocomplete#fallback_mappings` a buffer variable? Then for example, depending if spell check is active, such as in a Text type document, this could be set to `<c-x><c-k>`.

By the way, before opening another issue, is the dictionary fallback `<c-x><c-k>` supposed to work? Over here `let g:neocomplete#fallback_mappings = ["\<C-x>\<C-k>"]` has no effect.

**Comment by Shougo** [comment]
I don't want to add the feature.

**Comment by Konfekt** [comment]
Ok!

**Comment by Grueslayer** [comment]
I started to use neocomplete and love the display from different sources (Buffer / UltiSnips / etc.). But using omnicompletion stops that feature until you created the fallback feature in 2014. But this is still a slimmed solution, my snippets are still missing. 

I still have to decide what expansion I want to use. So there is no benefit from neocomplete anymore (can use vanilla VIM for this).

The only thing then is fuzzy search but that still requires a match on the first char, YCM does a better job.

I really think with omnicompletion enabled, it should be possible to get the keywords from the same sources as without.

**Comment by Shougo** [comment]
@Grueslayer You seems use `g:neocomplete#force_omni_patterns`.  You should use `g:neocomplete#sources#omni#input_patterns` instead.
But some omnifunc does not support the feature.

> The only thing left is fuzzy search but that requires a match on the first char, YCM does a better job.

deoplete implements "matcher_full_fuzzy" feature.
