### ISSUE TITLE
Having trouble compiling vim with lua in Linux

### ISSUE THREAD

**Issue by JohanTan** [Shougo/neocomplete.vim#31]
Cannot use homebrew option in linux. Tried recompiling vim with Lua and got no luck. Google didn't help either because seemed nobody is using this compilation option. Is there any tutorial that would help this process?

**Comment by richvincent** [comment]
@JohanTan Is a genius!!! Your advice worked like a charm!

Here is a repost:

From my experience, this is how it will work (only tested on Ubuntu):

sudo apt-get install liblua5.1-dev
copy all files from /usr/include/lua5.1/ to /usr/include/lua5.1/include/
sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so /usr/local/lib/liblua.so

Go to vim source folder:
./configure --with-features=huge --enable-cscope --enable-pythoninterp=yes --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-multibyte --enable-fontset --disable-gui --disable-netbeans --enable-luainterp=yes --with-lua-prefix=/usr/include/lua5.1 --enable-largefile
make
sudo make install
