### ISSUE TITLE
Vim crashes when Neocomplete autocompletion active

### ISSUE THREAD

**Issue by Konfekt** [Shougo/neocomplete.vim#313]
Dear Shougo,

Please open in Vim

https://github.com/Konfekt/FastFold/blob/223feb6c03abe8a4723d60137e417b9bb41cc1ed/plugin/fastfold.vim

and goto line 165, column 43. Enter `ce` and then `E`.

GVim 7.4.505 under Windows 7 64bit crashes immediately.

**Comment by Shougo** [comment]
OK.
