### ISSUE TITLE
Neocomplete Freeze in Scanning files

### ISSUE THREAD

**Issue by j5shi** [Shougo/neocomplete.vim#331]
I've encountered several times that when I was deleting a word using `<Backspace>` key, and neocomplete will keep poping up the autocomplete option everytime I delete a character, and all of a sudden VIM stopped responding, with a message in the bottom saying "Scanning: \user...", and by then VIM could contributes >25% CPU load, VIM will never come back to response and I have to kill the VIM process.

Is there any way to debug?

**Comment by Shougo** [comment]
No response and it is not neocomplete issue.

**Comment by Shougo** [comment]
It is same problem.  You must map `<BS>` key.

https://github.com/Shougo/neocomplete.vim/issues/339

**Comment by j5shi** [comment]
It's not "No response", I didn't reply because I was trying to find the situation to reproduce this issue, but not found yet, it's random. 

I searched the string `Scanning:` and found that it only appears in `vim.exe` and `gvim.exe`, even though it's a bug of vim (you've mentioned in issue 342), I believe it has something to do with neocomplete, since it's triggered only when I have neocomplete installed.

Anyway you've provided a workaround to avoid triggering this vim's bug, could you please explain more about what kind of bug it is and why it may be triggered when `<bs>` is not mapped? Thanks.

**Comment by Shougo** [comment]
> It's not "No response", I didn't reply because I was trying to find the situation to reproduce this issue, but not found yet, it's random. 

Sorry.

> Anyway you've provided a workaround to avoid triggering this vim's bug, could you please explain more about what kind of bug it is and why it may be triggered when <bs> is not mapped? Thanks.

OK.  I will follow up.

* If you press `<BS>` or `<C-h>`, Vim narrow the candidates automatically.
* To implement `complete()` feature, whole line completion is used.
* If you press `<C-h>`, Vim use whole line completion(It is `complete()` bug).
* Whole line completion searches the candidates from 'complete' option.
* Your 'complete' option contains "i" character.  Vim searches the candidates from the include files.
* Wow, "Scanning:" is echoed!
* `complete()` is not well tested feature.  It is buggy.

So, you must map `<BS>` and `<C-h>` keys.

**Comment by j5shi** [comment]
Very good explanation, thank you @Shougo!
