### ISSUE TITLE
Keyboard Mapping Issue

### ISSUE THREAD

**Issue by amadeus** [Shougo/neocomplete.vim#334]
If it's helpful, I can run a git bisect to find out exactly when this issue started occurring, however you might already know exactly what the cause is.

I have had these mappings in my vimrc for a while and they've been working beautifully:

```
inoremap <c-k> <esc>O
inoremap <c-l> <esc>A
inoremap <c-h> <esc>I
inoremap <c-j> <esc>o
```

Basically very handy little shortcuts that enable me to move the cursor, for example, to the end of the line while in insert mode.

Somewhat recently however, it seems that NeoComplete has hijacked the `inoremap <c-l> <esc>A` command and it no longer works after a popup has appeared.

**Edit:** I mistakenly referred to the wrong remap command in the final sentence, I have now fixed it, in case you see conflicting information in an email notification.

**Comment by Shougo** [comment]
Yes. I confirmed the problem.  But it seems Vim's problem.
I will check it.

**Comment by Shougo** [comment]
You can confirm it by below .vimrc.

```
set nocompatible

inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(col('.'), ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```

You can complete candidates by `<F5>` key.  And please press `<C-l>` in several times...

**Comment by Shougo** [comment]
https://groups.google.com/forum/#!topic/vim_dev/R7i2fb_yynY

mattn fixes it.

**Comment by amadeus** [comment]
I manually applied to the patch in that thread, and while it stops <c-l> being used to cycle the options, it changes to nothing happening at all, like a nop.

As per Christian's email here:

https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/ZIgRHDjJ8uEJ

I think something changed in this commit 1f7da02 that somehow prevent's `<c-l>` from being used. Is there any way I can provide a custom mapping or something to re-enable this functionality?

**Comment by Shougo** [comment]
> I think something changed in this commit 1f7da02 that somehow prevent's <c-l> from being used.

It is `complete()` problem.  It seems not tested feature well.

> Is there any way I can provide a custom mapping or something to re-enable this functionality?

Nothing.

**Comment by amadeus** [comment]
No worries, Christian just posted a patch in that thread that fixes the problem perfectly!
