### ISSUE TITLE
Lines don't break until after insert mode is exited

### ISSUE THREAD

**Issue by lervag** [Shougo/neocomplete.vim#336]
Hi. I've just noticed that with neocomplete (autocomplete) enabled, lines will not be broken when they pass `textwidth` length until after insert mode is exit.

I use the following minivimrc file:
```vimL
set nocompatible

let &rtp = '~/.vim/bundle/neocomplete,' . &rtp
let g:neocomplete#enable_at_startup = 1

filetype plugin indent on
syntax enable

set textwidth=79
set cursorline
```

Now I open any file and write a long line (more than 79 characters). I expect lines to break after 79 characters, but they don't break until after I leave insert mode. If I do not enable neocomplete, than I observe expected behaviour.

**Comment by Shougo** [comment]
It is not neocomplete bug.
It is Vim's feature.
If neocomplete opens completion window, Vim cannot break lines.

**Comment by lervag** [comment]
I see. Thanks for the clarification!
