### ISSUE TITLE
indentkeys broken after switching from completefunc to complete()

### ISSUE THREAD

**Issue by wilywampa** [Shougo/neocomplete.vim#337]
# Problems summary
Vim's `indentkeys` functionality no longer works in many cases when using NeoComplete. `indentkeys` works fine before 1f7da025efe2141a8a771289b82b71b949066dea but not after.

It appears that the `CompleteDone` event isn't getting through to the bottom of `neocomplete#handler#_on_complete_done()` where `indentkeys` is handled anymore.
## Expected
I should be able to type:
```vim
function! Foo() " {{{
    return 1
endfunction " }}}
```
but instead I get:
```vim
function! Foo() " {{{
    return 1
    endfunction " }}}
```
(last line not indented correctly). It does work if I select `endfunction` from the completion menu or hit `<CR>` after typing `endfunc` but it used to work in any case.

It's worse in Python:
```python
try:
    foo
    except:
        bar
```
If I do `:NeoCompleteDisable` I get the correct output:
```python
try:
    foo
except:
    bar
```
## Environment Information
Tested in Vim 7.4.525 in Cygwin and 7.4.541 in OS X
## Minimal vimrc less than 50 lines
```vim
set nocompatible
set hidden hlsearch incsearch
set autoindent smartindent
set expandtab shiftwidth=4 softtabstop=4
set runtimepath+=$HOME/neocomplete.vim
syntax enable
let g:neocomplete#enable_at_startup = 1
autocmd FileType vim runtime indent/vim.vim
autocmd FileType python runtime indent/python.vim
```
## Reproducible ways from Vim starting
`:set filetype = python`
then insert `try:<CR>foo<CR>except:<CR>bar`

**Comment by Shougo** [comment]
Fixed.

**Comment by wilywampa** [comment]
Thanks!
