### ISSUE TITLE
indentkeys broken part two

### ISSUE THREAD

**Issue by wilywampa** [Shougo/neocomplete.vim#338]
Sorry, I have to reopen https://github.com/Shougo/neocomplete.vim/issues/337.

That solved the problem for whole words in `indentkeys` but not for individual characters. For example, `:` doesn't cause a re-indent in Python:
```python
if foo:
    bar
    else:
        ...
```
It seems like there's a lot of subtle changes/problems caused by calling `complete()` instead of using a completion function. In this case, if I exit completion mode (e.g. by pressing `<C-x><C-x>` before typing the `:` it does indent the line.

**Comment by Shougo** [comment]
Fixed.

> It seems like there's a lot of subtle changes/problems caused by calling complete() instead of using a completion function.

Yes.  I think `complete()` feature is not tested well.  But the changes are needed.
https://github.com/Shougo/neocomplete.vim/issues/328
