### ISSUE TITLE
about whole line completion

### ISSUE THREAD

**Issue by lythesia** [Shougo/neocomplete.vim#339]
when deleting chars with `<BS>` in insert-mode, the popup of whole-line-completion (with msg "back at original") whose content is just the current line text (or sometimes content of each line come to options in popup) realy annoys. 
i think it is the completion feature of vim itself, but triggered by neocomplete. any approaches to disable this feature or better solutions?

**Comment by itchyny** [comment]
Same problem here :(

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/333

**Comment by lythesia** [comment]
not work
![2015-01-07-093908_814x359_scrot](https://cloud.githubusercontent.com/assets/1119483/5639438/48cb94d4-9651-11e4-8920-ffa2814fab47.png)

vimrc section
```vim
let g:acp_enableAtStartup=0
let g:neocomplete#enable_at_startup=1
let g:neocomplete#enable_smart_case=1
let g:neocomplete#sources#syntax#min_keyword_length=3
let g:neocomplete#lock_buffer_name_pattern='\*ku\*'
if !exists('g:neocomplete#keyword_patterns')
  let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javacriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#ctags_command = "ctags"
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

```

**Comment by Shougo** [comment]
Please check you `<C-h>` mapping.
I think it is overwritten.

**Comment by lythesia** [comment]
you are right! i found that `<C-h>` and `<BS>` mappings occupied by both neocomplete and another plugin, now it works by disabling the latter. Thx!

**Comment by baboofei** [comment]
I have the exact same issue, however with C-H and BS mapped as stated in issue #333. I don't seem to be overwriting the mapping either. Any ideas how to diagnose?

**Comment by lythesia** [comment]
@baboofei  have you tried `:imap` to check `<BS>` and `<C-h>`?

**Comment by jeromenerf** [comment]
Same problems here. I have the BS and C-h mappings and I can't see them being overwritten.

**Comment by Shougo** [comment]
@jeromenerf Please read issue template and upload minimal .vimrc less than 50 lines.

https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by zhuweifeng314** [comment]
`:imap` show `<BS>` and `<C-H>` are mapped by *auto-pairs* plugin. Maybe you guys need to check that.

**Comment by jeromenerf** [comment]
Thanks! Actually on my side, it appears it was on odd brew build problem since the exact same setup was fine on Debian and openbsd version like builds.

**Comment by Shougo** [comment]
It is fixed in Vim 7.4.617.

**Comment by HJiahu** [comment]
my <BS> mappings occupied by both neocomplete and auto-pairs.if you use auto-pairs ,maybe you can delete this line in auto-pairs.vim:     "execute 'inoremap \<buffer> \<silent>\<BS>\<C-R>=AutoPairsDelete()\<CR>\'   .the line number is about 427 in auto-pairs.vim,and you can use <C-h> to delete two parenthesis in one hit.

**Comment by indiofish** [comment]
```vim
inoremap <expr><BS> pumvisible()? neocomplete#smart_close_popup()."\<C-h>" : AutoPairsDelete()
```
although it's an already closed issue, I would like to leave this solution for anyone who might also be using AutoPairs and suffering from collision over <BS> mappings.
