### ISSUE TITLE
Can't use any key to trigger OminComplete?

### ISSUE THREAD

**Issue by IceNature** [Shougo/neocomplete.vim#340]
I use [vim-dutyl](https://github.com/idanarye/vim-dutyl) with DCD to complete D code.The configurations of NeoComplete is the on in README. And I add `let g:neocomplete#sources#omni#input_patterns.d = '\h\w*'`in to my `_vimrc`  
  In D buffers, the OmniComlete can't be shown as I want, and vim output error message:
    Vim(let):E121: Undefined variable: words    
  But when I use YouCompleteMe, it can work well any where I type `<C-space>`.

**Comment by Shougo** [comment]
I think the omnifunc does not support neocomplete omnifunc integration.
You should use `g:neocomplete#force_omni_input_patterns` instead of `g:neocomplete#sources#omni#input_patterns`.

> But when I use YouCompleteMe, it can work well any where I type `<C-space>`.

If you want to complete candidates by omnifunc, you should map `<c-x><c-o>`.

**Comment by IceNature** [comment]
Solved. Thank you.
