### ISSUE TITLE
often scan files

### ISSUE THREAD

**Issue by kdurant** [Shougo/neocomplete.vim#342]
@Shougo the latest neocomplete has bugs. Often scan files, must use `<C-c>` to abort it
![1](https://cloud.githubusercontent.com/assets/2704364/5733026/3b9a8500-9bd7-11e4-9bb3-6bb872ab8b65.png)

**Comment by Shougo** [comment]
Duplicated issue.  I think it is not neocomplete issue.
Because, neocomplete does not show "Scanning:" message.
It is include file scan in Vim feature.

https://github.com/Shougo/neocomplete.vim/issues/331

**Comment by Shougo** [comment]
If you think neocomplete issue, please create minimal .vimrc and reopen it.

**Comment by Shougo** [comment]
I get it.  It is `<BS>` bug in Vim `complete()`.  You must map `<BS>` key.

https://github.com/Shougo/neocomplete.vim/issues/339

**Comment by kdurant** [comment]
@Shougo  What to map `<BS>`?

**Comment by Shougo** [comment]
```vim
    inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
    inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
```
