### ISSUE TITLE
Provide a way to not show a certain candidate

### ISSUE THREAD

**Issue by StephenHesperus** [Shougo/neocomplete.vim#343]
Maybe provide a key binding to mark a certain completion candidate not showing in dropdown list?

This will be very helpful at this scenario: During the first editing, type some words, after a save, find out a word that spells wrong, go back to change the word. __NOW__, I don't want to see the wrong word in completion dropdown menu any more, so I think there should be a way to "delete" that word from the candidates.
What do you think?
Or is there any way to achieve this?

**Comment by Shougo** [comment]
You should use `NeoCompleteBufferMakeCache` command.
