### ISSUE TITLE
neocomplete breaks wrapping behaviour in insert mode

### ISSUE THREAD

**Issue by jonhoo** [Shougo/neocomplete.vim#345]
Minimal `.vimrc`:
```
set runtimepath=~/.vim/bundle/neocomplete
set nocompatible

let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
set tw=5
```

Open `vim`, go to insert mode, type:
```
abcde<ENTER>
abcde fghij
```

`fghij` should be automatically wrapped to the next line as can be seen by running `vim -u NONE`, setting `tw=5` explicitly, and doing the same. If the second line starts with something that does **not** have a completion, wrapping works correctly.

Using `git bisect`, I've found that this issue was introduced in 1f7da025efe2141a8a771289b82b71b949066dea.

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/336

* neocomplete uses `complete()` instead of completefunc
* `complete()` uses line completion to implement it (I don't know why)
* line completion does not break lines(Yes, it is true)
* Wow, neocomplete does not break lines!

**Comment by petobens** [comment]
@Shougo  there is no way to fix this? It is a really annoying. Please, if possible, try to find a workaround. Thanks!

**Comment by Shougo** [comment]
Nothing.  You can use prevous version of neocomplete.

**Comment by petobens** [comment]
Mmm I see, what a pity. Why do you use complete() instead of completefunc?

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/328

**Comment by petobens** [comment]
I see. Thanks. I hope some day this will work again.

**Comment by Shougo** [comment]
I will report the problem in vim_dev later.

**Comment by petobens** [comment]
Thank you

**Comment by jonhoo** [comment]
@Shougo: Did you report this upstream in vim_dev in the end? Any chance you could post a link to track progress?

**Comment by Shougo** [comment]
This is already fixed in the patch.

https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/oO1u4L_Wf_QJ

**Comment by petobens** [comment]
@Shougo thank you. I've upvoted the patch

**Comment by petobens** [comment]
@jonhoo , @Shougo using vim with [patch 653](https://groups.google.com/forum/#!topic/vim_dev/ZEQzTII6eRg) the problem seems fixed.

**Comment by Shougo** [comment]
Yes.  Thanks.
