### ISSUE TITLE
neocomplete#close.popup() bind key

### ISSUE THREAD

**Issue by pythonproof** [Shougo/neocomplete.vim#347]
Hello, Shougo!
Is there any possible solution to return in normal mode when popupmenu is on with just a single Esc hit? 
1. I dont wanna use and remember one more key for neocomplete#cancel_popup() and then hit Esc
2. Already tired to hit Esc sometimes 2 and even 3 times to get in normal mode.

And the second question. I use neocomplete with jedi-vim and neosnippet. It works almost perfectly, but when i have jedi candidates to complete i cant control them with neocomplete#max_list and i need to hit "Enter" twice to close popup menu, because i have this code:
```vim
imap <expr><CR> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)"
            \: "\<C-r>=<SID>my_cr_function()<CR>"
function! s:my_cr_function()
  return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
```
 
Here is the screenshots for jedi-vim problem. I know it is because of the code above, but how i can fix this? And make neocomplete and jedi-vim to select-close with one hit?

Typing something:
![1](https://cloud.githubusercontent.com/assets/6261276/5801219/55f0b230-9ff1-11e4-8ae3-351c15ee6153.jpg)
Now i hit TAB-key to select:
![2](https://cloud.githubusercontent.com/assets/6261276/5801220/55f13c14-9ff1-11e4-83eb-2a40a800a863.jpg)
Now i hit Enter(Yes, in this example i can just hit space and continue typing but it is not a solution everywhere), and got this "back at original":
![3](https://cloud.githubusercontent.com/assets/6261276/5801222/55fcd290-9ff1-11e4-8b0c-39e270387076.jpg)
Hit Enter one more time and here we go:
![4](https://cloud.githubusercontent.com/assets/6261276/5801221/55f6687e-9ff1-11e4-9f4d-783bb56ed2cb.jpg)

And for Esc problem:
Typing:
![55](https://cloud.githubusercontent.com/assets/6261276/5801350/a5c35140-9ff2-11e4-9256-cc01c5f9ac43.jpg)
Hit ESC once(again this back at original):
![66](https://cloud.githubusercontent.com/assets/6261276/5801349/a5c1e382-9ff2-11e4-844a-d027bea2185b.jpg)
Hit one more time. Still in the insert mode:
![77](https://cloud.githubusercontent.com/assets/6261276/5801348/a5bf19cc-9ff2-11e4-9b5c-74564aec823d.jpg)
And need to hit Esc third time to return in normal mode.

Am I completelly stupid or do something wrong?
Sorry for bad English.

**Comment by Shougo** [comment]
OK.  I will check the problem.
Please read issue template and upload minimal .vimrc.

https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by PythonProof** [comment]
Ok. Will do it in few hours.

**Comment by PythonProof** [comment]
## Environment Information
 * OS: Arch Linux  Kernel: 3.18.2-2-ARCH
 * Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 14 2015 20:15:55)
Included patches: 1-580
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
```

**Comment by PythonProof** [comment]
minimal .vimrc. I tested it and ESC problem doesnt appear with it and works as should with just 1 hit returns to normal mode. So i need check my config. Sorry for my mistake. But ENTER problem is still here. I will add more screenshots.
``` vim
set nocompatible
set runtimepath+=~/.vim/bundle/neobundle.vim/
call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'davidhalter/jedi-vim'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
call neobundle#end()
filetype plugin indent on
syntax enable

let g:jedi#popup_on_dot = 0
let g:jedi#force_py_version = 3

map <F7> :NeoCompleteToggle<CR>
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#max_list = 20
let g:neocomplete#manual_completion_start_length = 2
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_auto_delimiter = 1
let g:neocomplete#enable_fuzzy_completion = 1
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.python =
\ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

imap <expr><CR> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)"
            \: "\<C-r>=<SID>my_cr_function()<CR>"
function! s:my_cr_function()
    return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
imap <expr><TAB> pumvisible() ? "\<C-n>"
            \: neosnippet#jumpable() ? "\<Plug>(neosnippet_jump)"
            \ : "\<TAB>"
if has('conceal')
    set conceallevel=2 concealcursor=i
endif
'''

**Comment by PythonProof** [comment]
jedi-vim ENTER problem(screenshots above) is still here with some "back at original in the status line".
+ Screenshots not even with jedi-vim, just with omnifunc:
Typing "im":
![11](https://cloud.githubusercontent.com/assets/6261276/5815873/80e4dbae-a0a2-11e4-8c87-1b21c76446c9.jpg)
Hit TAB-key:
![22](https://cloud.githubusercontent.com/assets/6261276/5815875/80e6d094-a0a2-11e4-817a-47f53bec9b52.jpg)
Hit ENTER and expecting to paste selected candidate and close popup, but when there is some kind of simmiliar candidates it does'nt close.
![33](https://cloud.githubusercontent.com/assets/6261276/5815874/80e5d77a-a0a2-11e4-825f-c057100a0beb.jpg)

I trully believe the problem is somewhere in this part:
''' vim
imap <expr><CR> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)"
            \: "\<C-r>=<SID>my_cr_function()<CR>"
function! s:my_cr_function()
    return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
'''

I expecting that ENTER hit with slelected or without selected candidate just close popup and doesnt appear new one before i type few letters again and doesnt jump onto new line as it jumps if previous code removed from .vimrc.

**Comment by Shougo** [comment]
Thanks.  Enter problem is reproduced in my environment.
I will fix it later.

> And the second question. I use neocomplete with jedi-vim and neosnippet. It works almost perfectly, but when i have jedi candidates to complete i cant control them with neocomplete#max_list

It is feature.   `g:neocomplete#force_omni_patterns` ignores neocomplete features like `g:neocomplete#max_list`.

**Comment by PythonProof** [comment]
Thanks. I will wait for it.
Any advice how i can map keys to works as i expected? Is this only problem with ENTER? Can i map something like Ctrl-K for now and make it works with just 1 hit?

**Comment by PythonProof** [comment]
Do i need to rename the issue?

**Comment by Shougo** [comment]
Fixed.

**Comment by pythonproof** [comment]
Are you sure?
![111](https://cloud.githubusercontent.com/assets/6261276/5818303/46531f58-a0bd-11e4-9e48-58f338af57c3.jpg)

**Comment by pythonproof** [comment]
I have found why ESC problem appears.
It was because of the plugin Townk/vim-autoclose. 
I will report this issue to him, but seems like it is not maintained plugin.

**Comment by Shougo** [comment]
OK.

**Comment by insanemal** [comment]
I'm doubting this is fixed.. I'm experiencing it again with some gusto.

**Comment by Shougo** [comment]
@insanemal Please read the issue template and create new issue without spf13-vim.

**Comment by insanemal** [comment]
Will do. Thaks.
