### ISSUE TITLE
Minor typo in 'autoload/neocomplete/cache.vim'

### ISSUE THREAD

**Issue by Coacher** [Shougo/neocomplete.vim#350]
Hello.

See the file mentioned in subject at 825ab03ac73a6169b96a2b641fa7b423ac96b686 on line 216:
```
 \ neocomplete#cache#encode_name('tags_pattens', a:filename)
```

Please change 'tags_pattens' to 'tags_patterns' (note missing 'r').

**Comment by Shougo** [comment]
It is already fixed.
