### ISSUE TITLE
g:neocomplete#enable_refresh_always removed - have to press <CR> twice to start new line

### ISSUE THREAD

**Issue by wilywampa** [Shougo/neocomplete.vim#352]
# Problems summary
This is another issue that came with 1f7da025efe2141a8a771289b82b71b949066dea (replacing `'completefunc'` with `complete()`). That commit broke `g:neocomplete#enable_refresh_always` functionality which was then removed entirely in ef90e68f69b9e837d290fafabccb7ad05491d7b9.

It used to be that candidates would reliably update as text was typed, but now I frequently find myself hitting `<CR>` to start a new line and observing that new candidates pop up in the menu and I have to hit `<CR>` a second time to end the line.

I made a [branch that brings back the old `manual_complete()` function to use as `'completefunc'`](https://github.com/wilywampa/neocomplete.vim/tree/completefunc) which fixes this issue. It is not possible to fix using `complete()` instead of `'completefunc'`? This is a critical feature for me.
## Expected
This is how it used to (and should) behave (candidates updated as I type and `<CR>` opens new line immediately):
![old](https://cloud.githubusercontent.com/assets/4472522/5881767/ade10294-a300-11e4-94df-cfcad73c6027.gif)
This is how it behaves now (have to hit `<CR>` to get new candidates and hit `<CR>` again to open new line):
![new](https://cloud.githubusercontent.com/assets/4472522/5881765/a6e7d6de-a300-11e4-86fb-f7d86b5f2320.gif)
## Environment Information
Tested in Vim 7.4.525 in Cygwin and 7.4.541 in OS X
## Minimal vimrc less than 50 lines
```vim
set nocompatible noshowmode
set hidden hlsearch incsearch
set autoindent smartindent
set expandtab shiftwidth=4 softtabstop=4
set shortmess+=c
set runtimepath+=$HOME/neocomplete.vim
syntax enable
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_refresh_always = 1
let s:count = 0
function! EchoCR()
  let s:count += 1
  echomsg 'pressed <CR>; count = '.s:count
  return "\<CR>"
endfunction
inoremap <expr> <cr> EchoCR()
```
## Reproducible ways from Vim starting
Enter the text show in the .gifs or copy/paste:
```
# parse
# PASSED
# paste
# pants
# passing
# passer
```
then do `:NeoCompleteBufferMakeCache` and type `pass` and hit `<CR>`.

**Comment by Shougo** [comment]
It is feature.  You must map `<CR>` key.

	" <CR>: close popup and save indent.
	inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
	function! s:my_cr_function()
	  return neocomplete#close_popup() . "\<CR>"
	  " For no inserting <CR> key.
	  "return pumvisible() ? neocomplete#close_popup() : "\<CR>"
	endfunction

**Comment by wilywampa** [comment]
That is not a solution because it prevents ever seeing the candidates that should be in the menu after typing "pass". In the first attachment, the candidates `PASSED`, `passing`, and `passer` show up after typing "pass" and before pressing `<CR>`. In the second image, those candidates are not displayed until after pressing `<CR>`. Mapping `<CR>` the way you suggest makes those candidates never show up:
![map_cr](https://cloud.githubusercontent.com/assets/4472522/5911475/37896bf6-a583-11e4-922f-f0d68dafa8aa.gif)

**Comment by Shougo** [comment]
I get it.  It is `converter_case` feature.
You should disable it.

To implement `g:neocomplete#enable_refresh_always`, I must use completefunc feature.
I don't want to it.

**Comment by Shougo** [comment]
@wilywampa Please update neocomplete.

**Comment by wilywampa** [comment]
@Shougo Thanks for looking into this more. I find your plugins hugely useful and I'm grateful for them which is probably hard to see from the issues I open.

I don't think the problem is related to case sensitivity. In the specific example, yes, a case insensitive match does make "PASSED" show up. The main problem seems to be that the list is not updated unless the user types a letter that's not part of a match currently in the menu. That means some fuzzy completions don't appear when they used to with `g:neocomplete#enable_refresh_always`. Also the current text appearing in the menu is a (small) waste of screen space.

I understand not wanting to use `completefunc` because it causes incompatibilities but there has to be a way to move forward without losing old functionality. I have a few ideas.

The easiest/most feasible way is to use `InsertCharPre` to update the list as the user types. I know there is a `g:neocomplete#enable_insert_char_pre` option but the difference between that and `{'refresh': 'always'}` is that `InsertCharPre` adds the next character to `cur_text` whereas refreshing leaves `cur_text` as is. Modifying `neocomplete#helper#get_cur_text()` so `v:char` isn't appended to `complete_str` seems to result in behavior identical to refresh_always. The challenge here is - as stated in NeoComplete's help - that `<BS>` doesn't continue completion. However I think `<BS>` can be mapped to tell NeoComplete to call `complete()` again to continue the completion without too much difficulty.

Another option would be to use the `InsertCharPre` event in a different way - use it to check if the user has finished typing an entire candidate and call `complete()` with new results if so. I really have no idea how hard this would be because I don't know how to check what is currently visible in the menu or what the relevant part of the current text to compare to is.

Finally, do you think it might be worth suggesting on the Vim development mailing list a third argument to Vim's `complete()` function that allows behavior like having `{'refresh': 'always'}` in the return value from `completefunc`? For example, a callback funcref that Vim could use to check if the list should be refreshed would get the job done.

P.S. I tried the `<CR>` map you suggested for a little while and noticed that auto completion doesn't work on the first word typing after pressing `<CR>` if the word before pressing `<CR>` was in the first column:
![map_cr_new](https://cloud.githubusercontent.com/assets/4472522/5931676/e0cfdd6e-a65d-11e4-85a3-5577f3dcf62f.gif)

**Comment by Shougo** [comment]
> P.S. I tried the <CR> map you suggested for a little while and noticed that auto completion doesn't work on the first word typing after pressing <CR> if the word before pressing <CR> was in the first column:

It is bug.  I will fix it later.

**Comment by Shougo** [comment]
> The easiest/most feasible way is to use InsertCharPre to update the list as the user types. I know there is a g:neocomplete#enable_insert_char_pre option but the difference between that and {'refresh': 'always'} is that InsertCharPre adds the next character to cur_text whereas refreshing leaves cur_text as is. Modifying neocomplete#helper#get_cur_text() so v:char isn't appended to complete_str seems to result in behavior identical to refresh_always. The challenge here is - as stated in NeoComplete's help - that <BS> doesn't continue completion. However I think <BS> can be mapped to tell NeoComplete to call complete() again to continue the completion without too much difficulty.

I think to improve `g:neocomplete#enable_insert_char_pre`  is better.
But your explanation is not easy to understand.
Please explain it more clearly.

**Comment by wilywampa** [comment]
I'm sorry, it looks like I underestimated the difficulty of using InsertCharPre. All I did originally was:

1. `let g:neocomplete#enable_insert_char_pre = 1`
2. delete the line in `neocomplete#helper#get_cur_text()` that does `let complete_str .= v:char`, and
3. `inoremap <expr> <BS> pumvisible() ? '<BS>'.neocomplete#mappings#manual_complete() : '<BS>'`

I thought that came close to the old behavior but I tried using that setup for awhile today and there are a lot of problems (as you can probably guess). For example the completion results are very different after `<BS>` because I needed to use manual_complete instead of auto_complete, completion of Vim code doesn't work after typing '#', a fully typed candidate still shows up in the menu, and so on. It was just a bad idea.

**Comment by Shougo** [comment]
Yes.  It is problem.  I will fix it.

**Comment by Shougo** [comment]
Fixed the problem.
