### ISSUE TITLE
Link doesn't exist in the doc file

### ISSUE THREAD

**Issue by llfm** [Shougo/neocomplete.vim#353]
Shougo, your repo `https://github.com/Shougo/neoinclude.vim` doesn't exist.
In the docs: [here](https://github.com/Shougo/neocomplete.vim/blob/master/doc/neocomplete.txt#L177) and [here](https://github.com/Shougo/neocomplete.vim/blob/master/doc/neocomplete.txt#L1471).

**Comment by Shougo** [comment]
Yes.  I will implement the feature after neovim is completed...

**Comment by llfm** [comment]
Ah, ok. Didn't know.
