### ISSUE TITLE
Neocomplete autoselects first candidate with jedi-vim

### ISSUE THREAD

**Issue by person808** [Shougo/neocomplete.vim#354]
Related to #18 

Problem:

Neocomplete autoselects the first suggestion when using it with jedi-vim. (The gifs in #18 show the exact same problem.)

Expected behavior:

No suggestion is selected initially.

Minimal .vimrc:
```
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#auto_completion_start_length = 1
let g:neocomplete#enable_camel_case = 1
let g:neocomplete#enable_auto_select = 0
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#use_tabs_not_buffers = 0
let g:jedi#show_call_signatures = 2
let g:jedi#force_py_version = 3
let g:jedi#popup_select_first = 0
let g:neocomplete#force_omni_input_patterns.python =
	\ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.
First candidate is not selected.

**Comment by Shougo** [comment]
Your .vimrc is not minimal.
It must be full .vimrc.

Minimal .vimrc is like this.
https://github.com/Shougo/neocomplete.vim/issues/355

**Comment by person808** [comment]
I was setting all of my jedi settings in ~/.vim/after/python.vim. Everything worked as expected after moving them to my .vimrc.

**Comment by Shougo** [comment]
OK.

**Comment by petobens** [comment]
@person808  I do want neocomplete to select the first candidate from the popup menu. How did you do to achieve that? Thanks!

**Comment by person808** [comment]
@petobens Is `g:jedi#popup_select_first = 1`? It should be by default.

**Comment by petobens** [comment]
@person808 Thanks but it doesn't work. See #355
