### ISSUE TITLE
Autoselect first candidate with jedi-vim

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#355]
I have exactly the opposite problem when compared to #354.  Consider the following minimal vimrc:

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    set runtimepath+=$DOTVIM/bundle/neocomplete
    set runtimepath+=$DOTVIM/bundle/jedi

    filetype plugin indent on

    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_auto_select = 1
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python =
        \ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

    augroup py_comp
        au!
        au FileType python setlocal omnifunc=jedi#completions
    augroup END

    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    if has('python3')
        let g:jedi#force_py_version = 3
    endif

And in a new file (`foo.py`) type `str.` and you will see (as in the Gif) that neocomplete doesn't select the first candidate automatically. I do want neocomplete to select the first candidate.

![blah](https://cloud.githubusercontent.com/assets/2583971/5902467/6dc5c2c0-a559-11e4-86d2-cde6939e6a70.gif)

**Comment by Shougo** [comment]
OK.  I get it.

**Comment by Shougo** [comment]
You can vote the feature in vim_dev.

**Comment by petobens** [comment]
Thanks @Shougo for the explanation . I really need this feature. Can you post the relevant URL in the vim_dev group so I can upvot the patch ? Thank you

**Comment by petobens** [comment]
@Shougo  thanks for the explanation. I have voted for the patch in vim_dev. I really hope someday they will merge it.

**Comment by petobens** [comment]
Shougo your patch has been included has patch [775](https://groups.google.com/forum/#!topic/vim_dev/9BGZNGA7Ucg). How can I make this work now?

**Comment by Shougo** [comment]
I will add the support.
Please wait me.

**Comment by Shougo** [comment]
Implemented.

**Comment by petobens** [comment]
Thank you!!!!!
