### ISSUE TITLE
Severe lag in Insert mode

### ISSUE THREAD

**Issue by NHungate** [Shougo/neocomplete.vim#364]
I'm experiencing some heavy lag while writing within Script tags, specifically for Ember.js. 
The issue comes about when writing HTML tags within script tags for Handlebars.

Example:
```
<script type="text/x-handlebars" data-template-name="index">
  <h1>Title</h1>
  <p>Paragraph text</p>
  <img {{bind-attr src='logo'}} alt="Logo" />
</script>
```

After a heavy delay, the following displays in the command bar.
```
Skipped.
-- User defined completion (^U^N^P) Pattern not found
```

Edit:
Found the source of the issue. In the HTML file, one of the `<script>` tags in the head had a folder path that included a period in the name, causing the stuttering and crashing.
`<script src="vendors/ember.js/ember.js"></script>`
Renaming `ember.js/ember.js` to `emberJS/ember.js` corrected the issue

**Comment by Shougo** [comment]
OK.  I will test it.

Please read the issue template and upload minimal .vimrc.

https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by NHungate** [comment]
# Problems summary

## Expected

Heavy lag with eventual Vim crash when developing website in emberJS.

## Environment Information
 * OS: Mac OS X 10.10.2
 * Vim version: 7.4

## Minimal vimrc less than 50 lines

```
" Your vimrc
set nocompatible

set runtimepath+=~/.vim/bundle/neocomplete.vim/

set fo+=aw
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
set tw=10 " just for testing purposes
  
" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
syntax on
```

## Reproducable ways from Vim starting

 1. Create a file `index.html` with the contents below
 2. Write a tag inside the script tag with type "text/x-handlebars"
 3. Neocomplete will stutter and hang
 4. Vim will eventually crash with continued use

## Screen shot (if possible)

```
<html>
	<head>
        <script src="js/libs/jquery-1.11.2.min.js"></script>
        <script src="js/libs/ember.min.js"></script>
    </head>
    <body>
        <script type="text/x-handlebars" data-template-name="application">
            …
        </script>
    </body>
</html>
```

EmberJS/jQuery files must be local
Also occurs when `filetype plugin on` is set.

**Comment by Shougo** [comment]
Confirmed.  It is omnicomplete problem.
I cannot fix it.
To fix it, you must disable omnifunc by `:setlocal omnifunc=`.
