### ISSUE TITLE
clang_complete <CR> mapping issue

### ISSUE THREAD

**Issue by Hamled** [Shougo/neocomplete.vim#366]
Part of the way clang_complete works involves remapping ```<CR>``` in insertion mode when the completion list is active, and unmapping it when the list is closed (either through selection of an entry or canceling the menu).

Unfortunately it appears that by using clang_complete with neocomplete, the unmapping does not happen. Thus if clang_complete is used with neocomplete and there are any other plugins loaded which also remap ```<CR>```, the results are similar to what is described in Rip-Rip/clang_complete#431.

That issue was fixed in Rip-Rip/clang_complete#439, but again with neocomplete the fix's code is not executed or is somehow executed incorrectly. As I'm not particularly well versed in vimscript, I'm not sure exactly why that is.

Right now the workaround I have found is to disable clang_complete's default keymappings, which can be done by setting ```g:clang_default_keymappings = 0``` in vimrc. This may not be ideal as people might wish to use the default clang_complete mappings.

If the default clang_complete mappings are incompatible with neocomplete, or if the ```<CR>``` unmapping issue cannot be fixed, then the FAQ should be updated to recommend using the setting above.

**Comment by Shougo** [comment]
Thanks.  I updated it.
