### ISSUE TITLE
Global auto-completion lock

### ISSUE THREAD

**Issue by bohrshaw** [Shougo/neocomplete.vim#367]
AFAIK, whether auto-completion is locked is controlled by `b:neocomplete.lock`, which is buffer local. But I think a global state is very useful and personally I always prefer manual-completion *over* auto-completion.
I could reset that buffer local variable through `autocmd`, but I think a global variable such as `g:neocomplete_lock` would be better if it get checked.

**Comment by Shougo** [comment]
I don't want to add the feature.

> I think a global state is very useful and personally I always prefer manual-completion over auto-completion.

neocomplete supports manual completion.  But it is auto completion plugin.
I don't want to add the features for manual completion.
