### ISSUE TITLE
Vim crashes with SEGV in lua plugin

### ISSUE THREAD

**Issue by edwintorok** [Shougo/neocomplete.vim#368]
Neocomplete is only lua plugin I use (previously I was using neocomplcache), and Vim randomly segfaults, see this Debian bugreport that I just opened:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778821

**Comment by Shougo** [comment]
Please use latest Vim binary.  It is already fixed.

**Comment by dagfinnr** [comment]
Is there any way to get a MacVim that has this fix?

**Comment by Shougo** [comment]
Current MacVim version is 7.4.505.

https://github.com/macvim-dev/macvim

Unfortunatelly, It is too old.
You should contact MacVim maintainer to update it.
