### ISSUE TITLE
NeoComplete does not show Neosnippets shorter than 3 characters in length

### ISSUE THREAD

**Issue by jkowalski3** [Shougo/neocomplete.vim#369]
Hi,
I am not sure this is a bug or feature but I have noticed that Neocomplete does not show  short snippets (2 characters in length for example) in the auto-completion popup window. Increasing snippet length to 3 sorts this problem out but there are many cases where I like to keep short snippet names like "if", "wh", ...
Neosnippet expansion still works though. For example, after typing "if" you can expand the snippet without problem. It is just now showing in the auto completion window, which makes the usage bit hard.

thanks
Jack

**Comment by Shougo** [comment]
It is feature.  You can change the behavior by the configuration.

```vim
let g:neocomplete#auto_completion_start_length = 1
```
