### ISSUE TITLE
neocomplete and snipmate

### ISSUE THREAD

**Issue by pdoak** [Shougo/neocomplete.vim#373]
If I set completion to \<tab\> using the recommended mapping:

`inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"`

it seems to disable [snipmate](https://github.com/garbas/vim-snipmate) completion as snipmate also uses \<tab\> as the completion key. Is it possible for [neocomplete](https://github.com/Shougo/neocomplete.vim) and [snipmate](https://github.com/garbas/vim-snipmate) to coexist with both using the \<tab\> key for completion?

**Comment by Shougo** [comment]
I don't know snipMate feature.  But neosnippet can do it.

```vim
	imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	 \ "\<Plug>(neosnippet_expand_or_jump)"
	 \: pumvisible() ? "\<C-n>" : "\<TAB>"
	smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	 \ "\<Plug>(neosnippet_expand_or_jump)"
	 \: "\<TAB>"
```

**Comment by pdoak** [comment]
Shougo

I disabled [snipmate](https://github.com/garbas/vim-snipmate) and loaded [neosnippet](https://github.com/Shougo/neosnippet.vim) and put your suggested code into my .vimrc and I get the following message: `E117: Unknown function: neosnippet#expandable_or_jumpable`

Update: Even though I thought I had loaded neosnippet, it must have not loaded. It seems to be working now. Thank you.
