### ISSUE TITLE
Method to collect results from omnifunc without selecting first result

### ISSUE THREAD

**Issue by expipiplus1** [Shougo/neocomplete.vim#374]
For example I type the beginning of an identifier and NeoComplete hasn't found a match so I hit C-x C-o to call the omnifunc. The ideal behavior here would be for NeoComplete to add the results from omnifunc to its list and allow me to select from them as I like (for example fuzzy matching or smart case). Here "C-x C-o" could be any keypress, that's not important.
At the moment what happens is omnifunc takes over and none of the NeoComplete settings seem to be in effect.
Occasionally I'm able to get the completion list populated properly, but this is a little sporadic.

Hopefully there's already a way to do this.

**Comment by Shougo** [comment]
> The ideal behavior here would be for NeoComplete to add the results from omnifunc to its list and allow me to select from them as I like (for example fuzzy matching or smart case).

https://github.com/Shougo/neocomplete.vim/issues/344

It is same feature?

> At the moment what happens is omnifunc takes over and none of the NeoComplete settings seem to be in effect.

Don't effect in `g:neocomplete#force_omni_patterns` is feature.
Please explain the example.

**Comment by expipiplus1** [comment]
Sorry, Github ate some of the formatting, I've corrected the original post.

I don't think it's the same issue as #344 

A more succinct way of putting this might be:
In order to get the results from the omnifunc, I type C-x C-o. However doing so autoselects the first match. Is there a function I can call which takes the results from omnifunc, and inserts them into the list of suggestions NeoComplete already has?

So for example I start typing a word, and decide I'd like to see the results from the omnifunc, I call this function and NeoComplete adds the results from omnifunc to the popup, without the extra behaviors of C-x C-o

**Comment by Shougo** [comment]
You should use `<C-x><C-o><C-p>` mapping.

**Comment by expipiplus1** [comment]
That's much better, thanks!
I think that after `<C-x><C-o><C-p>` fuzzy searching doesn't work due to #344; Is this correct?

**Comment by Shougo** [comment]
No.  It is Vim's feature.
