### ISSUE TITLE
Method to run omnifunc over already typed string

### ISSUE THREAD

**Issue by expipiplus1** [Shougo/neocomplete.vim#375]
It would be nice to type a fuzzy string for example `gcrcnt` and call a function to complete to `glCreateContext` (Or display a popup for multiple matches). I imagine though that this would be up to the omnifunc, is there anything NeoComplete can do about this?

**Comment by Shougo** [comment]
Dup of #344

If you use `<C-x><C-o>`, it is impossible.
It is Vim's feature.  Omnifunc does not support fuzzy matching.
