### ISSUE TITLE
NeoComplete not working after update

### ISSUE THREAD

**Issue by pratz** [Shougo/neocomplete.vim#376]
Environment:
- Ubuntu 14.04
- Vim version 7.4 enabled with lua

After update "PluginUpdate" Neocomplete stopped working.

I did:
https://gist.github.com/pratz/d513dde3c2ac11ca59c8

I used the commit id from my other box, where Neocomplete was not updated.

After I downgraded NeoComplete everything seems to work.

**Comment by pratz** [comment]
Being more specific, after this commit "30497b751fe3c8d6cc25a8abbc17a0d6d8dc1e38" NeoComplete has stopped working for me.

**Comment by pratz** [comment]
I think this is the commit which is creating a problem https://github.com/Shougo/neocomplete.vim/commit/3d03ded56c4ed35821cc64742bef784b50de4e7c

**Comment by Shougo** [comment]
Please upload minimal .vimrc and reproduce ways.
https://github.com/Shougo/neocomplete.vim/issues/236

I will check it.

> Vim version 7.4 enabled with lua

Please upload your Vim version.

**Comment by Shougo** [comment]
I think your Vim version is old.
I want to know your Vim version.

**Comment by pratz** [comment]
Hi,

Vim version:
https://gist.github.com/pratz/5f63832e07a2b2b1afe2

System Info:
https://gist.github.com/pratz/085ea585f476fb03364f

**Comment by Shougo** [comment]
Thanks.  Fixed.
