### ISSUE TITLE
Broken repeat

### ISSUE THREAD

**Issue by ruedigerha** [Shougo/neocomplete.vim#377]
It seems dot-repeat functionality is broken with neocomplete active in some cases, namely when writing more than one word in a single operation.

Absolutely minimal vimrc is sufficient:

    set nocompatible
    set runtimepath^=$VIMUSERRUNTIME/bundle/neocomplete
    let g:neocomplete#enable_at_startup = 1

I type something with more than one word, e.g. `Data.List`. Then `<Escape>0.` gives `Data.ListData.List` as expected.

Now I undo everything and repeat the same steps (now after the second letter of each word the neocomplete popup - well, pops up). The result is now `DastData.List`.

**Comment by Shougo** [comment]
#332
