### ISSUE TITLE
cgn doesn't work when neocomplete "unlocked"

### ISSUE THREAD

**Issue by markwu** [Shougo/neocomplete.vim#378]
I have a weird issue, the `cgn` command does not work when neocomplete unlocked.  For example, I have following text:

```
test 1
test 2
test 3
```

I use search `/` command in to search `test`, than I use `cgn` to replace `test` to `home`,  then I use `.` to repeat the replacement.

When neocomplete unlocked (the autocompletetion enabled), the result will become

```
home 1  // (completion popup menu show here and let me complete the word `home` .... )
e 2
e 2
```

Sometimes, I even get

```
home 1  // (completion popup menu show here and let me complete the word `home` .... )
 2
 2
```

But, when I locked neocomplete (the autocompletetion disabled), the result is what I need.

```
home 1
home 2
home 3
```

About the `gcn` command, you can see the video http://vimcasts.org/episodes/operating-on-search-matches-using-gn/ for detail.

Is this the normal behavior or a bug?

**Comment by Shougo** [comment]
#332

**Comment by markwu** [comment]
So, you mean I have to upgrade to vim 7.4.633 to get `.` repeat to work?

**Comment by Shougo** [comment]
Yes.
