### ISSUE TITLE
Lack of "if_lua" without root permission

### ISSUE THREAD

**Issue by peidong** [Shougo/neocomplete.vim#379]
My vim version is 7.4.364 and my Linux is Ubuntu server 12.04.

When I installed neocomplete, it said I don't have "if_lua".

However I don't have root permission of the Ubuntu server, so that I cannot do "sudo" commands. Could I install "if_lua" feature without "sudo commands"?

**Comment by Shougo** [comment]
You should compile Vim which is enabled if_lua manually.
