### ISSUE TITLE
enable_smart_case = 1 breaks dot repeat

### ISSUE THREAD

**Issue by opennota** [Shougo/neocomplete.vim#380]
The `.` (dot) command fails to repeat last change when using neocomplete plugin with `enable_smart_case = 1`.

Steps to reproduce:

1. Install neocomplete (copy autoload, doc and plugin folders to the ~/.vim directory). Use the following .vimrc:

    let g:neocomplete#enable_at_startup = 1
    " Use smartcase.
    let g:neocomplete#enable_smart_case = 1

2. Open [align.txt](http://pastebin.com/raw.php?i=9794YxEK).

3. Move to the first `case` keyword.

4. Press `cw` and type `align`.

5. Press `Esc`.

6. Move to the second `case`.

7. Press `.` (dot).

8. Repeat works incorrectly.

GIF screencast: http://i.imgur.com/L3YjYGL.gif

    ~ $ vim --version                                                                             
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar  8 2015 13:53:42)
    Included patches: 1-622
    Modified by Gentoo-7.4.622
    Compiled by portage@localhost
    Huge version without GUI.  Features included (+) or not (-):
    +acl             +farsi           +mouse_netterm   +syntax
    +arabic          +file_in_path    +mouse_sgr       +tag_binary
    +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
    -balloon_eval    +float           +mouse_urxvt     -tag_any_white
    -browse          +folding         +mouse_xterm     -tcl
    ++builtin_terms  -footer          +multi_byte      +terminfo
    +byte_offset     +fork()          +multi_lang      +termresponse
    +cindent         +gettext         -mzscheme        +textobjects
    +clientserver    -hangul_input    +netbeans_intg   +title
    +clipboard       +iconv           +path_extra      -toolbar
    +cmdline_compl   +insert_expand   +perl            +user_commands
    +cmdline_hist    +jumplist        +persistent_undo +vertsplit
    +cmdline_info    +keymap          +postscript      +virtualedit
    +comments        +langmap         +printer         +visual
    +conceal         +libcall         +profile         +visualextra
    +cryptv          +linebreak       +python/dyn      +viminfo
    -cscope          +lispindent      +python3/dyn     +vreplace
    +cursorbind      +listcmds        +quickfix        +wildignore
    +cursorshape     +localmap        +reltime         +wildmenu
    +dialog_con      +lua             +rightleft       +windows
    +diff            +menu            -ruby            +writebackup
    +digraphs        +mksession       +scrollbind      +X11
    -dnd             +modify_fname    +signs           +xfontset
    -ebcdic          +mouse           +smartindent     -xim
    +emacs_tags      -mouseshape      -sniff           +xsmp_interact
    +eval            +mouse_dec       +startuptime     +xterm_clipboard
    +ex_extra        -mouse_gpm       +statusline      -xterm_save
    +extra_search    -mouse_jsbterm   -sun_workshop    -xpm
       system vimrc file: "/etc/vim/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -pipe -march=native -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
    Linking: x86_64-pc-linux-gnu-gcc   -Wl,-E  -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -ldl  -L/usr/lib -lluajit-5.1 -Wl,-E -Wl,-O1 -Wl,--as-needed  -L/usr/lib64/perl5/5.20.1/x86_64-linux/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lc

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/332

It is fixed in Vim 7.4.633

http://ftp.vim.org/vim/patches/7.4/7.4.633
