### ISSUE TITLE
Problem getting neocomplete to work with existing tag files

### ISSUE THREAD

**Issue by weaksauce** [Shougo/neocomplete.vim#381]
set tags=./tags;,tags;

but neocomplete doesn't use the tag file that should be found by that preference. is this a bug?

**Comment by Shougo** [comment]
It is not bug.  It is intended behavior.
Please read `:help g:neocomplete#sources#tags#cache_limit_size`.

**Comment by weaksauce** [comment]
seems like it should be an option as completing from the tags is a very common thing and, without that, it reduces the utility of this plugin considerably.

**Comment by Shougo** [comment]
I don't think so.  Tags completion is too heavy.

**Comment by Shougo** [comment]
We need this option because, ....
https://github.com/Valloric/YouCompleteMe/issues/1414

**Comment by weaksauce** [comment]
I see. I still see it as a deal breaker for my use of this otherwise useful plugin. It would be nice to have it as an option that you could set, even if it slows down completions because without it writing rubymotion code become unwieldy in vim. 

Perhaps this could be added when you move this plugin over to neovim? if it's an asynchronous plugin at that point it would be less intrusive to the user experience if you think it's "too slow" as even if it's a little slower than ideal, it is faster than writing long method names.

**Comment by Shougo** [comment]
> Perhaps this could be added when you move this plugin over to neovim? if it's an asynchronous plugin at that point it would be less intrusive to the user experience if you think it's "too slow" as even if it's a little slower than ideal, it is faster than writing long method names and options. 

I will create new completion plugin for neovim.

**Comment by lukepass** [comment]
Hello, sorry for resurrecting this old post, but did you create that new completion plugin for Neovim?
I need tags for my PHP project but I have an extremely large tags file (more than 50 MB).

Thanks.

**Comment by lambdalisue** [comment]
https://github.com/Shougo/deoplete.nvim

**Comment by Shougo** [comment]
Note: deoplete also has the limit variable `deoplete#tag#cache_limit_size`.
Because the huge tag file analysis is too slow.
No magic.
