### ISSUE TITLE
Can we move the configuration out of the .vimrc(_vimrc) file ?

### ISSUE THREAD

**Issue by daviestang** [Shougo/neocomplete.vim#385]
Can we move the configuration out of the .vimrc(_vimrc) file ? I just want to keep the vimrc file clean.

**Comment by ujihisa** [comment]
You can type command to setup every time you launch vim, instead of saving them in vimrc.

**Comment by daviestang** [comment]
@ujihisa Can I move these configuration to other *.vim file then put it in plugin directory ?

**Comment by ujihisa** [comment]
Yes
