### ISSUE TITLE
lua53.dll issue

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#387]
I use [this](https://tuxproject.de/projects/vim/) windows build. If I use `lua52.dll` then it works fine but when I try using `lua53.dll` neocomplete complains that it doesn't have `if_lua` (when it actually does have it). And when I run `:lua print("Hello, Vim!")` I get the following error

    E448: Could not load library function lua_replace
    Lua library cannot be loaded.

**Comment by Shougo** [comment]
It is not neocomplete error.
Please report the problem to vim_dev.

**Comment by petobens** [comment]
Okay, I will report it. Thanks
