### ISSUE TITLE
Neocomplete & Eclime

### ISSUE THREAD

**Issue by zhamlin** [Shougo/neocomplete.vim#39]
Using [Eclime](http://eclim.org/index.html) when editing java files I get auto-completion when pressing "<C-x><C-U>". ![untitled1](https://f.cloud.github.com/assets/1034743/805607/1ed76ca0-ee2a-11e2-9cf0-4a2a0447492e.png)
With Neocomplete installed this no longer happens. Instead I get this
![untitled2](https://f.cloud.github.com/assets/1034743/805640/ca01e24a-ee2a-11e2-98a7-45c5c92ce139.png)
 Is there any to add those results to neocompletes?

**Comment by SteveCharleston** [comment]
All of the configurations above are still a little bit wrong, as Shougo has suggested you have to use force_omni_input_patterns, so the correct configuration is:
```
if !exists('g:neocomplete#force_omni_input_patterns')                                                                                                  
    let g:neocomplete#force_omni_input_patterns = {}                                                                                                   
endif                                                                                                                                                  
let g:neocomplete#force_omni_input_patterns.java =                                                                                                     
    \ '\%(\h\w*\|)\)\.\w*'
```

**Comment by mr** [comment]
Ah, my bad. I actually had that in my configuration, but I must have typed it wrong or copied something wrong. I'll edit my comment to avoid confusion.
