### ISSUE TITLE
Completion before brace

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#390]
Consider the following minimal vimrc
```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath=$DOTVIM,$VIMRUNTIME
set runtimepath+=$DOTVIM/bundle/ultisnips
set runtimepath+=$DOTVIM/bundle/neocomplete
set runtimepath+=$DOTVIM/bundle/vimproc

filetype plugin indent on
let g:tex_flavor = 'latex'

let g:UltiSnipsSnippetDirectories = ["texsnippet"]

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer', 'ultisnips']

if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns._ = '[A-Za-zá-úÁ-ÚñÑ_][0-9A-Za-zá-úÁ-ÚñÑ_]*'
let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)

inoremap <silent><expr><CR> pumvisible() ?
    \ (len(keys(UltiSnips#SnippetsInCurrentScope())) > 0 ?
    \ neocomplete#close_popup()."\<C-R>=UltiSnips#ExpandSnippet()\<CR>" :
    \ neocomplete#close_popup()) : "\<CR>"
```

and create two files: i) `$DOTVIM/texsnippets/tex.snippets`:
```
snippet crs "Cleverref section" w
\cref{sec:${1}}$0
endsnippet

snippet crs1 "Cleverref section" w
\cref{sec:${1}$0
endsnippet

snippet crs2 "Cleverref section" w
\cref{sec:${1} }$0
endsnippet
```
and ii) `foo.tex`:
```tex
\label{sec:foo}
```

Now open the `foo.tex` file and in a new line type `crs` and press enter. You will see, as in the GIF, that the neocomplete does not complete `sec:foo`. On the other hand if you expand the snippets `crs1` and `crs2` neocomplete does complete `sec:foo`. So why is it that neocomplete cannot complete from buffer completion when there is a brace immediately after the text to be completed (i.e when using the `crs` snippet)?

![blah](https://cloud.githubusercontent.com/assets/2583971/7115391/b2d074fe-e1be-11e4-8dd4-613d41ba5f54.gif)

**Comment by Shougo** [comment]
I will check it...
But I think it is cache feature.
neocomplete cannot load file cache immediately.

**Comment by petobens** [comment]
Thank you.

**Comment by Shougo** [comment]
I tested it.  But I cannot reproduce it.
I think in your Windows envirinment, to load cache is slow.
You should load the cache manually by `:NeoCompleteCachingBuffer`.

**Comment by petobens** [comment]
So basically when you try my minimal vimrc you can complete before the brace? Why is it that the loading is slow just for the brace but not in the other cases?

I tried running `:NeoCompleteBufferMakeCache` just before the `crs` snippet but I still cannot complete before the brace.

**Comment by Shougo** [comment]
I don't want to test UltiSnips.  So please remove UltiSnips from the test case.

My tested vimrc.

```vim
set nocompatible

set runtimepath+=~/work/neocomplete.vim
set runtimepath+=~/work/vimproc

filetype plugin indent on
let g:tex_flavor = 'latex'

let g:UltiSnipsSnippetDirectories = ["texsnippet"]

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer', 'ultisnips']

if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns._ = '[A-Za-zá-úÁ-ÚñÑ_][0-9A-Za-zá-úÁ-ÚñÑ_]*'
let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)
```

1. $ vim -u test.vimrc test.tex
2. `o\cref{sec:`
3. `sec:foo` is completed.

**Comment by petobens** [comment]
@Shougo I have no problem completing `\cref{sec:` (in fact my second snippet, `crs1`, does exactly that and works just fine).
The problem appears when I try `\cref{sec:|}` and the cursor is placed just before the closing brace (at the position marked with `|`).

A long time ago I reported a similar problem in #146.

**Comment by Shougo** [comment]
Confirmed.  You should create test case like this:

```tex
\label{sec:foo}
\label{sec:}
```

It is correct foo.tex.  I reproduced the problem.  I will search it.

**Comment by petobens** [comment]
Thank you.

**Comment by Shougo** [comment]
Fixed it.

**Comment by petobens** [comment]
Thank you so much! Your plugins are awesome and the support is incredible.

**Comment by petobens** [comment]
HI @Shougo, I have this problem/issue again:

>I have no problem completing \cref{sec: (in fact my second snippet, crs1, does exactly that and works just fine).
The problem appears when I try \cref{sec:|} and the cursor is placed just before the closing brace (at the position marked with |).

Can you please fix it? Thank you.

**Comment by Shougo** [comment]
@petobens I cannot reproduce the problem.

```vim
set nocompatible

set runtimepath+=~/work/neocomplete.vim

filetype plugin indent on
let g:tex_flavor = 'latex'

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer', 'ultisnips']

let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)
setfiletype tex
```

`sec:foo` is completed correctly.

**Comment by petobens** [comment]
Thank you @Shougo. I think the problem is related to #290.  I posted a comment there explaining my problem.

**Comment by petobens** [comment]
Please consider once again the setting in my first post [above](https://github.com/Shougo/neocomplete.vim/issues/390#issue-68084210). i.e use as a minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath=$DOTVIM,$VIMRUNTIME
set runtimepath+=$DOTVIM/bundle/ultisnips
set runtimepath+=$DOTVIM/bundle/neocomplete
set runtimepath+=$DOTVIM/bundle/vimproc

filetype plugin indent on
let g:tex_flavor = 'latex'

let g:UltiSnipsSnippetDirectories = ["texsnippet"]

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer', 'ultisnips']

if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns._ = '[A-Za-zá-úÁ-ÚñÑ_][0-9A-Za-zá-úÁ-ÚñÑ_]*'
let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)

inoremap <silent><expr><CR> pumvisible() ?
    \ (len(keys(UltiSnips#SnippetsInCurrentScope())) > 0 ?
    \ neocomplete#close_popup()."\<C-R>=UltiSnips#ExpandSnippet()\<CR>" :
    \ neocomplete#close_popup()) : "\<CR>"

````
and create two files: i) `$DOTVIM/texsnippets/tex.snippets`:
```
snippet crs "Cleverref section" w
\cref{sec:${1}}$0
endsnippet
```
and ii) `foo.tex` (for instance in your Desktop folder):
```
\label{sec:foo}
```

Now open the foo.tex file and in a new line type `sec:`. You will see that neocomplete correctly completes `sec:foo`. In a new line now type `crs`, select the snippet from the popup list (with <C-n>) and then press `<CR>`. As seen in the GIF the snippet will get correctly expanded but no completion happens. On the other hand once the snippets gets expanded if I press `<SPACE><BACKSPACE>` then neocomplete will complete the candidate. So my question is: why is neocomplete unable of completing once the snippet gets expanded? Thanks in advance for the help.

![blah](https://cloud.githubusercontent.com/assets/2583971/9235571/dc584b38-4115-11e5-96fb-3344813a3608.gif)

**Comment by Shougo** [comment]
I don't know why.  Because, if neosnippet+neocomplete works.
I don't use UltiSnips.

**Comment by Shougo** [comment]
I think `neocomplete#close_popup()` disables neocomplete popup.
You should not use it.

**Comment by petobens** [comment]
> I think neocomplete#close_popup() disables neocomplete popup.
You should not use it.

I finally had some time to test this. I doesn't seem to be a problem with `neocomplete#close_popup() `. Consider a very similar setting to that in my previous comment.  The minimal vimrc is:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath=$DOTVIM,$VIMRUNTIME
set runtimepath+=$DOTVIM/bundle/ultisnips
set runtimepath+=$DOTVIM/bundle/neocomplete
set runtimepath+=$DOTVIM/bundle/vimproc

filetype plugin indent on
let g:tex_flavor = 'latex'

let g:UltiSnipsSnippetDirectories = ["texsnippet"]
let g:UltiSnipsExpandTrigger = '<C-s>'

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer', 'ultisnips']

if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns._ = '[A-Za-zá-úÁ-ÚñÑ_][0-9A-Za-zá-úÁ-ÚñÑ_]*'
let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)

imap <silent><expr><CR> pumvisible() ?
    \ (len(keys(UltiSnips#SnippetsInCurrentScope())) > 0 ?
    \"\<C-y>\<C-s>" : "\<C-y>") : "\<CR>"
```
The `texsnippet/tex.snippet` file consists of:

```
snippet crs "Cleverref section" w
\cref{sec:${1}}$0
endsnippet
```
 and `foo.tex` is once again

```tex
\label{sec:foo}
```

Now do the following:

i) Open `Gvim` and edit the `foo.tex` file
ii) type `crs` and press `<CR>`: there is no buffer completion
iii) type `crs` and press `<C-y>` and then `<C-s>`: there is buffer completion.

So for some reason the mapping is not working (maybe there is a timeout problem?).

![buuu](https://cloud.githubusercontent.com/assets/2583971/10222913/ea00ddac-682c-11e5-90aa-c185f7d19b1e.gif)

**Comment by Shougo** [comment]
> So for some reason the mapping is not working (maybe there is a timeout problem?).

I think it is completion timeout.
I cannot reproduce it in Linux environment.

**Comment by petobens** [comment]
It is indeed a timeout problem since writing the mapping like this:

```vim
imap <silent><expr><CR> pumvisible() ?
    \ (len(keys(UltiSnips#SnippetsInCurrentScope())) > 0 ?
    \"\<C-y>\<C-o>:sleep 3m\<CR>\<C-s>" : "\<C-y>") : "\<CR>"
```

Fixes the problem. I don't know if there is a general solution.

**Comment by petobens** [comment]
710a25385a9ff86927ae78d24cfd5b3e229de877 seems to have fixed the issue. Thanks!

**Comment by Shougo** [comment]
OK.

**Comment by petobens** [comment]
Hi @Shougo,  after commit https://github.com/Shougo/neocomplete.vim/commit/1977757ec425408d5dc1dfaa9c0ccb67a5c437bb and using the minimal vimrc and steps in this [previous comment](https://github.com/Shougo/neocomplete.vim/issues/390#issuecomment-144738698) I get no completion after typing `crs` and then `<CR>`.

**Comment by Shougo** [comment]
Unfortunately, it is feature.
The completion is disabled when you expand a snippet.

**Comment by petobens** [comment]
But it used to worked just fine before https://github.com/Shougo/neocomplete.vim/commit/1977757ec425408d5dc1dfaa9c0ccb67a5c437bb . Can you restore the behavior?

**Comment by Shougo** [comment]
No.  I think it should not be supported.
The feature is changed.  It is intentional.

**Comment by petobens** [comment]
@lervag does this work for you? i.e triggering autocompletion after expanding a snippet (for instance a `\cite{` snippet). If it doesn't, is there a workaround?

**Comment by Shougo** [comment]
It is do to fix https://github.com/Shougo/deoplete.nvim/issues/114

**Comment by lervag** [comment]
@petobens I've never tried this. I don't know if there is a workaround. To me, it seems sensible to not trigger autocompletion after snippet expansion, as that could have some strange side effects in many other cases (although I can't come with a good example right now).

**Comment by petobens** [comment]
@lervag  @Shougo if once a snippet get expanded it matches one of the omni input patterns I think it is sensible to automatically trigger autocompletion. Besides when using neocomplete I don't want to to call completion manually since the whole point of having an autocompletion plugin is, as I understand it, to avoid manual completion.
