### ISSUE TITLE
When terminal reports no colors (or you disable colors in vim) neocomplete causes problems

### ISSUE THREAD

**Issue by mtglsk** [Shougo/neocomplete.vim#391]
For example:
`set t_Co=1`

Makes impossible to use vim. omnicomplete menu doesn't work in such a situation anyway, so maybe neocomplete should abort when no color support is present in vim?

**Comment by Shougo** [comment]
Confirmed.  I will implement the detection.

**Comment by Shougo** [comment]
Fixed.
