### ISSUE TITLE
Vim freezes for few minutes if omni function for c is enabled

### ISSUE THREAD

**Issue by ejaz-ahmed** [Shougo/neocomplete.vim#392]
I am using neocomplete with vim 7.4 on Ubuntu 14.04. I mostly work on C and Groovy language. I have been using neocomplete without omni support. Following line was commented out most of the time.
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'

Few days back, I brought this line back and found that Vim freezes when I access member of any structure pointer i.e instance_handle ->reg1 causes vim to freeze for few minutes. It however come back from the freeze and pops up correct suggestions after freezing.

Here is my minimal vimrc:

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required"
Plugin 'gmarik/Vundle.vim'

"Grails
Plugin 'NathanNeff/grails-vim'

"vim airline which inserts a status line"
Plugin 'bling/vim-airline'

"ctrlp fullpath fuzzy file, buffer, mru, tag finder"
Plugin 'kien/ctrlp.vim'

"NERDTree
Plugin 'scrooloose/nerdtree'

"Solarized color
Plugin 'altercation/vim-colors-solarized'

"Neocomplete plugin
Plugin 'Shougo/neocomplete.vim'
Bundle 'Shougo/neosnippet'
Bundle 'Shougo/neosnippet-snippets'
Plugin 'rking/ag.vim'
Plugin 'majutsushi/tagbar'
Plugin 'taglist.vim'
"Plugin 'taglist.vim' 
Plugin 'jiangmiao/auto-pairs'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

"End Vundle"

:set nu
:set autoindent

"CtrlP Default mapping
let g:ctrlp_map = '<C-P>'
let g:ctrlp_cmd = 'CtrlP'

"CtrlP set the local working directory to current
let g:ctrlp_working_path_mode = 'ra'
"CtrlP ignores
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
"Note: This option must set it in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return neocomplete#close_popup() . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()
" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

**Comment by Shougo** [comment]
Unfortunatelly, it is not neocomplete problem.
You should not use omnicomplete.

You can check the freeze by manual omni completeion(`<C-x><C-o>`).
