### ISSUE TITLE
g:neocomplete#sources#omni#input_patterns にマッチしない入力を行っても omnifunc が呼ばれる

### ISSUE THREAD

**Issue by osyo-manga** [Shougo/neocomplete.vim#393]
Twitter で言っていたやつですが、`g:neocomplete#sources#omni#input_patterns` に設定したパターン以外を入力した場合でも `omnifunc` が呼び出されているようです。

#### vimrc

```vim
if has('vim_starting')
	set nocompatible
endif

set runtimepath+=~/bundle/neobundle.vim
call neobundle#begin(expand($HOME."/neobundle"))

NeoBundle "Shougo/neocomplete.vim"

call neobundle#end()
filetype plugin indent on     " required!

let g:neocomplete#enable_at_startup = 1


call extend(g:neocomplete#sources#omni#input_patterns, {
\		'hoge' : 'aa',
\})

function! Omnifunc(first, base)
	echom "Call Omnifunc"
	if a:first
		return -1
	endif
endfunction

set ft=hoge
setlocal omnifunc=Omnifunc
```

#### 再現手順

上記の vimrc を読みこんで起動したあと、バッファに何か入力する度に `Omnifunc()` が呼び出される。

**Comment by Shougo** [comment]
了解しました。確認します。

**Comment by Shougo** [comment]
再現しました。修正予定です。

**Comment by osyo-manga** [comment]
了解です。お願いします

**Comment by Shougo** [comment]
手元では修正できたので、そんなに時間がかからず修正できるかと思います。
この問題の原因は、omnifuncが二回呼ばれているためです。

**Comment by Shougo** [comment]
修正しましたので確認をお願いたします。

**Comment by osyo-manga** [comment]
了解です。あとで確認してみます。

**Comment by sebastianmarkow** [comment]
This commit introduces a bug, at least for me. Did a brief git bisect and it is indeed this commit breaking neocomplete#close_popup().

**Comment by Shougo** [comment]
@sebastianmarkow It is fallback mappings problem?   Yes, it is fixed in latest version.

**Comment by sebastianmarkow** [comment]
Ran a minimal setup with 77ba2575 , popup won't close

Here are my mappings:

~~~viml
    imap <expr><cr>  pumvisible() ? neocomplete#close_popup() : "\<cr>"
    imap <expr><esc> pumvisible() ? neocomplete#cancel_popup() : "\<esc>"
    imap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
~~~

cancel_popup() won't close as well as close_popup() won't close the popup whenever there's nothing selected.

**Comment by Shougo** [comment]
Reproduced.  Please update neocomplete.

**Comment by sebastianmarkow** [comment]
Thanks @Shougo, a384cfa resolves all issues I encountered.

**Comment by osyo-manga** [comment]
こちらでも修正されていることを確認しました
ありがとうございます。
