### ISSUE TITLE
Autocomplete not opening with TAB, but some char, and leaving it behind

### ISSUE THREAD

**Issue by hgfischer** [Shougo/neocomplete.vim#395]
Hi,

I have a recurring issue with my setup and I don't know how to fix it. Sometimes this kind of `autocomplete artifact` issue haunts me:

[![asciicast](https://asciinema.org/a/19018.png)](https://asciinema.org/a/19018)

Could you help me fix it? I'm not sure if it is a issue with neocomplete.vim or something else. My vim setup can be found at: https://github.com/hgfischer/vim

Thanks in advance!

**Comment by Shougo** [comment]
Please describe it in detail.
I cannot understand your problem.

**Comment by hgfischer** [comment]
Hi @Shougo 

In the video, after 8s, I typed:

```listener.<TAB><TAB><BKSP><BKSP>a<TAB><TAB>....```

The letter `a` should have been replaced by one of the auto-completed choices, which was not what happened.

**Comment by Shougo** [comment]
OK.  Please upload above main.go file.
I will test it.

**Comment by hgfischer** [comment]
After commenting some of the following options and enabling all again, looks like it started working again:
```
set wildmenu
set esckeys
set ttyfast
set encoding=utf-8 nobomb
set binary
set noeol
```

I find it strange. Looks like some sort of cache was causing the issue, because I had to close/open vim many times when I was trying to isolate the buggy config.

**Comment by Shougo** [comment]
OK.
