### ISSUE TITLE
Freezes when writing relative path for the parent directory in C++

### ISSUE THREAD

**Issue by xeno1991** [Shougo/neocomplete.vim#396]
C++で

```cpp
#include "../
```

と書くと、CPU使用率100%のままVimが固まります。`/`と打った直後に固まるようです。

![](http://i.gyazo.com/72d72f203f827267a8883ec69219d28a.png)
![](http://i.gyazo.com/68b4171318ff52344e9c1537ce5825dd.png)

ちなみに、試してみた限り、C言語だと起こりませんでした。

**Comment by xeno1991** [comment]
また、`.`でカレントディレクトリに対してではなく、include pathに対して補完が効くのは不自然な感じがします。

![](http://i.gyazo.com/7fadc6ad2034a052fdba963a1d8207df.png)

**Comment by Shougo** [comment]
> と書くと、CPU使用率100%のままVimが固まります。/と打った直後に固まるようです。

再現しません。おそらく、インクルードパスの上位ディレクトリについて問題があるか、候補が大量なのだと思います。

> また、.でカレントディレクトリに対してではなく、include pathに対して補完が効くのは不自然な感じがします。

これは file_include source の現在の仕様になります。
気になるなら、該当 source を無効にしてください。

**Comment by xeno1991** [comment]
候補が大量にあると思われます。
仕様ということですので、issueを閉じさせていただきます。
ありがとうございました。

**Comment by xeno1991** [comment]
候補が大量なのだと思います。
他のC++を使っている方に試してもらったところ再現が取れています。
"."と".."に関してはカレントディレクトリからの相対パスのみ候補に出したほうがいいと思うのですが、いかがでしょうか。

**Comment by Shougo** [comment]
Fixed.
