### ISSUE TITLE
Neocomplete doesn't auto enable at startup

### ISSUE THREAD

**Issue by pickfire** [Shougo/neocomplete.vim#398]
I have set `let g:necomplete#enable_at_startup = 1` in *~/.vimrc* but it doesn't seems that it works. [My dotfiles](https://github.com/pickfire/dotfiles).

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by pickfire** [comment]
Expected
------------
Neocomplete auto enable at startup after setting the variable.

Enviroment Information
-----------------------------

- OS: Linux alarmpi 3.18.11-4-ARCH #1 SMP PREEMPT Tue Apr 21 21:52:58 MDT 2015 armv7l GNU/Linux
- Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 27 2015 16:42:49)

Vimrc
-------
```
...
Plug 'Shougo/neocomplete.vim' " next generation completion framework           
+ "Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }                       
+ Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }             
...
```

Screenshot
--------------

![vim](https://cloud.githubusercontent.com/assets/4687791/7369873/1b05bb1c-ede8-11e4-8eb3-fcdfa624a89f.png)

**Comment by Shougo** [comment]
Please don't omit the .vimrc.
You must reduce it.

**Comment by pickfire** [comment]
> Please don't omit the .vimrc.
> You must reduce it.

What do you mean?

**Comment by Shougo** [comment]
I cannot use your .vimrc.
And please don't use plugin manager in minimal .vimrc.
You should add runtimepath manually.

**Comment by pickfire** [comment]
Now I understand what you mean, I think you mean to write a minimal *.vimrc* here.
```vim
" My ~/.vimrc
set nocompatible
set runtimepath+=~/.vim/plugged/neocomplete.vim/

set formatoptions=qrn1
let g:neocomplete#enable_at_startup = 1
set tw=10 " just for testing purposes
```

**Comment by Shougo** [comment]
I tested your minimal .vimrc and works.
You should neocomplete installed correctly and `:NeoCompleteEnable` works.

**Comment by pickfire** [comment]
I know `:NeoCompleteEnable` works but `let g:necomplete#enable_at_startup = 1` doesn't works.

**Comment by Shougo** [comment]
Please upload `autocmd neocomplete` result after initialized in minimal .vimrc.
It must be like below.

![autocmd](https://cloud.githubusercontent.com/assets/41495/7408803/bc5f900e-ef5b-11e4-8e66-3a644b1ffcd8.png)

**Comment by Shougo** [comment]
And you should add the message in `plugin/neocomplete.vim` to check it is called.
Like this:

```vim
" Global options definition. "{{{
let g:neocomplete#enable_debug =
      \ get(g:, 'neocomplete#enable_debug', 0)
if get(g:, 'neocomplete#enable_at_startup', 0)
  echomsg 'hello!'
  augroup neocomplete
    " Enable startup.
    autocmd CursorHold,InsertEnter
          \ * call neocomplete#init#enable()
  augroup END
endif"}}}
```

**Comment by pickfire** [comment]
Thanks. It works after I added the following to *.vimrc*:
```vim
autocmd VimEnter * NeoCompleteEnable " Enable NeoComplete at startup           
```

**Comment by Shougo** [comment]
Hmm...
I don't know why the setting is not work..

**Comment by pickfire** [comment]
Maybe add ***Why doesn't NeoComplete enabled at startup after setting ...*** to **FAQ** after solving the mystery.

**Comment by Shougo** [comment]
If other people reported this problem.

**Comment by chauncey-garrett** [comment]
For what it's worth, I dropped the boilerplate configuration from the README file into my `.vimrc` and NeoComplete didn't work on startup until I added `autocmd VimEnter * NeoCompleteEnable` as suggested by @pickfire.

**Comment by Shougo** [comment]
@chauncey-garrett 
It is feature.  Because,

```
					*g:neocomplete#enable_at_startup*
g:neocomplete#enable_at_startup
		neocomplete gets started automatically when Vim starts if
		this value is 1.

		With the default value 0, you cannot use neocomplete
		unless you start it manually.

		Note: This option has to be set in your .vimrc or _vimrc.
		NOT IN the .gvimrc nor _gvimrc!
```

neocomplete does not work automatically in default.

**Comment by pickfire** [comment]
@Shougo as I said, setting `g:neocomplete#enable_at_startup` to 1 doesn't work even if you didn't add `autocmd VimEnter * NeoCompleteEnable` to *.vimrc*.

**Comment by Shougo** [comment]
@pickfire I cannot reproduce the problem.
Something wrong in your environment.
