### ISSUE TITLE
does not show source suffixes and other issues

### ISSUE THREAD

**Issue by maikelmeyers** [Shougo/neocomplete.vim#400]
I see some issues that I did not expect. Maybe you can help me?

Please do the following to reproduce:
```
mkdir test_dir
cd test_dir
touch tags
touch testfile.cpp
echo "QWidget\tqwidget.cpp\t/^QWidget::QWidget(QWidget *parent, Qt::WindowFlags f)$/;\"\tf\tclass:QWidget" >> tags
echo 'QWiTest' >> testfile.cpp
echo 'QWi' >> testfile.cpp
```
neocomplete settings in vimrc:
```
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#disable_auto_complete = 1
let g:neocomplete#sources#syntax#min_keyword_length = 1
let g:neocomplete#min_keyword_length = 1
let g:neocomplete#enable_auto_select = 1
let g:neocomplete#enable_auto_close_preview = 1
let g:neocomplete#enable_fuzzy_completion = 1

if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.cpp = '.*'
imap <expr><C-k> neocomplete#start_manual_complete(['buffer','tag','omni'])
```
Now open vim:
```vim testfile.cpp```
and press ``` jA<C-k>```

neocomplete now shows as expected 3 matches (a buffer, a tag and an omni match)
But the issues then are:
1. the preview window does not autoclose
2. for the tag and the omni match I see no [O] and [T] suffixes. Only the buffer match has a [B] appended (see the picture)
![screenshot from 2015-05-03 22 22 06](https://cloud.githubusercontent.com/assets/11267603/7446767/2ebde202-f1e3-11e4-9516-806b710c9399.png)
3. If you press Backspace 3 times (until the line is empty) the popup menu now shows the contents of the preview window.
![screenshot from 2015-05-03 22 54 46](https://cloud.githubusercontent.com/assets/11267603/7446882/a1afa53a-f1e7-11e4-81a5-30d11fe66f2e.png)
4. Sometimes I have to press ```<C-k> ```twice or more times to get the full list (it does not show the "buffer" match candidate reliable at the first ```C-k``` key press, but all other candidates)

**Comment by Shougo** [comment]
> 1. the preview window does not autoclose

Please explain the detailed behavior.
Autoclose feature is to close preview buffer in cursor moved in insert mode or leave insert mode.

> 2. for the tag and the omni match I see no [O] and [T] suffixes. Only the buffer match has a [B] appended (see the picture)

Feature.  "[O]" is default set of completion menu.  But the omnifunc set menu manually.
neocomplete does not set it.
And tag candidates are hidden.  Because, omni func candidates overwrites them.

> 3. If you press Backspace 3 times (until the line is empty) the popup menu now shows the contents of the preview window.

Please update your Vim.

https://github.com/Shougo/neocomplete.vim/issues/345

> 4. Sometimes I have to press <C-k>twice or more times to get the full list (it does not show the "buffer" match candidate reliable at the first C-k key press, but all other candidates)

Sometimes...?  I don't know the problem.
Please create reproduce ways.

**Comment by maikelmeyers** [comment]
Did you try the example I gave you?

1. There is not much more detail to explain. It does not matter what I do. I can move the cursor or leave insert mode but the preview window stays open.

2.  Sorry, I did not understand clearly who appends the [O] suffix? Can you explain? Is there any reproducable way to get an [O] because I never saw one. I thought it is set by neocomplete. Who else should set it?
I can not confirm your answer for the tags. In the screenshot in my first comment you can see that the tag and the omni candidate is shown together. To convince you that I can not get an [T] suffix I changed
```imap <expr><C-k> neocomplete#start_manual_complete(['buffer','tag','omni'])``` to
```imap <expr><C-k> neocomplete#start_manual_complete(['buffer','tag'])```
You can see the result in the picture below. The completion shows the tag and the buffer candidate, but there is no [T] suffix.
![screenshot from 2015-05-04 13 38 31](https://cloud.githubusercontent.com/assets/11267603/7452830/e3b77e3c-f262-11e4-91cb-1122ab286f7e.png)

3. Does not bother me enough to have all the work with patching, compiling and so on. I only wonder, because this patch does not seem to describe the problem I saw.

4. There is no way to reproduce it. There is no system behind the behavior. Sometimes it shows all candidates by pressing ```<C-k>``` the first time, sometimes I have to press it 2 or 3 times to get also the buffer candidate [B]. I don't know. Forget about it. I think we can not find this issue.

The first 2 points are the most important for me.

**Comment by maikelmeyers** [comment]
I found something out: If you delete the last ```\tclass:QWidget``` in the tags file, then I can see the suffixes. See the picture. It is also the evidence, that the completion menu shows both together (omni and tag). But I still see no [O] suffix.
![screenshot from 2015-05-04 14 04 58](https://cloud.githubusercontent.com/assets/11267603/7453167/b6069d20-f266-11e4-9987-e3e17ada8035.png)
So issue 2 seems to be a problem parsing the tag. But this line is an original line from a ctags generated file.

Issue 4 is very annoying now. Sometimes I have to press 5 times now to see a candidate in the completion menu. I don't know how I can reproduce this in a way that you could see it. Is there a possibility for debug output the manual completion?

**Comment by maikelmeyers** [comment]
I updated vim to 7.4 with all possible 718 patches. Still the same, but 3. is fixed.

**Comment by Shougo** [comment]
2. problem is omni source feature.
omni source append if omnifunc does not set menu attribute in the candidates.
It is for optimization.
Unfortunatelly, omnicppcomplete set menu attribute.  So `[O]` does not be shown.

About 1. problem.
Please read issue template and create minimal .vimrc.
I will test it.

**Comment by Shougo** [comment]
> You can see the result in the picture below. The completion shows the tag and the buffer candidate, but there is no [T] suffix.

It is tag source feature.
tag source append [T] suffix if the candidates have not additional information.
It is for optimization.

**Comment by Shougo** [comment]
> Did you try the example I gave you?

I tested it.  But autoclose feature works(close preview window when insert leave and cursor moved).
So I said "Please read issue create and create minimal .vimrc"
Do you understand?

**Comment by maikelmeyers** [comment]
OK. I understand now the issue with [T] and [O] suffix, but there was no hint in the documentation.

# Problems summary

The preview window does not close automatically, although

`let g:neocomplete#enable_auto_close_preview = 1`

 is set in vimrc. This happens only if auto-completion is turned off with

`let g:neocomplete#disable_auto_complete = 1`

and the completion is started manually with

`neocomplete#start_manual_complete()`

## Expected
The preview window should also auto-close in "start_manual_complete" mode

## Environment Information
 * OS: Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

 * Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  4 2015 16:25:58)
Included patches: 1-718

## Minimal vimrc less than 50 lines

```
set nocompatible
filetype plugin on
set runtimepath+=~/.vim/bundle/neocomplete.vim

set fo+=aw
set tw=10 " just for testing purposes

set completeopt=preview,menuone

let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_close_preview = 1
let g:neocomplete#disable_auto_complete = 1

setlocal omnifunc=ccomplete#Complete
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.cpp = '.*'

imap <expr><C-k> neocomplete#start_manual_complete('omni')
```

## Prerequisites before Vim starting
```
mkdir test_dir
cd test_dir
touch tags
touch testfile.cpp
echo "QWidget\tqwidget.cpp\t/^QWidget::QWidget(QWidget *parent, Qt::WindowFlags f)$/;\"\tf\tclass:QWidget" >> tags
echo 'QWiTest' >> testfile.cpp
echo 'QWi' >> testfile.cpp
vim testfile.cpp
```
## Reproducable ways from Vim starting
1. Press `j`
2. Press `A`
3. Press `<C-k>` to start manual complete behind 'QWi'
4. You should see now 1 candidate from 'omni' source with a preview window
5. Press `<esc>` to leave insert mode
6. The preview window should disappear but it does not.

## Screen shots
![screenshot from 2015-05-06 22 39 15](https://cloud.githubusercontent.com/assets/11267603/7503081/cbae4d4a-f440-11e4-9a91-2ee477cf6da9.png)
![screenshot from 2015-05-06 22 39 19](https://cloud.githubusercontent.com/assets/11267603/7503080/cba98350-f440-11e4-95cb-3afed62a20f3.png)

**Comment by Shougo** [comment]
This feature is added by https://github.com/Shougo/neocomplete.vim/commit/fdea680a5c9ef45796ef80c6a4511a1698196089.
I don't know why...

**Comment by Shougo** [comment]
Fixed.
