### ISSUE TITLE
Not working with Vim 7.4

### ISSUE THREAD

**Issue by mDomingues** [Shougo/neocomplete.vim#401]
Hi,

I've the following setup and still neocomplete outputs that known message 
"neocomplete does not work with this version of Vim.
It requires Vim 7.3.885 or later with Lua support ("+lua")."

Vi 7.4 (installed by brew)
Included patches: 1-488
Lua 5.2.3

What's the problem ? What fails under your check below ?

if !(has('lua') && (v:version > 703 || v:version == 703 && has('patch885')))
  echomsg 'neocomplete does not work with this version of Vim.'
  echomsg 'It requires Vim 7.3.885 or later with Lua support ("+lua").'
  finish
endif

**Comment by kopischke** [comment]
You need to compile Vim with Lua support: `brew install --with-lua` (or `--with-luajit`if you want to use the faster Lua JIT, but you need to install that separately via Homebrew, `brew install luajit`). Having Lua installed on your system does not help Vim use it :).

**Comment by Shougo** [comment]
@mDomingues Please check @kopischke 's advice.
Your Vim is not enabled if_lua.

**Comment by caiocutrim** [comment]
Does not work for me too

**Comment by caiocutrim** [comment]
I use ubuntu 14.04

**Comment by Shougo** [comment]
@caiocutrim Please check your Vim `:version`.
To use neocomplete, you must enable if_lua feature.
I think you should install `vim-full` package.

**Comment by archr** [comment]
This works for me:

```sh
brew uninstall vim
brew install luajit
brew install vim --with-luajit
```

👍 @kopischke

**Comment by ming8924** [comment]
I'm using vim 7.4 on OS X Yosemite. 
The output of `vim --version` has +lua, but `:echo has("lua")` returns 0, and neocomplete can not be used. Any ideas of why this is happening?

**Comment by Shougo** [comment]
I don't know...
It is not neocomplete's problem.
It seems your build problem.

**Comment by ming8924** [comment]
@Shougo  This is what I did to make it work:

Remove both MacVim and vim, reinstall vim using the command `brew install vim --with-lua`.
Previously, I only removed vim. I guess my vim configuration might have messed up with the two installation, making it inconsistent.

**Comment by tushardave26** [comment]
The solution that @archr has provided works fine for me too. Below are the steps I followed in order to get neocomplete working for me:

1. brew uninstall macvim
2. brew uninstall vim
3. brew install macvim --with-cscope --with-lua --HEAD
4. brew install luajit
5. brew install vim --with-luajit ( I have tried brew install vim --with-lua but that did not work out for me)

**Comment by evansdoe** [comment]
Anybody know how to solve this problem with macports?

**Comment by MarlonFan** [comment]
thanks @kopischke

**Comment by makmanalp** [comment]
The luajit solution worked for me - also it was breaking only when using git and I realized I had my git core.editor setting hardcoded to /usr/bin/vim/ - serves me right.

**Comment by luoshenyuan** [comment]
If windows, you should include "lua51.dll" in the same path as "vim.exe !

**Comment by jorgetutor** [comment]
As brew does not remove the OSX vim version (/usr/bin/vim) I needed to hardcode in the ~/.gitconfig file the vim full path (where brew has installed it):

git config --global core.editor /usr/local/bin/vim

And now it is working!

**Comment by ibqn** [comment]
On Ubuntu 14.04 you just need to install `vim-nox` package.

**Comment by shahsaifi** [comment]
how do you fix it on RHEL 6.6?

**Comment by lambdalisue** [comment]
@shahsaifi 

Checkout https://gist.github.com/lambdalisue/01996ca7877f72b860b2#file-install_gvim-sh

**Comment by machycek** [comment]
Found any solution? I have an issue in following. Vim returns 1 on :echo has("lua"), Neovim returns 0.

**Comment by lambdalisue** [comment]
neovim didn't support lua so use deoplete instead.

**Comment by gideon-maina** [comment]
Following some guidelines from this [question](https://superuser.com/questions/630911/vi-command-doesnt-open-newly-installed-vim-7-4-on-os-x#) helped. It appears you have to force the system to uninstall vim in Mac Os then reinstall it forcing the system to take the newly installed version as default.

$ brew uninstall vim
$ brew install vim --override-system-vi
$ hash -r ( for the changes to take effect and you're sorted out)

**Comment by tawanda** [comment]
Thanks for getting me in the right direction, however 
--override-system-vi was deprecated rather use --with-override-system-vi instead

This worked for me, I did not need to uninstall my system vim thanks to the override

```
brew install luajit
brew install vim --with-override-system-vi  --with-cscope  --with-luajit  --HEAD
```

**Comment by joesus** [comment]
🎤🎤 luajit! luajit to quit! 🎤🎤

**Comment by Ericsonsweah** [comment]
ok

**Comment by berndsi** [comment]
A combination of the above did the trick for me:
```
brew uninstall vim
brew install luajit
brew install vim --with-override-system-vi  --with-cscope  --with-luajit  --HEAD
hash -r
```
I needed to run `hash -r` in all terminal sessions for it to take effect everywhere. I could have also logged in again (or probably restarted Terminal).
