### ISSUE TITLE
neosnippet complete is slow with honza snippets and ruby

### ISSUE THREAD

**Issue by aaronjensen** [Shougo/neocomplete.vim#403]
# Problems summary

neosnippet completion spends a lot of time in strwidthpart, causing neocomplete to behave slugishly when using honza snippets and ruby.

Here is a profile log: https://gist.github.com/aaronjensen/afd67f1f536801c3b894

## Expected

neocomplete should be fast, even with snippets

## Environment Information
 * OS: OSX
 * Vim version: 7.4 p712

## Minimal vimrc less than 50 lines

```viml
  " Your vimrc
  set nocompatible

  set runtimepath+=~/path/to/neocomplete.vim/
  set runtimepath+=~/path/to/neosnippets/
  set runtimepath+=~/path/to/vim-snippets/

  set fo+=aw
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_auto_select = 0
  set tw=10 " just for testing purposes

  let g:neosnippet#disable_runtime_snippets = {'_': 1}
  let g:neosnippet#enable_snipmate_compatibility = 1  
  let g:neosnippet#snippets_directory=/path/to/vim-snippets/snippets'
```

## Reproducable ways from Vim starting

 1. Open ruby file
 2. Type `ma`

**Comment by Shougo** [comment]
Please update neocomplete.
This problem is fixed in latest version.

**Comment by aaronjensen** [comment]
I am using 771274c which is only one documentation change behind. Is the fix on another branch?

**Comment by Shougo** [comment]
OK.  The routine is already optimized.

You should disable "converter_abbr" like this:

```vim
	" Change default converter.
	call neocomplete#custom#source('_', 'converters',
	\ ['converter_remove_overlap', 'converter_remove_last_paren',
        \  'converter_delimiter'])
```

**Comment by aaronjensen** [comment]
The problem is this:

https://github.com/Shougo/neosnippet.vim/blob/master/autoload/vital/_neosnippet/Prelude.vim#L112

Is an unoptimized version. It is much slower than this:

https://github.com/Shougo/neocomplete.vim/blob/master/autoload/vital/_neocomplete/Data/String.vim

Also, neocomplete has one:

https://github.com/Shougo/neocomplete.vim/blob/master/autoload/vital/_neocomplete/Prelude.vim#L112

It looks like maybe vital needs to be upgraded on both.

**Comment by Shougo** [comment]
Thanks.
