### ISSUE TITLE
How do I remove keyword "buffer" completion - just smart completions.

### ISSUE THREAD

**Issue by tony** [Shougo/neocomplete.vim#405]
Is there a way I can turn off keyword completions for buffers everywhere?

I've tried:

```
let g:neocomplete#keyword_patterns['default'] = ''
```

```
let g:neocomplete#sources._ = []
```

Everything else, member, tag, syntax, vim, dictionary, file, omni - is ok. I just don't want ``buffer`` completion anywhere.

**Comment by Shougo** [comment]
```vim
	call neocomplete#custom#source('buffer', 'disabled', 1)
```

**Comment by tony** [comment]
@Shougo 

Where does ``-- Keyword Local completion`` come from? How can i disable those keywords?

**Comment by tony** [comment]
![keyword local completion](https://cloud.githubusercontent.com/assets/26336/7559968/c8671dec-f783-11e4-9376-fb3551cdd234.png)

**Comment by Shougo** [comment]
> Where does -- Keyword Local completion come from? How can i disable those keywords?

I think you set `g:neocomplete#fallback_mappings`.

```vim
let g:neocomplete#fallback_mappings = ["\<C-x>\<C-o>", "\<C-x>\<C-n>"]
```

**Comment by tony** [comment]
https://github.com/tony/vim-config/blob/a0bb8cc0692cde679fa14aa4bff3e261516a1a60/settings/neocomplete.vim
``imap <expr> <C-n> neocomplete#start_manual_complete()``
https://github.com/tony/vim-config/blob/a0bb8cc0692cde679fa14aa4bff3e261516a1a60/keymappings.vim#L232

**Comment by tony** [comment]
Correct. I have that.
