### ISSUE TITLE
Weird Issue with Hexidecimal Colors

### ISSUE THREAD

**Issue by amadeus** [Shougo/neocomplete.vim#406]
OS: OSX 10.10.3
Version: MacVim 7.4, patches: 1-728

Basic Vimrc:

```
set nocompatible

set runtimepath+=~/.vim/bundle/neocomplete.vim

let g:neocomplete#enable_at_startup = 1
```

Open/create a file with JUST the following text:

```
#24ae5f
```

Copy `1a8547` into your clipboard.

Put the cursor on the `#` symbol, press `a` to go into insert mode with the cursor after the `#` character but before the `2` character.

Paste the text you just copied above into the document, `cmd + v` in OSX.

Vim completely locks up for a while. `ctrl + c` is usually the best way to get out of it.

**Comment by Shougo** [comment]
I cannot reproduce the problem.

Please try below .vimrc:

```vim
set nocompatible

set runtimepath+=~/work/neocomplete.vim

let g:neocomplete#enable_at_startup = 1

call append(1, '#24ae5f')
```

1. `$ gvim -u test.vimrc`
2. Copy `1a8547` into my clipboard.
3. Put the cursor on the # symbol, press a to go into insert mode with the cursor after the # character but before the 2 character.
4. Paste the text you just copied above into the document by `<C-r>+`.
5. Vim don't lock up...

**Comment by amadeus** [comment]
Interesting, using `<c-r>+` does not trigger the lockup. What happens if you use the OS specific paste command, perhaps `ctrl v`

**Comment by Shougo** [comment]
I used clipboard paste in toolbar.  But it doe not lockup.
I think it is not plugins problem.

**Comment by amadeus** [comment]
Is there any way I could be profiling what vim is doing? I suspect this could be an issue related to a recent patch? Or something MacVim specific.

**Comment by Shougo** [comment]
You can use `:profile` for VimL.
But I don't know how to profile in Vim internal functions.
