### ISSUE TITLE
neocomplete not working with Gtk

### ISSUE THREAD

**Issue by ElGoreLoco** [Shougo/neocomplete.vim#407]
I'm working on a project using Gtk and I've tried this plugin. But when I write `Gtk.` gvim stops working and I can't type, so I have to close it. If I do the same in the terminal, when I type `Gtk.` it crashes and shows this:
![captura de pantalla de 2015-05-14 23 01 04](https://cloud.githubusercontent.com/assets/7355087/7641936/554ba230-fa8d-11e4-8fe0-46f68c2f632e.png)

The code that I wrote in the test.py file is:
```
from gi.repository import Gtk
Gtk.
```
My .vmrc is like in the configuration example in the README, my version of vim is 7.4.52 and when I type `:echo has("lua")` I get 1. I'm on Elementary OS Freya (based on Ubuntu 14.04)
I tried with docopt too and it works fine, but maybe this happens because Gtk is bigger.

I hope there's a solution for this because I'd love to use this plugin but I need it to work on my main project.

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplcache.vim/issues/181

**Comment by Shougo** [comment]
You should disable the  omnifunc.
