### ISSUE TITLE
add option to select last popup menu item by default

### ISSUE THREAD

**Issue by sunaku** [Shougo/neocomplete.vim#408]
Hello,

Please add an option to select the last popup menu item by default.  This can be achieved by sending `<c-p>` initially instead of `<c-n>` after the popup menu is created.  [The reason](https://github.com/ajh17/VimCompletesMe/issues/7#issuecomment-73469819) for this preference is:

> [completion should] search backwards, not forwards from the cursor position. [because] Most of the time, you want to complete words that are already defined in the buffer before the cursor position.

Thanks for your consideration. :santa:

**Comment by Shougo** [comment]
> [completion should] search backwards, not forwards from the cursor position. [because] Most of the time, you want to complete words that are already defined in the buffer before the cursor position.

It is no means in neocomplete.
Because, neocomplete does not use Vim's completion and buffer position sorting

**Comment by sunaku** [comment]
:tada: Excellent, then there's nothing more to be done. :runner: Thanks.
