### ISSUE TITLE
Modes switching loop, file change fired when no change happened

### ISSUE THREAD

**Issue by Fetz** [Shougo/neocomplete.vim#411]
# Problems summary
change is fired when no changes is done in the file
modes switching loop between normal and insert

## Environment Information
 * OS: MAC
 * Vim version:  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 24 2015 13:15:49), MacOS X (unix) version Included patches: 1-488

## vimrc
```
set nocompatible
filetype plugin indent on
syntax enable

set runtimepath+=~/.vim/bundle/neocomplete.vim/

let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
```

## How to reproduce

 1. with a minimal html file `<a href="example1/example2/url.html"></a>`
 2.  in normal mode if you press a when the cursor is in example**2**
 3. vim status line starts to switch between insert mode and normal mode and even if you didn't do any changes, is registered a change

**Comment by Shougo** [comment]
Reproduced the problem.  It is fatal problem.  I will fix it later.
