### ISSUE TITLE
C/C++ completion

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Shougo/neocomplete.vim#413]
Hello,

I wanted to use this plugin with clang_complete. I browsed the old issues and found #71 was exactly what I searched. The problem is issue tells there is something about this in the wiki but I think it has changed and this information is not available anymore.

Can you tell me how to do this ?

EDIT :

I think I tried every possible vimrc and I still cant make it work : I have the following problems :
- When I disable NeoComplete I get the completions I expect when I hit C-n. When I re-enable it they are no longer available
- When I hit C-x-C-o (Omni completion) I have the correction completion but it open a new split called "Scratch"
- When Neocomplete shows it never has [vim] completion

Best regards

**Comment by Shougo** [comment]
I think vim-clang is better than clang_complete.

> When I disable NeoComplete I get the completions I expect when I hit C-n. When I re-enable it they are no longer available

What do you mean?

> When I hit C-x-C-o (Omni completion) I have the correction completion but it open a new split called "Scratch"

It seems clang_complete feature.  You should disable preview window in 'completeopt'.
https://github.com/Rip-Rip/clang_complete/issues/127

> When Neocomplete shows it never has [vim] completion

What do you mean?
Unfortunately, when neocomplete with clang_complete, neocomplete does not show other completions candidates.  It is clang_complete feature.  Clang_complete does not support with other completion candidates.

**Comment by GuillaumeLeclerc** [comment]
When I have NeoComplete enabled if y type : `str` i get the following completions why I type C-n
- strlen  [B]    
- strndup [B]                                                                                                                          
- string  [B]                                                                                                                          
- struct  [S] 

When I disable it i get :

```
 string    
 strndup    
 strings       /usr/include/string.h    
 strcpy        /usr/include/string.h    
 strncpy       /usr/include/string.h    
 strcat        /usr/include/string.h    
 strncat       /usr/include/string.h    
 strcmp        /usr/include/string.h    
 strncmp       /usr/include/string.h    
 strcoll       /usr/include/string.h    
 strxfrm       /usr/include/string.h    
 structure     /usr/include/xlocale.h    
 struct        /usr/include/xlocale.h    
 strcoll_l     /usr/include/string.h    
 strxfrm_l     /usr/include/string.h    
 strdup        /usr/include/string.h    
 strdupa       /usr/include/string.h    
 strlen        /usr/include/string.h    
 strndupa      /usr/include/string.h    
 strnlen       /usr/include/string.h    
 strchr        /usr/include/string.h    
 strrchr       /usr/include/string.h    
 strchrnul     /usr/include/string.h    
 strcspn       /usr/include/string.h    
 strspn        /usr/include/string.h    
 strpbrk       /usr/include/string.h    
 strstr        /usr/include/string.h    
 strtok        /usr/include/string.h    
 strtok_r      /usr/include/string.h    
 strcasestr    /usr/include/string.h    
 strerror      /usr/include/string.h    
 strerror_r    /usr/include/string.h    
 strerror_l    /usr/include/string.h    
 strcasecmp    /usr/include/string.h    
 strncasecmp   /usr/include/string.h    
 strcasecmp_l  /usr/include/string.h    
 strncasecmp_l /usr/include/string.h    
 strsep        /usr/include/string.h    
 strsignal     /usr/include/string.h    
 strverscmp    /usr/include/string.h    
 strfry        /usr/include/string.h    
 strange       /usr/include/math.h    
 strict        /usr/include/math.h
```
In the homepage of the project the is a sceenshot with completions marked as `[vim]` I dont see them on my setup

Is vim-clang integrated with with Neovim ? If yes I will install it instead of clang_complete

Thank you for your reactivity and awesome project !

**Comment by Shougo** [comment]
> In the homepage of the project the is a sceenshot with completions marked as [vim] I dont see them on my setup

It is vim's completion.  It is available if you edit VimL.

> Is vim-clang integrated with with Neovim ? If yes I will install it instead of clang_complete

I think it is.  But I don't test it.

**Comment by GuillaumeLeclerc** [comment]
So there is no way to obtain the full list of suggestions with Neovim Enabled ?

**Comment by Shougo** [comment]
> So there is no way to obtain the full list of suggestions with Neovim Enabled ? 

I don't use C/C++ auto completion.  So I cannot suggest it.
