### ISSUE TITLE
neocomplete breaks "." with cw

### ISSUE THREAD

**Issue by wwalker** [Shougo/neocomplete.vim#414]
# Problems summary
Given a line such as:

-props /var/local/simple.deploy.marathon/conf/simple.deploy.marathon.properties

if I run:   0fsfs5cworc.update<Esc>fs.

One would expect that I changed both instances of simple.deploy.marathon to orc.update

Instead, the second simple.deploy.marathon instance is replaced with ordate:

    -props /var/local/orc.update/conf/ordate.properties \

This never occurs without Bundle 'Shougo/neocomplete.vim.git' loaded.

However!  This only happens if either Bundle 'Lokaltog/vim-powerline' or Bundle 'bling/vim-airline' (or both) is also loaded.

There are other things (which escape me at the moment) where '.' doesn't work right, but <N>cw sometext is the command that is most often affected.

Note that whether or not the failure occurs is dependent upon what the replacing text is!  (things with a, r, and e are the ones I most often see failing)

## Expected

'.' should always cause exactly what the last edit was to happen

## Environment Information
 * OS: Fedora 21
 * Vim version: 
wwalker@hatter:~/golang_workspace/src/indeed/devops/update-orc (master #%)$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 13 2014 08:59:18)
Included patches: 1-207, 209-475
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags  -Wl,-z,relro  -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc       

## Minimal vimrc less than 50 lines

    " Set up Vundle
    set nocompatible
    filetype off
    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()
    let g:go_fmt_command = "goimports"
    Bundle 'gmarik/vundle'

    Bundle 'tpope/vim-fugitive'

    Bundle 'Lokaltog/vim-powerline'
    Bundle 'Shougo/neocomplete.vim.git'
    Bundle 'bling/vim-airline'
    filetype on

    let g:neocomplete#enable_at_startup = 1

## Reproducable ways from Vim starting

 1. start vim on file with line mentioned in Description
 2. 0fsfs5cworc.update<esc>fs.
 3. says ordate where it should say orc.update

**Comment by Shougo** [comment]
#332

It is fixed in Vim 7.4.633.
You should update your Vim.

http://ftp.vim.org/vim/patches/7.4/7.4.633
