### ISSUE TITLE
How to expand neosnippet directly from neocomplete menu ?

### ISSUE THREAD

**Issue by collegeimprovements** [Shougo/neocomplete.vim#415]
I can see my neo-snippet snippets in neocomplete popup. 
I can select them from the menu and then by pressing `<C-k>`, I can expand them.

Is there any way to expand the snippets directly from the popup box? Just to save a `<C-k>` pressing again ?

**Comment by Shougo** [comment]
This feature cannot be supported.
You can complete neosnippet triggers but you must press the expand key.
