### ISSUE TITLE
Block cursor become invisible with neocomplete and jedi-vim

### ISSUE THREAD

**Issue by pythonproof** [Shougo/neocomplete.vim#416]
Here is minimal vimrc
https://ptpb.pw/gxMB/vim

I'll try to explain the problem. Sorry for bad English.

When i typing something in python file after the dot or an import(if there is no suggestion in jedi-vim completion) my cursor turns invisible.

There i want to append to the fucntion argument that is list(jedi doesn't know this), so modules for list class didn't appear. Few step screenshots
![1](https://cloud.githubusercontent.com/assets/6261276/8150167/808c68cc-12e7-11e5-85a4-f41c2955d6cd.jpg)
Here is it dissapear after the first 'a' i type to the end of the word
![2](https://cloud.githubusercontent.com/assets/6261276/8150168/808c7c5e-12e7-11e5-9415-999f2412e73a.jpg)
And when it turns invisible there is this message blink 3+ times per second. In my vimrc i turned this messages off with shortmess, but still some weird behavior
![pattern](https://cloud.githubusercontent.com/assets/6261276/8150172/80a3358e-12e7-11e5-8920-99a8b9b50cb4.jpg)
Then here it is again
![3](https://cloud.githubusercontent.com/assets/6261276/8150166/808adf34-12e7-11e5-8ed0-6ea162039dc7.jpg)

When jedi knows the suggestion completion window just popup and cursor is there
![8](https://cloud.githubusercontent.com/assets/6261276/8150170/808edefe-12e7-11e5-8dbd-a948e94074e3.jpg)

And in imports when you missclick or there is no suggestion the cursor turns invisible too
![4](https://cloud.githubusercontent.com/assets/6261276/8150169/808e14ba-12e7-11e5-9bb8-35fdebf91765.jpg)
![5](https://cloud.githubusercontent.com/assets/6261276/8150171/808f137e-12e7-11e5-8132-791d02bcbe50.jpg)

Tried different terminal - same issue.
let g:jedi#completions_enabled = 1 or 0 - same problem, but seems like need to be one for python3 support

When neocomplete turns off - the cursor doesn't dissapear.

**Comment by Shougo** [comment]
It is not neocomplete problem.
Because, neocomplete just call `feedkeys("\<C-x>\<C-o>")`.

I think it is jedi problem.  But it may be Vim bug.

I think you can reproduce the problem without neocomplete(You can just press `<C-x><C-o>`).
You should report it in jedi-vim issues.

**Comment by pythonproof** [comment]
I can't reproduce it with <C-x><C-o>. It shows command message "Pattern not found" but cursor is visible.

**Comment by Shougo** [comment]
OK. I will test it.  It is terminal only or both GUI?

**Comment by pythonproof** [comment]
Just checked.
In gvim it blinking like 20+ times per sec and glitching with some stripes. 
I think it trying "click" `<C-x><C-o>` 20 times per sec. Maybe something with my neocomplete-neosnippet bindings?

**Comment by pythonproof** [comment]
tried and removed all this neocomple-neosnippet bindings, but problem is still here

here is .vimrc 
https://ptpb.pw/hSIZ

**Comment by Shougo** [comment]
I get the problem.
It seems infinite loop.

I will fix it later.

**Comment by pythonproof** [comment]
Thank you very much.

**Comment by NigoroJr** [comment]
I know it says in the FAQ section that neocomplete.vim doesn't officially support eclim, but I noticed the popup menu isn't shown (automatically) after commit 890d68ad85f30dbe449a9e58a8646b1f6d7a7f6e when it used to. This only happens when using eclim, and I have:

```
let g:neocomplete#force_omni_input_patterns.java = '\%(\h\w*\|)\)\.\w*'
```

set. Entering `C-x C-o` does show the popup menu.

I have no idea how eclim handles omnifunc differently from other plugins, but I thought it's worth mentioning.

**Comment by Shougo** [comment]
OK.  But I don't want to support eclim.
Pull request is wellcome.

**Comment by pythonproof** [comment]
@NigoroJr  i think you can branch and return settings as they were before this commit if u never had the same problem as me. Actually i have almost the same problem. Before this commit in python when you type "from" it automattically popup jedi-vim suggestions for imports, and after even if u type few letters nothing happens(for me it is not a problem because i can use `Ctrl+Cpace` for jedi-vim completions. And this happens only after this "from" imports command). I tried to fix RegExp line for jedi-vim and python without any success(But i really think it can be fixed here). We need to check how other languages behave after this commit.

**Comment by Shougo** [comment]
Fixed.

**Comment by NigoroJr** [comment]
Confirmed. Super awesome, thanks!
