### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mhartington** [Shougo/neocomplete.vim#418]
Currently I'm using https://github.com/Quramy/tsuquyomi to get typescript support in vim. It allows to get omnicompletion of typescript code. While it works with neocomplete, I do have to manually call `<C-x><C-o>` to get neocomplete to show.

Now this was an issue with YouCompleteMe as well, so I had to add sematic triggers. 

```viml
if !exists(“g:ycm_semantic_triggers”)
 let g:ycm_semantic_triggers = {}
 endif
 let g:ycm_semantic_triggers[‘typescript’] = [‘.’]
```

I went a head and added them for neocomplete as well.

```viml
  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
  let g:neocomplete#sources#omni#input_patterns.typescript = '[^. *\t]\.\w*\|\h\w*::'

```

But still the omnicomplete menu has to be invoked manually. 
This is on OSX. Is there any more information I could provide?

**Comment by Shougo** [comment]
You should use `g:neocomplete#force_omni_patterns` instead of `g:neocomplete#sources#omni#input_patterns`.

**Comment by mhartington** [comment]
Hmm, still have to manually invoke omni-complete, even with ` g:neocomplete#force_omni_patterns`

**Comment by Shougo** [comment]
Really?

OK.  I will test it.
Please read https://github.com/Shougo/neocomplete.vim/issues/236.

**Comment by Shougo** [comment]
I tested https://github.com/Quramy/tsuquyomi.  But it does not work.
It just prints "TSServer request was timeout".
I cannot support it.

**Comment by Shougo** [comment]
I tested below config.

It works.

```vim
set nocompatible
set completeopt+=menuone
set rtp+=~/work/neocomplete.vim/
set rtp+=~/work/vimproc.vim/
set rtp+=~/.cache/neobundle/tsuquyomi/

filetype plugin indent on
let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.typescript = '[^. *\t]\.\w*\|\h\w*::'
```

**Comment by zhang-ning** [comment]
cool!
