### ISSUE TITLE
Go completion when a package spans multiple files not working as expected.

### ISSUE THREAD

**Issue by daved** [Shougo/neocomplete.vim#420]
# Summary

When a go package spans multiple files, definitions from one file do not automatically trigger completion in another file unless it is explicitly imported, or is open within a buffer.  Setting fallback_mappings helps, but then the completion is not auto-selected as other neocomplete completion options are.

## Expected

I expected that completion for all definitions with a package would trigger autocompletion options despite being in separate files.

## Environment Information

 * OS: Ubuntu 14.04
 * Vim version: 7.4 (Including patches: 1-52) Huge version with GTK2 GUI.

## vimrc

(Using vundle, L9, and vim-go only)

    let g:acp_enableAtStartup = 0
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#sources#syntax#min_keyword_length = 3
    let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
    let g:neocomplete#enable_auto_delimiter = 1
    let g:neocomplete#max_list = 15
    let g:neocomplete#force_overwrite_completefunc = 1
    let g:neocomplete#sources#dictionary#dictionaries = {
            \ 'default' : '',
            \ 'vimshell' : $HOME.'/.vimshell_hist',
            \ 'scheme' : $HOME.'/.gosh_completions'
            \ }
    inoremap <expr><C-g>     neocomplete#undo_completion()
    inoremap <expr><C-l>     neocomplete#complete_common_string()
    inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
    function! s:my_cr_function()
      return pumvisible() ? neocomplete#close_popup() : "\<CR>"
    endfunction
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
    inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
    inoremap <expr><C-y>  neocomplete#close_popup()
    inoremap <expr><C-e>  neocomplete#cancel_popup()
    let g:neocomplete#enable_auto_select = 1
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
    autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
    if !exists('g:neocomplete#sources#omni#input_patterns')
      let g:neocomplete#sources#omni#input_patterns = {}
    endif
    let g:neocomplete#fallback_mappings = ["\<C-x>\<C-o>", "\<C-x>\<C-n>"]

    " vim-go
    let g:go_fmt_fail_silently = 1
    au FileType go nmap <Leader>s <Plug>(go-implements)
    au FileType go nmap <Leader>i <Plug>(go-info)
    au FileType go nmap <Leader>gd <Plug>(go-doc)
    au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
    au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
    au FileType go nmap <leader>r <Plug>(go-run)
    au FileType go nmap <leader>b <Plug>(go-build)
    au FileType go nmap <leader>t <Plug>(go-test)
    au FileType go nmap <leader>c <Plug>(go-coverage)
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
    let g:go_autodetect_gopath = 1

## Reproduction

 1. Create two go files, each of the same package.
 2. Define some things in file "a".
 3. Open file "b" (without file "a" being in a buffer or being imported).
 4. Start typing one of the definitions from file "a".

**Comment by Shougo** [comment]
It is vim-go limitation.  I cannot fix it.
You can report it in vim-go repository.
But I think it cannot be fixed easily.

> Setting fallback_mappings helps, but then the completion is not auto-selected as other neocomplete completion options are.

It is Vim's feature.
deoplete(neovim) fixes the problem though.
