### ISSUE TITLE
I can't use neocomplete in windows 8 to edit python source file

### ISSUE THREAD

**Issue by blueyi** [Shougo/neocomplete.vim#421]
I use neocomplete in windows 8.1 to edit python source when I input dot “." gvim will terminate immediately。For example, I can't input "neocompete.vim"。when I input the dot ,gvim will force terminate, if I disable necomplete，everything is OK。I have install python 3.4 and python 2.7 in windows。thanks, I like the neocomplete。

"--Here is my neocomplete configure--
"Note: This option must set it in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return neocomplete#close_popup() . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()
" Close popup by <Space>.
"inoremap <expr><Space> pumvisible() ? neocomplete#close_popup() : "\<Space>"

" For cursor moving in insert mode(Not recommended)
"inoremap <expr><Left>  neocomplete#close_popup() . "\<Left>"
"inoremap <expr><Right> neocomplete#close_popup() . "\<Right>"
"inoremap <expr><Up>    neocomplete#close_popup() . "\<Up>"
"inoremap <expr><Down>  neocomplete#close_popup() . "\<Down>"
" Or set this.
"let g:neocomplete#enable_cursor_hold_i = 1
" Or set this.
"let g:neocomplete#enable_insert_char_pre = 1

" AutoComplPop like behavior.
"let g:neocomplete#enable_auto_select = 1

" Shell like behavior(not recommended).
"set completeopt+=longest
"let g:neocomplete#enable_auto_select = 1
"let g:neocomplete#disable_auto_complete = 1
"inoremap <expr><TAB>  pumvisible() ? "\<Down>" : "\<C-x>\<C-u>"

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
"let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
"let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
"let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

" For perlomni.vim setting.
" https://github.com/c9s/perlomni.vim
let g:neocomplete#sources#omni#input_patterns.perl = '\h\w*->\h\w*\|\h\w*::'

**Comment by Shougo** [comment]
It is just Python crash.
Not neocomplete error.
You can test it by `<C-x><C-o>`.

**Comment by blueyi** [comment]
Thank you for your reply，when I uninstall all of my python in my windows。when i input the dot，gvim still be terminated。thank you。

![ss](https://cloud.githubusercontent.com/assets/6254020/8306914/2b431678-19ee-11e5-84a5-50080868ae69.jpg)

**Comment by Shougo** [comment]
You should disable the omnifunc.

```vim
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
```

**Comment by blueyi** [comment]
Thank you very much!when I disable the omnifunc and reinstall python 3.4 , I got another problem: gvim still be terminated, and give a tips in the cmd.
![other](https://cloud.githubusercontent.com/assets/6254020/8307267/48c8cf88-19f0-11e5-890f-67a4ad2305dd.jpg)

**Comment by Shougo** [comment]
I don't know.  Your if_python(3) seems not works.
This is not Q/A site for your environment...

You can reproduce the problem without neocomplete.
For example, `:py print("hello")` and `:py3 print("hello")`.

**Comment by blueyi** [comment]
you are right ,the promble is caused by my Gvim version.Thank you very much!

**Comment by blueyi** [comment]
Sorry,I need your help. I really can't resolve this problem.I have use another gvim for windows8.1 X64 . And I have reinstalled the python 3.4.3 for windows x64.When I edit python source file I got this prompt "[neocomplete] Vim(python):E887:  Sorry, this command is disabled, the Python's site module could not be loaded. "  Best regard to you!thanks!

**Comment by Shougo** [comment]
You should install Python 2.7 x64 binary.
