### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by norbertklar** [Shougo/neocomplete.vim#422]
Hey!

Is there a way to disable autocompletion in strings("Hello World!"), and in comments? Because I didn't find any settings to do it.

**Comment by Shougo** [comment]
Unfortunatelly, nothing.
But you can define original filters for it.

You can get it by `neocomplete#get_current_neocomplete().within_comment`.

**Comment by norbertklar** [comment]
Can you be more specific? I don't know how set it up. Thanks

**Comment by Shougo** [comment]
If you want to disable it in comment, you must write original filter using VimL.
