### ISSUE TITLE
Insertion of '<Plug>(neocomplete_fallback)' strings in ruby file when inserting text.

### ISSUE THREAD

**Issue by lompy** [Shougo/neocomplete.vim#427]
Sammary.
When editing empty ruby file with filetype set to ruby and trying to type a class name with `::` separator random string is inserted.

Environment.
Vim 7.4.738, Ubuntu 14.04

To reproduce.
1) Create ~/ncvimrc with content:

    set nocompatible
    set runtimepath+=~/.vim/bundle/neocomplete.vim
    set filetype=ruby
    let g:neocomplete#enable_at_startup = 1

2) Launch vim from command line editing new ruby file:

    $ vim -u ~/ncvimrc new_ruby_file.rb

3) After vim is launched press following keys:

    iFoo::Bar<Esc>

Expected buffer content:

    Foo::Bar

Actual buffer content:

    Foo::Ba<Plug>(neocomplete_fallback)r

**Comment by nicholasc** [comment]
This was fixed in #425.
Have you updated since?

**Comment by lompy** [comment]
Yep, update fixed the problem. Thanks!
