### ISSUE TITLE
Can I switch match_head or match_fuzzy dynamically ?

### ISSUE THREAD

**Issue by cs86661** [Shougo/neocomplete.vim#430]
I think it maybe useful. Can you implement it ?

**Comment by Shougo** [comment]
I don't think it is useful.

**Comment by Shougo** [comment]
If you want to get the feature, please describe the advantage.

**Comment by cs86661** [comment]
When using match_fuzzy on large project,
It's too fuzzy so I will hard and slow to match my target(If I know the first three letters was).

So if I can dynamically switch to match_head, for example:
ino <silent> <C-G><C-G> <C-O>:NeoCompleteFuzzyToggle<CR>

I type <C-G> twice switch to match_head, and then I can match my target very quickly.
Then type <C-G> twice to switch back match_fuzzy...

Even I can add an notice on 'statusline' to point out the current match mode.

**Comment by Shougo** [comment]
Implemented.

**Comment by cs86661** [comment]
thank you :)

But I have an question, use the follow steps...
======
echo neocomplete#get_default_matchers() --> ['matcher_fuzzy', 'matcher_length']
call neocomplete#set_default_matchers('matcher_head')
echo neocomplete#get_default_matchers() --> ['matcher_head'] ?!
======

I think it should be...
======
call neocomplete#set_default_matchers(['matcher_head', 'matcher_length'])
echo neocomplete#get_default_matchers() --> ['matcher_head', 'matcher_length'] 
======

**Comment by Shougo** [comment]
It is feature.

> I think it should be...

No.  You should use `call neocomplete#set_default_matchers(['matcher_head', 'matcher_length'])
`.

**Comment by cs86661** [comment]
So the "neocomplete.txt" document was typo...please fix it. :)
======
*neocomplete#set_default_matchers()*
neocomplete#set_default_matchers({names})
Chang default matchers in current buffer.
>
call neocomplete#set_default_matchers('matcher_head')
<

**Comment by Shougo** [comment]
It is not typo.
`neocomplete#set_default_matchers()` just change default matchers.
