### ISSUE TITLE
How can I disable autocompletion for filenames and directories?

### ISSUE THREAD

**Issue by fgimian** [Shougo/neocomplete.vim#431]
Hello there, really love your plugin, thanks for all your effort! :smile: 

I've been reading the manual and learned a lot, but I can't seem to figure out how to disable completion for directories and files.

Would you please point me in the right direction?

Thanks
Fotis

**Comment by Shougo** [comment]
`:help g:neocomplete#ignore_source_files`

**Comment by fgimian** [comment]
Sweet, thanks so much @Shougo :smile:
