### ISSUE TITLE
Golang [neocomplete] Vim(let):E121: Undefined variable: words

### ISSUE THREAD

**Issue by andradei** [Shougo/neocomplete.vim#432]
# Neocomplete won't autocomplete when `.` is typed after a package.

I installed Vim on Linux Mint 17.2 with the following script

```
# Remove previous installations
sudo apt-get remove vim vim-runtime vim-tiny vim-common

# Install dependencies
sudo apt-get install libncurses5-dev python-dev libperl-dev ruby-dev liblua5.2-dev

# Fix liblua paths
sudo ln -s /usr/include/lua5.2 /usr/include/lua
sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.2.so /usr/local/lib/liblua.so

# Clone vim sources
sudo apt-get install mercurial
hg clone https://code.google.com/p/vim/

cd vim
./configure --prefix=/usr     \
    --enable-luainterp=yes    \
    --enable-perlinterp=yes   \
    --enable-pythoninterp=yes \
    --enable-rubyinterp=yes   \
    --enable-cscope           \
    --disable-netbeans        \
    --enable-multibyte        \
    --enable-largefile        \
    --enable-gui=gnome2    \
    --with-features=huge      \
    --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu

make VIMRUNTIMEDIR=/usr/share/vim/vim74

sudo apt-get install checkinstall
sudo checkinstall
```

And auto completion for Golang gives me the error: `[neocomplete] Vim(let):E121: Undefined variable: words`

If I install vim-nox autocompletion starts working, but the package manager won't work until I uninstall it.

## Expected
`fmt.` should bring up all public functions, structs, etc. from the _fmt_ package

## Environment Information
 * OS: Linux Mint 17.2
 * Vim version: Described above

## Minimal vimrc less than 50 lines

   " Your vimrc
   set nocompatible

   set runtimepath+=~/path/to/neocomplete.vim/

  set fo+=aw
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_auto_select = 0
  set tw=10 " just for testing purposes

## Reproducable ways from Vim starting

 1. Install vim-nox
 2. Type in code:
```
package main
import "fmt"
func main() {
    fmt.
}
```
 3. Error appears after you type `fmt.` (notice the dot)

## Screen shot (if possible)
![neocomplete](https://cloud.githubusercontent.com/assets/2653546/8632583/f3b84c40-275e-11e5-873e-a7e672d94f7e.jpg)

**Comment by andradei** [comment]
I also tried uninstalling Vim and installing `vim-nox` and got the same error with golang autocompletion.

**Comment by Shougo** [comment]
Please read the issue template
https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by andradei** [comment]
There it is.

**Comment by Shougo** [comment]
Your minimal .vimrc is wrong.
And it works for me.

```vim
" Your vimrc
set nocompatible

set runtimepath+=~/work/neocomplete.vim/
set runtimepath+=~/.cache/neobundle/gocode/vim/

set fo+=aw
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
set tw=10 " just for testing purposes
setlocal omnifunc=gocode#Complete

filetype indent plugin on
```

**Comment by Shougo** [comment]
You should install latest gocode.

**Comment by andradei** [comment]
Thanks for the suggestions. I updated the vimrc snippet.

I tried installing go goce via Vundle, vim-go's functions `:GoInstallBinaries` and `:GoUpdateBinaries` and by running `go get`, at the bottom of the printscreen above is gone, but the autocompletion for Golang is still not happening.

Any other suggestions?

**Comment by Shougo** [comment]
Please check the omnifunc is works.

**Comment by daef** [comment]
i get the same errormessage, did you find a solution?

**Comment by andradei** [comment]
I have not.

**Comment by Shougo** [comment]
@daef I don't know the problem.  But the omnifunc returns wrong type.  It is the omnifunc's bug.
You should update it to the latest version and report to the maintainer.
