### ISSUE TITLE
Node.js support [Question]

### ISSUE THREAD

**Issue by iasj** [Shougo/neocomplete.vim#433]
I'd like to know how to enable proper node.js documentation/completion in neocomplete. 

I'll show what I'm talking in about. Here is some python script:

![neocomplete](https://cloud.githubusercontent.com/assets/7888397/8654061/63d5abca-295e-11e5-842f-a0086d185467.png)

it seems to work great. But, when I try similar thing in node.js, here is what I got:

![neocomplete js](https://cloud.githubusercontent.com/assets/7888397/8654092/ad8edef8-295e-11e5-9b56-ffc63be19620.png)

i've been searching for those suggestions that appear, in this [link location](https://nodejs.org/api/net.html), but I think that they aren't the right ones. And yet, neocomplete don't show any documentation suggestions as well as with python does.

And in general, I'd like to know how to enable this wonderful feature in any program (script) language as well. Is that possible?

**Comment by Shougo** [comment]
You can use echodoc to print the documentation.
https://github.com/Shougo/echodoc.vim
You should update your Vim to latest version.
