### ISSUE TITLE
Vim freezes when deleting characters until one left before the cursor.

### ISSUE THREAD

**Issue by meoow** [Shougo/neocomplete.vim#436]
In insert mode, I was trying to delete all characters before the cursor using `backspace` while there are still some characters after the cursor, when the cursor reached to one left character to the beginning of the current line, vim will freeze forever. It happens every time in every file.
Here is a example when neocomplete caused vim completely froze.
![pic1](http://i.imgbox.com/oamu9hQw.png)

Any solution to avoid this?

**Comment by meoow** [comment]
It happens when I opened multiple files in different tabs, and some of them has thousands of lines.

**Comment by j5shi** [comment]
`    inoremap <expr><bs> pumvisible() ? "<ESC>:call neocomplete#close_popup()<CR>a<bs>" : "<bs>"
`

**Comment by Shougo** [comment]
@meoow You must upgrade your Vim.
https://github.com/Shougo/neocomplete.vim/issues/339
