### ISSUE TITLE
Tag completion per filetype

### ISSUE THREAD

**Issue by cornerman** [Shougo/neocomplete.vim#437]
Hi, I have one tags file per project, which can include tags from multiple languages (the language field is present). When I set ```g:neocomplete#sources``` to include the ```tag``` source, it completes all tags regardless of the language. Any idea how I could filter the tag completions to only use tags for the filetype of the current buffer?

**Comment by Shougo** [comment]
I think it cannot.
Because, tag file has not filetype field.
neocomplete does not get filetype information.

**Comment by cornerman** [comment]
ctags can actually provide language information in the tag file via the language field: ```--fields=+l```.
This will generate something like this: 
```
History	./window_back_forth.rb	/^class History$/;"	c	language:Ruby
services	./UserService.scala	/^package services$/;"	p	language:scala
```

Wouldn't it be possible to map those to the filetype in vim?

**Comment by Shougo** [comment]
Hmmm...
But I don't use tag file completion and I don't want to add new features in neocomplete.

**Comment by cornerman** [comment]
Any idea how I could manually filter the tag source results?

**Comment by Shougo** [comment]
You can implement the filter by `s:load_from_tags()` in async_cache.vim.

**Comment by cornerman** [comment]
Thanks, I will have a look (or maybe just have different tag files per filetype)
