### ISSUE TITLE
How to disable popup menu while moving cursor?

### ISSUE THREAD

**Issue by dongli** [Shougo/neocomplete.vim#438]
First of all, thanks for making such great fuzzy autocomplete plugin for VIM! This definitely boosts the productivity, but I have a little problem, that is while I move around the cursor, the popup menu will trap the cursor, then I need to press ESC to disable the unnecessary completion suggestion. Is there any possibility to disable the popup while moving cursor?

**Comment by zchee** [comment]
@dongli 
FYI,
https://github.com/Shougo/neocomplete.vim/blame/master/README.md#L169-L174
Not work?

**Comment by Shougo** [comment]
This feature is already supported.
You should update your Vim to 7.4.143 or above.

**Comment by dongli** [comment]
Thanks for pointing that out! It would be great if this is the default behavior~
