### ISSUE TITLE
Is there a way to use keyword_patterns for indiviual sources

### ISSUE THREAD

**Issue by effi** [Shougo/neocomplete.vim#440]
Hi, I tried to figure it out with you documentation, but I couldn't find the correct solution.
I want to provide sources for Latex-Completion that are triggered by individual keywords.. Like one source file for labels, one for citations etc.. Is the only way to give them individual keyword_patterns to write a get_complete_position function? Or am I missing some key ingredient here?
(There are also a lot of Omnifunc completions, but i prefer the neocomplete)

Thank you :)

**Comment by Shougo** [comment]
You can use "keyword" kind.
Please see `:help neocomplete-source-attribute-kind`.

**Comment by effi** [comment]
Hi Shougo, thanks for your answer!
Im still a little unclear in this regard:
 if I understand this passage correctly:

> kind			String				(Optional)
> 			The kind of the source.  It decides the behaviour of
> 			the complete position.  The following values are
> 			available:
> 
> 			"manual": The source decides the complete position
> 				manually with the "get_complete_position"
> 				attribute.  See also:
> 				|neocomplete-source-attribute-get_complete_position|
> 
> 			"keyword": The source decides the complete position
> 				with |g:neocomplete#keyword_patterns|.  This
> 				pattern is also used to filter the candidates.
> 
> 			Note that "plugin", "complfunc" and "ftplugin" are old
> 			values that are no longer accepted.

It states that I either use manual and define the get_complete_position function, or i select keywords, which are on a filetype basis and not on a source basis? Or do I mix this up?
What I want are different sources for my tex file that use different keywords... :)

**Comment by Shougo** [comment]
>It states that I either use manual and define the get_complete_position function, or i select keywords, which are on a filetype basis and not on a source basis? Or do I mix this up?
> What I want are different sources for my tex file that use different keywords... :)

You should create tex filetype source.  It should use "keyword" kind.
