### ISSUE TITLE
Is it possible to get same line auto completion? 

### ISSUE THREAD

**Issue by kasldfh** [Shougo/neocomplete.vim#441]
For example, if I have this in my buffer:
cakeMaker
cakeEater = 
and I want to say cakeEater = cakeEater  + 1
If i start typing after the equals sign, cakeEater will not be the first suggestion -- cakeMaker will be. I would like to have the most recently used match be the first suggestion, even if it's on the same line.  

I read somewhere that not taking suggestions from the same line is a feature of neocomplete. Is there a way to disable this "feature"?

**Comment by Shougo** [comment]
It is possible.
I cannot reproduce your problem.

Please read the issue template.
https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by kasldfh** [comment]
Ah, when I looked closer I had an issue with another plugin I am using. Sorry about that.
