### ISSUE TITLE
HTML no longer auto indents

### ISSUE THREAD

**Issue by m0v0nage** [Shougo/neocomplete.vim#442]
OS: Debian 7
Vim version: 7.4

Possibly related to #311:
Other languages and filetypes seem to auto indent correctly, but in HTML when I type a closing tag with NeoComplete disabled, it would align it with it's opening tag. When NeoComplete is enabled, it keeps the closing tag indented as if it were a child opening tag.

Example:
```html
<body>
    <div>
        </div>
    </body>
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please read the issue template.

https://github.com/Shougo/neocomplete.vim/issues/236

> OS: Debian 7
> Vim version: 7.4

Please upload Vim's patch version.

**Comment by m0v0nage** [comment]
Here is my vimrc
```vimscript
set autoindent

filetype plugin indent on

let g:neocomplete#enable_at_startup = 1

set tabstop=4
set shiftwidth=4
```
I just took a screen shot of the version info incase there was anything else you needed:
![vim version](https://cloud.githubusercontent.com/assets/1407391/8860038/562939fa-313e-11e5-95f5-c804708c91e8.PNG)

When I type the beginning of a tag and NeoComplete gives me suggestions, it will indent correctly if I select that tag for the auto complete list. If I finish typing it manually and leave insert mode, the indentation stay incorrect as shown in the original issue post.

If you are still unable to reproduce this, perhaps I will upload a quick gif or video to help describe what I mean.

**Comment by Shougo** [comment]
I tested it, and it works for me.
Please describe the detailed information.

**Comment by m0v0nage** [comment]
I am going to try to get some buddies to test this for me as well. In the meantime, here is a gif demonstrating the problem:

![neocmpl](https://cloud.githubusercontent.com/assets/1407391/8920689/a002b846-3489-11e5-8d5b-b35df9da0ced.gif)

**Comment by DeaR** [comment]
I think is not NeoComplete problem.
```sh
$ vim -u NONE
```
```vim
:filetype plugin indent on
:setf html
```

#### all input
```
a<html><CR></html><Esc>
```
```html
<html>
</html>
```
OK

#### omni completion (use escape key)
```
a<html><CR></<C-X><C-O><Esc>
```
```html
<html>
        </html>
```
NG

#### omni completion (use indentkeys before escape key)
```vim
:set indentkeys?
indentkeys=o,O,<Return>,<>>,{,},!^F
```
```
a<html><CR></<C-X><C-O><C-F><Esc>
```
```html
<html>
</html>
```
OK

**Comment by m0v0nage** [comment]
@DeaR I see what you mean, that does seem to be the issue. But shouldn't NeoComplete not interfere with the indent keys? If I just type out the closing tag myself, the indentation triggered by me pressing the '>' character should still happen.

**Comment by DeaR** [comment]
okey, I understood.
please update vim 7.4.655 or higher.
https://groups.google.com/d/topic/vim_dev/qvTXcdJ7Jbw/discussion
https://groups.google.com/d/topic/vim_dev/AVOjVAa0Npo/discussion

**Comment by m0v0nage** [comment]
@DeaR Thanks so much! I am on patch 658 now and everything works great!

**Comment by Shougo** [comment]
Yes, it is not neocomplete problem.
