### ISSUE TITLE
Some chars are swallowed

### ISSUE THREAD

**Issue by RageYL** [Shougo/neocomplete.vim#446]
# Problems summary
Sometimes when pressing a key, the next char is 'swallowed'.
This is due to 'let g:neocomplete#enable_insert_char_pre = 1'

## Environment Information
vim 7.4.778

## Minimal vimrc less than 50 lines

set nocompatible

filetype off

set runtimepath+=~/.vim/bundle/Vundle.vim
set runtimepath+=~/.vim/plugin

call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/neocomplete.vim'

call vundle#end()

filetype plugin on
filetype indent on

let g:acp_enableAtStartup                = 0
let g:neocomplete#enable_at_startup      = 1
let g:neocomplete#enable_insert_char_pre = 1

## Reproducable ways from Vim starting

= file: test.py
```
#!/usr/bin/env python2
# coding: utf-8

response = 42
print response
```

= issue:
move your cursor between print and response: (| is the cursor)

	print |response

type repr

	print reprr|esponse

expected:

	print repr|response

**Comment by Shougo** [comment]
I don't reproduce the problem.
And I don't recommend to use the feature.
It is deprecated.  You should disable it.
