### ISSUE TITLE
trouble with vim fo+=a

### ISSUE THREAD

**Issue by coachshea** [Shougo/neocomplete.vim#447]
I am getting a very weird behavior when I am using neocomplete with vim and
formatoptions+=a. If I am typing near the end of a line and type a character
that triggers the completion popup window, a new line is automatically created
and the first choice is automatically inserted along with whatever I have been
typing at the moment.

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by Shougo** [comment]
Related problem
https://github.com/Shougo/neocomplete.vim/issues/235

**Comment by Shougo** [comment]
I think you don't set textwidth option...

**Comment by coachshea** [comment]
I have tried set tw=80 and tw-78 the only difference is when this happens.

**Comment by Shougo** [comment]
Please create minimal .vimrc.

**Comment by coachshea** [comment]
I believe the below settings are all that are relevant to this issue.


" neocomplete

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif

let g:neocomplete#sources#omni#input_patterns.ls = '\.'
let g:neocomplete#sources#omni#input_patterns.tex = '.*cite.*{\|.*ref.*{'
let g:neocomplete#sources#omni#input_patterns.r = '\$'

if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif

let g:neocomplete#force_omni_input_patterns.tex = '.*cite.*{\|.*ref.*{'
let g:neocomplete#force_omni_input_patterns.r = '\$'

if !exists('g:neocomplete#same_filetypes')
  let g:neocomplete#same_filetypes = {}
endif

let g:neocomplete#same_filetypes.r = 'R,Rnw,Rmd'

" mail
set spell
set tw=78
set noautoindent
set formatoptions+=aw

**Comment by Shougo** [comment]
Can you try the minimal .vimrc?
And please provide the reproduce ways to me.

**Comment by Shougo** [comment]
You can see the sample in https://github.com/Shougo/neocomplete.vim/issues/235.

**Comment by coachshea** [comment]
Here was the minimal vimrc that I used:

" settings
set nocompatible

filetype plugin off
filetype plugin indent on
execute pathogen#infect()
Helptags
syntax on

" neocomplete

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif

let g:neocomplete#sources#omni#input_patterns.ls = '\.'
let g:neocomplete#sources#omni#input_patterns.tex = '.*cite.*{\|.*ref.*{'
let g:neocomplete#sources#omni#input_patterns.r = '\$'

if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif

let g:neocomplete#force_omni_input_patterns.tex = '.*cite.*{\|.*ref.*{'
let g:neocomplete#force_omni_input_patterns.r = '\$'

if !exists('g:neocomplete#same_filetypes')
  let g:neocomplete#same_filetypes = {}
endif

let g:neocomplete#same_filetypes.r = 'R,Rnw,Rmd'

" mail
set spell
set tw=78
set noautoindent
set formatoptions+=aw
" vim: set ft=vim:

As far as reproducing, just get to the end of a line and type any word that 
was previously been used in the buffer. 

Thanks for all your help.

**Comment by coachshea** [comment]
I have looked at #235 and, I'm sorry if I'm missing something, but I don't see 
how to fix this.

Thank again for your time, I'm sorry if I'm missing something obvious.

**Comment by Shougo** [comment]
I think below code is not needed for the problem.

```vim
if !exists('g:neocomplete#sources#omni#input_patterns') let g:neocomplete#sources#omni#input_patterns = {} endif let g:neocomplete#sources#omni#input_patterns.ls = '\.' let g:neocomplete#sources#omni#input_patterns.tex = '.*cite.*{\|.*ref.*{' let g:neocomplete#sources#omni#input_patterns.r = '\$' if !exists('g:neocomplete#force_omni_input_patterns') let g:neocomplete#force_omni_input_patterns = {} endif let g:neocomplete#force_omni_input_patterns.tex = '.*cite.*{\|.*ref.*{' let g:neocomplete#force_omni_input_patterns.r = '\$' if !exists('g:neocomplete#same_filetypes') let g:neocomplete#same_filetypes = {} endif let g:neocomplete#same_filetypes.r = 'R,Rnw,Rmd'
```
I will try it later.

**Comment by Shougo** [comment]
I cannot reproduce the problem above minimal .vimrc.
