### ISSUE TITLE
Vim hangs when entering insert mode, buffer shown as modifed

### ISSUE THREAD

**Issue by phphong** [Shougo/neocomplete.vim#448]
## Problems summary
* In terminal MacVim, insert mode and normal mode exchange rapidly
* In GUI MacVim, vim hangs until you press `Esc`
* Buffer is shown as modified but there is no change

## Environment information
* OS X Yosemite 10.10.3
* Vim: 
  * VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  1 2015 18:12:59)
  * MacOS X (unix) version
  * Included patches: 1-769
  * Compiled by Homebrew
  * Huge version with MacVim GUI.

## Minimal vimrc
    syntax enable
    set runtimepath+=~/.vim/plugged/neocomplete.vim/
    let g:neocomplete#enable_at_startup = 1
    " inoremap <expr><C-e>  pumvisible()? neocomplete#close_popup():"\<C-c>"
    " inoremap <expr><C-c>  pumvisible()? neocomplete#cancel_popup():"\<C-e>"

## Reproducable way
1. Open the above vimrc by MacVim terminal or GUI
2. Put the cursor at the last line, at <pre>nocomplet<b>[e]</b>#cancel</pre>
3. Press `a` or `i`

**Comment by Shougo** [comment]
Thanks.  Fixed.
