### ISSUE TITLE
Plugin doesn't work after installation

### ISSUE THREAD

**Issue by zavfel** [Shougo/neocomplete.vim#449]
I installed vim using this 

    brew install vim --with-lua

then add 

    let g:neocomplete#enable_at_startup = 1

to my .vimrc but when I use vim it still doesn't work

**Comment by shubhamgoyal** [comment]
I also face the same problem. Maybe I am too new to this and so I am doing something wrong. Would love if someone could point in the right direction.

**Comment by crazymaster** [comment]
Can you show us more information?
ref: #236

**Comment by crazymaster** [comment]
Does if_lua enable?
Please check by this command.
`:echo  has('lua')`

**Comment by zavfel** [comment]
# Problems summary

## Expected

## Environment Information
 * OS:X Yosemite 10.10.4
 * Vim version:7.4.712

## Minimal vimrc less than 50 lines

  1 set number
  2 let &titlestring = @%
  3 set title
  4 execute pathogen#infect()
  5 syntax on
  6 filetype plugin indent on
  7 let g:neocomplete#enable_at_startup = 1

the command doesn't show any output, how do i enable if_lua?

**Comment by crazymaster** [comment]
>`:echo has('lua')`
>the command doesn't show any output, how do i enable if_lua?

Hmm, you can check `+lua` by the `:version` command.

Is 'filetype' set in the buffer?
Please check `:set ft?` output.

**Comment by zavfel** [comment]
There's lua enabled in the version. The filetype is set as javascript, does it only work on certain filetype?

**Comment by crazymaster** [comment]
>`:echo has('lua')`
>the command doesn't show any output, how do i enable if_lua?

How about `:lua print("Hello, Vim!")`?
If not output `Hello, Vim!`, have a problem with if_lua.

**Comment by zavfel** [comment]
The output is correct. I manage to resolve the problem already. I think because i got pathogen installed, so it interferes with the file. Once I put this folder inside the bundle folder for pathogen to read it works. Thanks for the help!
