### ISSUE TITLE
Fuzzy search without first letter match

### ISSUE THREAD

**Issue by AndreasPetersen** [Shougo/neocomplete.vim#451]
The help text for fuzzy search says that the first letter must match. Is it possible to implement an option so that fuzzy search works even when the first letter does not match? This is the case in sublime text for example.

Sublime text:
![st](http://puu.sh/jqiRo/17a1ae7fea.png)

NeoComplete:
![ec](http://puu.sh/jqja9/fe5b16af64.png)

**Comment by Shougo** [comment]
No.  I don't want to implement it.
You can create original matcher or use YouCompleteMe instead.
