### ISSUE TITLE
How to enable it solely for a given file type?

### ISSUE THREAD

**Issue by oblitum** [Shougo/neocomplete.vim#452]
Hi, I'd like to know how I could enable neocomplete solely for one or two filetypes?

For example, I'm using both YCM and neocomplete, but I don't enable both at the same time, so with YCM I can do:

```vim
if !exists('g:ycm_filetype_blacklist')
  let g:ycm_filetype_blacklist = {}
endif
let g:ycm_filetype_blacklist.python = 1
```

and it won't be enabled for python,  now I want to have neocomplete enabled for python solely.

**Comment by Shougo** [comment]
You should use `:NeoCompleteLock` feature.

```vim
autocmd FileType * call s:check()
function s:check()
if &filetype ==# 'python'
  NeoCompleteUnlock
else
  NeoCompleteLock
endif
endfunction
endfunction

**Comment by oblitum** [comment]
Thanks.
