### ISSUE TITLE
function hint neocomplete eclim

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/neocomplete.vim#455]
@shugo how can i have function paramettre hint with neocomplete i use echodoc and he work amazing whith Go plugin but not with eclim for java how can i have paramettre hint without the preview window because it make me hungry if there is no solution do you think that it will be with the new neovim and if neocomplete will work with it because neo don't support lua

**Comment by Shougo** [comment]
OK.  I will add support for it.

**Comment by Shougo** [comment]
Please test it.
I cannot test it.   Because, I have not eclim environment.

**Comment by 7belrhalmia** [comment]
yes @Shougo  it work i test it for eclim  and it work amazing

**Comment by Shougo** [comment]
>  because it make me hungry if there is no solution do you think that it will be with the new neovim and if neocomplete will work with it because neo don't support lua

You can use deoplete instead of neocomplete.
It also supports echodoc feature.

https://github.com/Shougo/deoplete.nvim

**Comment by 7belrhalmia** [comment]
@Shougo  when neocomplete make a sugestion and you choose it insert object.function(                                    it's not nice   it will be cool if   it insert all the prototype object.function(param1 ,param2);  and make the param1 in visual mode and when you tape tabe it move to the next it will be much fuster

**Comment by 7belrhalmia** [comment]
@Shougo  like that neocomplete insert object.function(int a ,String Z)    and all int a is in visual mode when you type tab it move to String Z  this will be amazing
