### ISSUE TITLE
Can't make jedi come before ultisnips

### ISSUE THREAD

**Issue by elvis-sik** [Shougo/neocomplete.vim#456]
I have set 
 > autocmd FileType python setlocal omnifunc=jedi#completions
 > let g:jedi#completions_enabled = 0
 > let g:jedi#auto_vim_configuration = 0
 > let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
 > call neocomplete#custom#source('ultisnips', 'rank', 1)

If I create a file `foo.hs` (Haskell), and create a function called `haddocking` the snippet `haddock` will come after it (which is the desired behavior).
If I create a file `foo.py` (Python), and create a function named `classing`, it comes *after* the snippet `class`. This is undesirable because when I get to the snippet, if I press <Tab>, it is expanded.

I would be satisfied with either being able to make snippets come after other suggestions or to expand them with other key, and using Tab only to cycle. Note that I am currently using supertab, but don't particularly care about it.

Thanks!

**Comment by Shougo** [comment]
Please upload the screenshot.
I will check it.

**Comment by Shougo** [comment]
> I would be satisfied with either being able to make snippets come after other suggestions or to expand then with other key, and using Tab only to cycle. Note that I am currently using supertab, but don't particularly care about it.

Unfortunatelly, you use g:neocomplete#force_omni_patterns feature for it.
You cannot mix UltiSnips and jedi candidates.

**Comment by elvis-sik** [comment]
Okay, thanks, I guess I'll try neosnippet

**Comment by NoAnyLove** [comment]
Just want to confirm that it's impossible to combine the jedi candidates with UltiSnips?

So if we set `let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'`, we can't see the candidates of UltiSnips. And if we set `let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'`, we can't see the candidates of jedi except inputting `from`,`import` and `.`, correct?

Is there any workarounds to combine the candidates of UltiSnips and jedi?

**Comment by Shougo** [comment]
@NoAnyLove You can use `g:neocomplete#sources#omni#input_patterns` instead of `g:neocomplete#force_omni_patterns`.
It can combine them.  But I don't support it.
