### ISSUE TITLE
lack lua/dyn support

### ISSUE THREAD

**Issue by kaji331** [Shougo/neocomplete.vim#457]
I have a Vim with +lua/dyn. It means Vim supports lua and loads it dynamically. But neocomplete told me my Vim didn't support lua. I couldn't use neocomplete. Thanks~

**Comment by Shougo** [comment]
Please check your "lua/dyn" works.
You can test `:lua print "hello"` command.

**Comment by kaji331** [comment]
Thanks very much

发自我的 Windows Phone
________________________________
发件人: Shougo<mailto:notifications@github.com>
发送时间: ‎2015/‎8/‎15 6:35
收件人: Shougo/neocomplete.vim<mailto:neocomplete.vim@noreply.github.com>
抄送: kaji331<mailto:kaji331@hotmail.com>
主题: Re: [neocomplete.vim] lack lua/dyn support (#457)

Please check your "lua/dyn" works.
You can test `:lua print "hello"` command.

---
