### ISSUE TITLE
. is broken by neocomplete

### ISSUE THREAD

**Issue by frioux** [Shougo/neocomplete.vim#458]
# Problems summary

## Expected

I expect to be able to do something (for example: `cwfoo bar baz<esc>`) and be able to use `.` to repeat it.

## Environment Information
 * OS: Ubuntu 15.04
 * Vim version: 7.4.488

## Minimal vimrc less than 50 lines

   " Your vimrc
   set nocompatible

   set runtimepath+=~/path/to/neocomplete.vim/

  set fo+=aw
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_auto_select = 0
  

## Reproducable ways from Vim starting

 1. Edit the config above
 2. Add some comments at the bottom, like `" this is a log test footbal percival bong`
 3. Type `cwfoo bar baz<esc>` to replace one of the `let`'s with `foo bar baz`
 4. Press `.` on the next let; you should see `foo bar baz`, instead you'll see something like `foz`

**Comment by Shougo** [comment]
#332

It is fixed in Vim 7.4.633

http://ftp.vim.org/vim/patches/7.4/7.4.633
