### ISSUE TITLE
'indentexpr' does not triggered when "else" is typed with "e" indentkeys

### ISSUE THREAD

**Issue by popkirby** [Shougo/neocomplete.vim#459]
# Problems summary
When 2nd "e" of "else" is typed with "e" indentkeys, Vim should trigger 'indentexpr'.
However, when "else" is completed by neocomplete.vim, 'indentexpr' does not be triggered.

## Expected
In the example, "foofoo" is indented correctly like:
```
foo
  foo
    foofoo
```
However, "else" is not indented, showing:
```
foo
  foo
else
```

## Environment Information
 * OS: Mac OS X 10.10.4
 * Vim version: 7.4.826 + iTerm 2.1.1

## Minimal vimrc less than 50 lines
```vim
set nocompatible
set runtimepath+=~/path/to/neocomplete.vim

set fo+=aw
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
set tw=10

set indentexpr=GetIndent()

" When I type 2nd "e" of "else", GetIndent() should be called
" since 'indentkeys' contains 'e' by default
set indentkeys&

" add a 'indentkeys' for comparison
set indentkeys+=0=foofoo

function! GetIndent()
  return indent(v:lnum - 1) + 2
endfunction
```

## Reproducable ways from Vim starting
```sh
$ cat test
foofoo
else
foo
  foo

```

 1. ``` vim -u vimrc test ```
 2. ``` Gielse<CR> ``` or ``` Gifoofoo<CR> ``` for comparison

**Comment by Shougo** [comment]
`Gielse<CR>` result

```
foofoo
else
foo
  foofoo
    foo
```

`Gifoofoo<CR>` result


```
foofoo
else
foo
  foofoo
    foo
```

**Comment by Shougo** [comment]
Please test your instructions.

**Comment by popkirby** [comment]
The test file includes line break at last (number of lines is 5.)  Sorry for confusing you.

**Comment by Shougo** [comment]
Fixed.

**Comment by popkirby** [comment]
Thank you.
