### ISSUE TITLE
function hint neocomplete 

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/neocomplete.vim#460]
![68747470733a2f2f7261772e6769746875622e636f6d2f646176696468616c7465722f6a6564692f6d61737465722f646f63732f5f73637265656e73686f74732f73637265656e73686f745f66756e6374696f6e2e706e67](https://cloud.githubusercontent.com/assets/13202562/9291620/60c04d66-43c4-11e5-83d2-3a1ee7381a95.png)

you think that it's possible to do for neocomplete  , in youcompleteme plugin they work to accomplish so it will be nice that youcomplete me do that

**Comment by ujihisa** [comment]
http://github.com/Shougo/echodoc.vim

**Comment by Shougo** [comment]
Yes.  I don't want to implement another feature.
Closing.
