### ISSUE TITLE
it's very slow on win10 x64

### ISSUE THREAD

**Issue by foxundermoon** [Shougo/neocomplete.vim#462]
and the vimproc can not run well on the win10。
my gvim version is 7.4.824 。
i'm use it with gocode。
Before I used the system(win8.1) smoothly
i don't know where is wrong!

**Comment by Shougo** [comment]
Note:  I don't have Windows 10 environment.

Question:

1. vimproc works?  What is the mean of "vimproc can not run well"?

2. Please read the issue template.
https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by Shougo** [comment]
It is not neocomplete problem.
