### ISSUE TITLE
smart_close_popup not working properly

### ISSUE THREAD

**Issue by mattiasahlsen** [Shougo/neocomplete.vim#463]
neocomplete#smart_close_popup() doesn't do what it says it does in the documentation. It doesn't save the indent, instead it simply closes the popup and removes the indent (if one was selected).

**Comment by Shougo** [comment]
```
				*neocomplete#smart_close_popup()*
neocomplete#smart_close_popup()
		Insert candidate and re-generate popup menu for neocomplete.
		Unlike |neocomplete#close_popup()|, this function changes
		behavior by |g:neocomplete#enable_auto_select| smart.
		Note: This mapping is conflicted with |SuperTab| or |endwise|
		plugins.
		Note: This key mapping is for <C-h> or <BS> keymappings.
		You should not use it for <CR>.
```

> neocomplete#smart_close_popup() doesn't do what it says it does in the documentation. It doesn't save the indent, instead it simply closes the popup and removes the indent (if one was selected).

`neocomplete#smart_close_popup()` does not have the save indent feature.
And please read the issue template.
I cannot reproduce your problem.

https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by mattiasahlsen** [comment]
I meant save candidate. Shouldn't smart_close_popup() insert the selected autocomplete candidate? I doesn't for me.

**Comment by Shougo** [comment]
@mattiasahlsen Please read the issue template.
I will try it.

**Comment by Shougo** [comment]
No response.
