### ISSUE TITLE
Candidates keep jumping on screen and then disappear in gvim (macvim)

### ISSUE THREAD

**Issue by yarray** [Shougo/neocomplete.vim#464]
![neocomplete](https://cloud.githubusercontent.com/assets/1227829/9452688/f8bf99d0-4ab5-11e5-84d3-557d15239bce.gif)

Normal typing may trigger this, and backspace usually triggers it. It seems that after a little period some previous words will not jump any more. Terminal vim works without this problem. 

My settings:

``` vimL
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#enable_fuzzy_completion = 0

if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
let g:neocomplete#force_omni_input_patterns.javascript = '[^. \t]\.\w*'

call neocomplete#custom#source('omni',
	\ 'disabled_filetypes', {'html': 1})

set splitbelow
let g:neocomplete#enable_auto_close_preview = 1

" SuperTab like snippets behavior.
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: "\<TAB>"

```

Vim version is MacVim 7.4 with patches 1-712. OS version is OS X 10.10.5

**Comment by Shougo** [comment]
I don't understand the issue.
Please describe it in detail.

**Comment by yarray** [comment]
As the gif suggests, when I typed "collaboration" and then backspace in insert mode, the word 

1. becomes "collaboratio", and then
2. becomes "collaboration", and then again
3. becomes "collaboratio"

As I continue backspacing, the whole word of "collaboration" keeps "jumping in" and disappear, which makes visual noise. It just looks like that the first candidate is auto selected, and then the original text is recovered.  Compare it with that in terminal vim:

![necomplete-term](https://cloud.githubusercontent.com/assets/1227829/9476009/91ec0378-4b6a-11e5-9340-99d8d632529d.gif)

When I backspace for "collaboration", the word simply becomes "collaboratio". When I continue backspacing the suggestion of "collaboration" always appeared in the completion menu, but never jumped in the buffer.

**Comment by Shougo** [comment]
OK.  I get it.
You should map `<C-h>` and `<BS>`.

```vim
	inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
	inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
```

**Comment by yarray** [comment]
Many thanks for your reply. However it changes the behavior of backspace which is not what I wanted.

To make things clearer I quickly scanned the code and it seemed for a completion:

1. "complete()" is invoked so the menu will pop up while the first candidate is selected, and
2. "<C-p>" is invoked by the mapping#pop_post so the completed part is removed

My guess is that in terminal the speed of the selected/removed cycle is too fast to notice, however in gvim it is observerable. Also after checking the screenshots in README again I find it seems a normal behavior of neocomplete..

This is only a little visual noise for me. This is still an perfect plugin to use. I just wondering why this condition doesn't appear in some other plugins. Do they use a different mechanism other than calling "complete()"?

Hope this time I get things clear.

**Comment by Shougo** [comment]
OK.  I get it.  It just flick problem.
It is already fixed in Vim 7.4.775.
You should update your Vim.

But I think you use MacVim.  It is Vim 7.4.769 base.
I don't recommend to use it.

**Comment by yarray** [comment]
That makes sense. Thanks a lot!

**Comment by aakashsigdel** [comment]
I have this problem. I have vim 7.4.998

Here is my neocompelete settings:

```
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_delimiter = 1
let g:neocomplete#enable_auto_select = 0
let g:neocomplete#enable_fuzzy_completion = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#force_overwrite_completefunc = 1
let g:neocomplete#max_list = 10
let g:neocomplete#use_vimproc = 1
let g:neocomplete_enable_camel_case_completion = 0
let g:neocomplete_enable_fuzzy_completion_start_length = 2

" Fix the omnicompletion for NeoComplete with force.
if !exists('g:neocomplcache_force_omni_patterns')
    let g:neocomplcache_force_omni_patterns = {}
endif

" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"

let g:neocomplete#sources#vim#complete_functions = {
        \     'Unite': 'unite#complete_source',
        \     'VimShell': 'vimshell#complete',
        \     'VimFiler': 'vimfiler#complete',
        \ }
call neocomplete#custom#source('ultisnips', 'rank', 500)
" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType javascript setlocal omnifunc=tern#Complete
" Disable the neosnippet preview candidate window. Or it will ruin your overview, especially when splits are used. 
set completeopt-=preview
```

**Comment by aakashsigdel** [comment]
I started having this problem after I used vim-plug instead of vundle.
I am using Vim 7.4.998

Here is my neocomplete settings:
```
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_delimiter = 1
let g:neocomplete#enable_auto_select = 0
let g:neocomplete#enable_fuzzy_completion = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#force_overwrite_completefunc = 1
let g:neocomplete#max_list = 10
let g:neocomplete#use_vimproc = 1
let g:neocomplete_enable_camel_case_completion = 0
let g:neocomplete_enable_fuzzy_completion_start_length = 2

" Fix the omnicompletion for NeoComplete with force.
if !exists('g:neocomplcache_force_omni_patterns')
    let g:neocomplcache_force_omni_patterns = {}
endif

" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"

let g:neocomplete#sources#vim#complete_functions = {
        \     'Unite': 'unite#complete_source',
        \     'VimShell': 'vimshell#complete',
        \     'VimFiler': 'vimfiler#complete',
        \ }
call neocomplete#custom#source('ultisnips', 'rank', 500)
" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType javascript setlocal omnifunc=tern#Complete
" Disable the neosnippet preview candidate window. Or it will ruin your overview, especially when splits are used. 
set completeopt-=preview
```

**Comment by Shougo** [comment]
Please upload `neocomplete#util#is_complete_select()` result.

**Comment by aakashsigdel** [comment]
git gives me output as 1

**Comment by Shougo** [comment]
Hm.  New feature is working.
Your flick seems another flick.

Please your detailed information.

**Comment by aakashsigdel** [comment]
![exportvim](https://cloud.githubusercontent.com/assets/4772643/12197944/cc714920-b633-11e5-9679-be2d5e543945.gif)

Sorry for the late reply.
When I type "co" then the completion kicks and highlights the first result automatically, and it does the same when i reach "componentD", then it gets super laggy and slow. And when I backspace, it keep highlighting for each letter.

**Comment by Shougo** [comment]
OK.  I get it.  It is Vim' feature.
complete_select feature does not solve the flick problem.
I will fix it later and send to the patch to vim_dev...

**Comment by nabn** [comment]
@Shougo, I'm noticing this behaviour with deoplete under neovim too.

**Comment by Shougo** [comment]
Yes.  Because the same function is implemented by me.

**Comment by Shougo** [comment]
It fixes the problem for neovim.
https://github.com/neovim/neovim/pull/4036

**Comment by aakashsigdel** [comment]
It solves the flickering problem but still the completion is painfully slow.
I have a file of 250 lines. The completion is very slow.

**Comment by sanscore** [comment]
I'm seeing the same issue that @aakashsigdel has demonstrated; The first match is selected, then quickly deselected. I use vim from the terminal (iTerm2) on El Capitan and Gnome-Terminal on Fedora 23.

**Comment by Shougo** [comment]
It is fixed in neovim.
But in Vim, not.  I will create the patch.

**Comment by Shougo** [comment]
https://github.com/vim/vim/pull/656

I have fixed the problem.  Please test it and vote it.

**Comment by Shougo** [comment]
http://ftp.vim.org/vim/patches/7.4/7.4.1405

Fixed.
