### ISSUE TITLE
I get an error saying "cannot create directory /home/user/.cache/neocomplete/dictionary_cache in sudo session

### ISSUE THREAD

**Issue by doMynation** [Shougo/neocomplete.vim#465]
The plugin seems to work, I get autocomplete based on the words that already exist in the file, but the autocomplete doesn't work with PHP's core function (i have to manually press C-x + C-o to make them appear.

Here is the error I get "cannot create directory /home/user/.cache/neocomplete/dictionary_cache in sudo session". I always open my files with sudo vim file_name. I have to use sudo, otherwise i can't write.

And here is my .vimrc: https://gist.github.com/doMynation/e465e8dfc97fe61a4518

Thank you for your time !

**Comment by crazymaster** [comment]
Why do you always have to use sudo? It is not recommended.

On the other hand, you should use sudoedit if you need sudo permission.

**Comment by Shougo** [comment]
>The plugin seems to work, I get autocomplete based on the words that already exist in the file, but the autocomplete doesn't work with PHP's core function (i have to manually press C-x + C-o to make them appear.

You should use `g:neocomplete#force_omni_input_patterns` instead of `g:neocomplete#sources#omni#input_patterns`.

> Here is the error I get "cannot create directory /home/user/.cache/neocomplete/dictionary_cache in sudo session". I always open my files with sudo vim file_name. I have to use sudo, otherwise i can't write.

You should create manually "/home/user/.cache/neocomplete/dictionary_cache" directory.
neocomplete cannot create the directory in sudo session.
Because, it is dangerous.
