### ISSUE TITLE
Undefined variable fdlist error on opening or switching to any buffer

### ISSUE THREAD

**Issue by Ghopper21** [Shougo/neocomplete.vim#468]
I just updated to the latest version and now am getting the following error whenever I open a file or switch to an already opened buffer:

> [vimproc] function <SNR>115_check_source..<SNR>115_make_cache_file..neocomplete#cache#async_load_from_file..<SNR>132_async_load..vimproc#system_bg..vimproc#pgr
oup_open..<SNR>135_pgroup_open..vimproc#plineopen3..<SNR>135_plineopen..<SNR>135_vp_pipe_open..<SNR>135_libcall, line 11
[vimproc] vimproc: vp_pipe_open: ['vp_stack_pop_num: sscanf error']
[vimproc] Error occurred in calling s:vp_pipe_open()
[vimproc] a:argv = ['/Applications/MacVim.app/Contents/MacOS/vim', '-u', 'NONE', '-i', 'NONE', '-n', '-N', '-S', '/Users/ien/.vim/bundle/neocomplete.vim/autolo
ad/neocomplete/async_cache.vim', 'load_from_file', '/Users/ien/.cache/neocomplete/buffer_cache/=+Users=+ien=+Studio=+killian=+Assets=+Game=+Gameplay=+Conductor
s=+SimpleChordConductor.cs', '/Users/ien/Studio/killian/Assets/Game/Gameplay/Conductors/SimpleChordConductor.cs', '/Users/ien/.cache/neocomplete/keyword_patter
ns/=+Users=+ien=+Studio=+killian=+Assets=+Game=+Gameplay=+Conductors=+SimpleChordConductor.cs', 'B', '4', 'utf-8']
[vimproc] original a:argv = ['/Applications/MacVim.app/Contents/MacOS/vim', '-u', 'NONE', '-i', 'NONE', '-n', '-N', '-S', '/Users/ien/.vim/bundle/neocomplete.v
im/autoload/neocomplete/async_cache.vim', 'load_from_file', '/Users/ien/.cache/neocomplete/buffer_cache/=+Users=+ien=+Studio=+killian=+Assets=+Game=+Gameplay=+
Conductors=+SimpleChordConductor.cs', '/Users/ien/Studio/killian/Assets/Game/Gameplay/Conductors/SimpleChordConductor.cs', '/Users/ien/.cache/neocomplete/keywo
rd_patterns/=+Users=+ien=+Studio=+killian=+Assets=+Game=+Gameplay=+Conductors=+SimpleChordConductor.cs', 'B', '4', 'utf-8']
Error detected while processing function <SNR>115_check_source..<SNR>115_make_cache_file..neocomplete#cache#async_load_from_file..<SNR>132_async_load..vimproc#
system_bg..vimproc#pgroup_open..<SNR>135_pgroup_open..vimproc#plineopen3..<SNR>135_plineopen..<SNR>135_vp_pipe_open:
line   25:
E121: Undefined variable: fdlist
E116: Invalid arguments for function len(fdlist)
E15: Invalid expression: a:npipe != len(fdlist)
Error detected while processing function <SNR>115_check_source..<SNR>115_make_cache_file..neocomplete#cache#async_load_from_file..<SNR>132_async_load:
line   18:
E171: Missing :endif

**Comment by Shougo** [comment]
It seems vimproc's error.
Please report the problem in vimproc issue tracker.

1. vimproc is latest version?
2. vimproc works?
3. Please create minimal .vimrc and reproduce ways from Vim starting.
