### ISSUE TITLE
Ctrl-p and enter not completing prediction

### ISSUE THREAD

**Issue by czepluch** [Shougo/neocomplete.vim#470]
I have just made a fresh install of spf13, but for some reason, when I have a list of suggestions for a completion neither ctrl-p nor enter works. It just closes the prediction dropdown.

Edit: Might be the wrong place I have created the issue, but thought I'd rather go to the source. Let me know if totally unrelated and I'll delete the issue.

**Comment by Shougo** [comment]
Unfortunatelly, it is not neocomplete issue.
neocomplete does not overwrite `<c-p>` and `<Enter>` mappings.
You should check `<C-p>` and `<Enter>`.

```vim
verbose map <C-p>
verbose map <Enter>
```
