### ISSUE TITLE
After Vim patch 7.4.851 async "buffer cache" is not saved

### ISSUE THREAD

**Issue by AlexMasterov** [Shougo/neocomplete.vim#471]
# Problems summary
After Vim patch [7.4.851](https://github.com/vim/vim/releases/tag/v7.4.851) vim.exe starts in bg. and crashes trying to run the command:
```
D:\Vim\vim74\vim.EXE -u NONE -i NONE -n -N -S D:/Vim/vimfiles/bundle/neocomplete.vim/autoload/neocomplete/async_cache.vim load_from_file D:/Vim/vimfiles/cache/buffer_cache/D=-=+Vim=+test.js D:\Vim\test.js D:/Vim/vimfiles/cache/keyword_patterns/D=-=+Vim=+test.js B 4 utf-8
```
Looks like: [#468](https://github.com/Shougo/neocomplete.vim/issues/468)

## Environment Information
 * OS: Windows 10
 * Vim version:  7.4.865  (7.4.850 and below works well)

## Reproducable ways from Vim starting
0. Minimal vimrc and vimproc.vim
1. NeoCompleteClean
2. NeoCompleteBufferMakeCache

**Comment by Shougo** [comment]
OK, it seems Vim's degrade.
I will create issue in vimproc.

**Comment by Shougo** [comment]
Fixed it in Vim 7.4.876.

**Comment by AlexMasterov** [comment]
Also crashes.

**Comment by mattn** [comment]
@AlexMasterov I'm writing patch to vim to fix problem similar to this issue. Currently, we confirm this issue occur only on windows7. but you seems getting same issue. right?

https://github.com/vim-jp/issues/issues/772

below is a patch can be applied to windows10 also

https://gist.github.com/mattn/8b29d2dd5025bfb56a25

Could you please try this?

**Comment by AlexMasterov** [comment]
Eh, also crashes.
```
conhost.exe [10.0.10240.16384]
ConhostV2.dll [10.0.10240.16391]
Exception code: 0xc0000005
The offset error: 0x0000000000020a7b
```
![vim_7 4 884p](https://cloud.githubusercontent.com/assets/700213/10154300/2e31e252-666e-11e5-860f-dcf551bcd40f.png)

**Comment by mattn** [comment]
I want to figure out whether this is a bug of vim or necomplete. Could you please try:

```
:!git http://github.com/vim/vim.git foobar
```

**Comment by k-takata** [comment]
Do you use special terminal emulator like ConEmu, etc?

**Comment by AlexMasterov** [comment]
@k-takata Yes, but without global registration.

**Comment by k-takata** [comment]
So, does the crash only occurs when you running Vim on ConEmu? Or it occurs even if you running in the normal Command Prompt?

**Comment by AlexMasterov** [comment]
@k-takata I don't run vim under terminal. The above screenshot is attached to show what I really tried to compile with the suggested patch. (and it didn't help for me) There is a standard Windows console.

I also tried with the latest vimproc.vim with a clean recompile. What else can I do?
While using latest gvim.exe (gui version) with vim.exe (console version) 7.4.850. No problem.

**Comment by mattn** [comment]
Could you give us minimal way to reproduce? For example

```
:!something-command-crash.exe
```
or
```
:echo system("broken-command.exe")
```
or something to reproduce.

**Comment by AlexMasterov** [comment]
[neocomplete/cache.vim](https://github.com/Shougo/neocomplete.vim/blob/master/autoload/neocomplete/cache.vim#L254)
```viml
call system(join(args))
```
Like not crash.
```viml
echo system(join(args))
```
"Vim: Warning: Output is not to a terminal". (ofc)

**Comment by mattn** [comment]
Can you see what arguments passing?

**Comment by AlexMasterov** [comment]
@mattn see "Problems summary", crashes trying to run the command like this:
```
D:\Vim\vim74\vim.EXE -u NONE -i NONE -n -N -S D:/Vim/vimfiles/bundle/neocomplete.vim/autoload/neocomplete/async_cache.vim load_from_file D:/Vim/vimfiles/cache/buffer_cache/D=-=+Vim=+test.js D:\Vim\test.js D:/Vim/vimfiles/cache/keyword_patterns/D=-=+Vim=+test.js B 4 utf-8
```
I repeat that only ```call system("command")``` not crash.  If use ```call vimproc#system("command")``` then it crashes.

**Comment by mattn** [comment]
@AlexMasterov Thanks. So do you mean this is an issue of vimproc not vim. right?

**Comment by k-takata** [comment]
> If use call vimproc#system("command") then it crashes.

Does it depend on command? How about `:call vimproc#system("dir")`?

**Comment by AlexMasterov** [comment]
@mattn looks like so.
@k-takata ```echo vimproc#system("dir")``` displays a list of files, but here does not create a child process.

**Comment by k-takata** [comment]
I want to know that the crash can be reproduced without neocomplete.
Does this crash? `:call vimproc#system("vim -c quit")`

**Comment by AlexMasterov** [comment]
@k-takata yes, it is crashes.

**Comment by Shougo** [comment]
@AlexMasterov 

Please test following python script.  It crashes?

```python
import subprocess
p = subprocess.Popen(['vim', '-c', 'quit'], shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print("waiting")
stdout_data, stderr_data = p.communicate()
print("finish: %d %d" % (len(stdout_data), len(stderr_data)))
print(str([p.returncode, stdout_data, stderr_data]))
```

My output in Linux.

```
waiting
finish: 187 85
[0, b'\x1b[?1006h\x1b[?1002h\x1b[?1049h\x1b[?2004h\x1b[?1h\x1b=\x1b[1;24r\x1b[?12;25h\x1b[?12l\x1b[?25h\x1b[27m\x1b[23m\x1b[m\x1b[38;5;253m\x1b[48;5;236m\x1b[H\x1b[2J\x1b[?1006l\x1b[?1002l\x1b[?1006h\x1b[?1002h\x1b[24;1H\x1b[?1006l\x1b[?1002l\x1b[?1l\x1b>\x1b[?1049l\x1b[?2004l', b'Vim: Warning: Output is not to a terminal\nVim: Warning: Input is not from a terminal\n']
```

**Comment by AlexMasterov** [comment]
@Shougo 
```viml
:execute 'pyfile ' . expand('%')
:execute 'py3file ' . expand('%')
:!py %
```
Not crash and output:
```waiting
finish: 0 87
[0, '', 'Vim: Warning: Output is not to a terminal\r\nVim: Warning: Input is not from a terminal\r\n']
```

**Comment by Shougo** [comment]
OK.  It seems vimproc's bug.
I will try it in Windows 7 environment.

**Comment by Shougo** [comment]
I have tested it in environment, but it works....
I think it seems in Windows 10 only problem.
Can other people test it?
I have not Windows 10 environment, so I cannot fix it...

**Comment by AlexMasterov** [comment]
@Shougo what can I do to help? debug?

**Comment by Shougo** [comment]
We need to check what the function crashes Vim.
So, 

* You can check the crash statement in `vimproc#system()` implementation.

* You can check the crash statement in C code(`proc_w32.c` functions).

I cannot check them...

**Comment by Shougo** [comment]
Vim 7.4.851 is reverted in 7.4.902.
Closing.
