### ISSUE TITLE
Neocomplete breaks ctrl-y

### ISSUE THREAD

**Issue by DavidEGx** [Shougo/neocomplete.vim#473]
Problem:

When using neocomplete ctrl-y in insert mode stops working as expected. As soon as a word popups ctrl-y stops working.

Expected:

Every press of ctrl-y should copy the character above the cursor

Environment Information:
* Ubuntu 15.04
* Vim 7.4.488

.vimrc:

    set rtp+=~/.vim/bundle/vundle/
    set nocompatible
    filetype off
    call vundle#begin()
    Bundle 'shougo/neocomplete.vim'
    call vundle#end()
    filetype plugin indent on
    
    let g:neocomplete#enable_at_startup = 1

Steps to reproduce:

    i
    hello hola ciao<CR>
    <C-y><C-y><C-y><C-y>

**Comment by Shougo** [comment]
```vim
inoremap <expr><C-y>  neocomplete#close_popup()
```

**Comment by DavidEGx** [comment]
That breaks <c-y> even more.

Anyway, shouldn't just work as normal by default?

**Comment by Shougo** [comment]
Unfoatunatelly, no.

> That breaks even more.

What is the break?   Please explain it to me.

**Comment by Shougo** [comment]
I have implemented the feature.
You don't have to map the mappings.

**Comment by DavidEGx** [comment]
Normally when you use <C-y> in insert mode vim just copy the character above from the previous line. Keeping <C-y> pressed would eventually copy the whole line.

So having something like:

```
var this_is_a_test1 = 1;

```
I can just press `<c-y>` until I get:


```
var this_is_a_test1 = 1;
var this_is_a_test
```
And then finish by typing `2 = 2;` or whatever.

When neocomplete is enabled if I keep `<c-y>` pressed it stops in:

```
var this_is_a_test1 = 1;
var th
(Offering a popup with "this_is_a_test_1".)
```

At that point `<c-y>` doesn't work anymore so I have to type manually the whole thing.

**Comment by Shougo** [comment]
I improved the behavior.  Please update neocomplete.
Unfortunatelly, auto completion feature conflicts with `<C-y>` completion.
I think it same with other completion system like YouCompleteMe.
If you want to complete whole line, you should lock neocomplete by `:NeoCompleteLock`.

**Comment by DavidEGx** [comment]
Same thing after updating.

Something like:

```
inoremap <c-y> <esc>:NeoCompleteDisable<CR>a<c-y><esc>:NeoCompleteEnable<CR>a
```

Seem to fix the problem. Although a bit clunky.

**Comment by Shougo** [comment]
@DavidEGx You should use `:NeoCompleteLock` and `:NeoCompleteUnlock` instead of `:NeoCompleteDisable` and `:NeoCompleteEnable`.

**Comment by Shougo** [comment]
You should use `<C-o>:command<CR>` instead of `<ESC>:command<CR>a`.

**Comment by DavidEGx** [comment]
Thanks, I'll keep it as:

```
inoremap <c-y> <c-o>:NeoCompleteLock<CR><c-y><c-o>:NeoCompleteUnlock<CR>
```

then.
