### ISSUE TITLE
Error detected while processing function neocomplete#mappings#auto_complete

### ISSUE THREAD

**Issue by Zundrium** [Shougo/neocomplete.vim#474]
To reproduce the error:

`vim test.py`
and type `if test == "14.` 

This will result in:
`Error detected while processing function neocomplete#mappings#auto_complete:`
`E117: Unknown function: SyntasticStatuslineFlag`

My .vimrc file: https://gist.github.com/Zundrium/797f93e675a944b9a7e3

Hope someone can help :+1:

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/236

Please read the issue template.
Your .vimrc is too long.
And please upload whole error messages.
You should take screenshot or save the error by `:redir` command.

**Comment by Shougo** [comment]
No response.
