### ISSUE TITLE
KEY MAPPINGS doesn't work on my mac !

### ISSUE THREAD

**Issue by The33Coder** [Shougo/neocomplete.vim#475]
Hi
I installed the spf13-vim and i have the last version of neocomplete.vim on .vim/bundle.
But if I press <C-y> key the selected item disappears and nothing happens.

Exemple I create a new file index.html I open this vil with vim and i write ht. The html5 is proposed. If I select with Tab and press `<C-y>` the menu disappears and the cursor aparea cursor appears to write. But if i press `<C-k>`. I have the html 5 template. After if I whant to add a h1 neither `<C-y>` or `<C-k>` work.

**Comment by Shougo** [comment]
I don't understand  the problem.
It seems spf13-vim's keymapping conflict.
spf13-vim is out of support.
Because, spf13-vim mixes configurations and plugins.

**Comment by Shougo** [comment]
@The33Coder If you want to get my support, you should read the issue template.
