### ISSUE TITLE
Query/Help - Tab Completion not Functioning

### ISSUE THREAD

**Issue by BrendanThompson** [Shougo/neocomplete.vim#476]
Hi there,

I have the latest version of the plugin, and I have used the example config from the `README.md` to try and get tab completion working. However, it seems to just insert a tab instead of completing the first entry from the `neocomplete` dropdown. I also tried using the [Smart Tab Completion](https://github.com/Shougo/neocomplete.vim/blob/master/doc/neocomplete.txt#L962) section from the `neocomplete.txt`, which also is having the same effect, any ideas what could be causing it to insert a tab instead of inserting the completion?

---

I am running OS X 10.11

Thanks,

Brendan

**Comment by Shougo** [comment]
```vim
		inoremap <expr><Tab>		pumvisible() ? "\<C-n>" : "\<Tab>"
```

**Comment by Shougo** [comment]
You should provide your desired behavior with examples.
