### ISSUE TITLE
Completion issues

### ISSUE THREAD

**Issue by 20115681** [Shougo/neocomplete.vim#477]
### Environment
```
Archlinux
Vim 7.4.854
```
### Vimrc
```
call plug#begin('~/.vim/plugged')

Plug 'Shougo/neocomplete.vim'
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#max_list = 5
let g:neocomplete#enable_auto_select = 1
let g:neocomplete#enable_smart_case = 1

call plug#end()

syntax on
```

### Problem 1
```
When i press enter, vim inserts new line instead of selected item.
```
![neocomplete](https://cloud.githubusercontent.com/assets/11208291/10040650/ae111152-6207-11e5-9dc9-5b32e4e40719.gif)

### Problem 2
```
Complete menu is different in same context and in wrong order.
```

![fuzzy](https://cloud.githubusercontent.com/assets/11208291/10040928/5b1c3794-620a-11e5-8700-40aebf8de6fa.png)

**Comment by Shougo** [comment]
> Complete menu is different in same context and in wrong order.

It is feature.  neocomplete ignores the order.

**Comment by Shougo** [comment]
> When i press enter, vim inserts new line instead of selected item.

```vim
inoremap <expr><CR> pumvisible()? "\<C-y>" : "\<CR>"
```

**Comment by 20115681** [comment]
Thanks. Since i also use delimitMate, this mapping is better:
```imap <expr> <cr> pumvisible() ? "\<c-y>" : "<Plug>delimitMateCR"```
