### ISSUE TITLE
[Minor] No support for system-wide installation

### ISSUE THREAD

**Issue by Coacher** [Shougo/neocomplete.vim#478]
Hello.

`neocomplete` cannot be installed on a system-wide level as it conflicts with other plugins like `neoinclude` and `vimshell`. This is because `autoload/vital.vim` file is included in all these plugins,
which leads to file collisions.

Can something be done to avoid this problem? Can these plugins utilize a system-wide installation of [vim-jp/vital.vim](https://github.com/vim-jp/vital.vim) plugin?

There are no problems with per-user installation.

**Comment by Shougo** [comment]
It is not problem.
Because, the autoload/vital.vim is same.
You can overwrite it.

**Comment by Coacher** [comment]
But it is a problem. Let me elaborate a bit.

I don't know about Windows platform, but virtually any Linux package manager won't install packages that overwrite existing files. Thus if one wants to properly package say neoinclude and neocomplete, then autoload/vital.vim must be removed from either one of them. And then imagine one wants to package vimshell as well. Again autoload/vital.vim must be excluded from installation. It becomes messy very fast this way because things start depend on one another in weird ways.

The proper way is to install vital.vim plugin system-wide and then remove autoload/vital.vim from any other plugin that provides it since this file is just a loader. But I've noticed that your bundled vital.vim parts diverged from the original. Thus I am not sure whether things will still work this way. Do you support the original vital.vim in your plugins or only the bundled parts?

**Comment by Shougo** [comment]
OK.  I get it.
But I cannot remove "autoload/vital.vim".
It breaks vital policy.

You can have 2 ways.

1. Remove "autoload/vital.vim" from the plugins and create vital.vim package.
2. Install the plugins in separated directories and add the paths.

**Comment by Coacher** [comment]
OK. That's fine.

One last thing. Since you [bundle](https://github.com/Shougo/neocomplete.vim/tree/master/autoload/vital/_neocomplete) parts of [vital.vim](https://github.com/vim-jp/vital.vim/tree/master/autoload/vital/__latest__), do you claim the support of the upstream vital.vim in any of your plugins? That is would your plugins work with bundled parts removed and vital.vim available in `'runtimepath'`?

**Comment by Shougo** [comment]
> Since you bundle parts of vital.vim, do you claim the support of the upstream vital.vim in any of your plugins? 

No. Because, I am one of vital developers.

> That is would your plugins work with bundled parts removed and vital.vim available in 'runtimepath'?

vital.vim works if it is exists in runtimepath.

**Comment by Coacher** [comment]
Thank you very much for clarifying things for me!
