### ISSUE TITLE
enable_cursor_hold_i disables fuzzy matching

### ISSUE THREAD

**Issue by sunaku** [Shougo/neocomplete.vim#479]
Hello,

To reproduce this issue:

1. Run `:new`
2. Run `:setf vim`
3. Enter insert mode and type `ino`
4. Completion pop-up will now appear
5. Type `p`

Now, if `let g:neocomplete#enable_cursor_hold_i = 1` is set, the entered `inop` input matches nothing.  Otherwise, it will match the `inoremap` pop-up menu item because fuzzy matching is not disabled.

Why does `enable_cursor_hold_i` disable fuzzy matching?  It should not. :crying_cat_face:

Thanks for your consideration.

**Comment by Shougo** [comment]
Fixed.

**Comment by sunaku** [comment]
Thank you! :bow:

**Comment by davidosomething** [comment]
I think this caused problem when using `o` to open new line below text

**Comment by Shougo** [comment]
@davidosomething 
Please describe the problem in detail.
I have not ESP skills.

**Comment by davidosomething** [comment]
See README.md in this gist for how to replicate
https://gist.github.com/davidosomething/01b752d81d63c5463d88

**Comment by Shougo** [comment]
It is not the related issue.
It is just wrong examples.

```vim
return (pumvisible() ? "\<C-y>" : "") . "\<CR>"
```

is correct mapping.
