### ISSUE TITLE
Text inserted in wrong place

### ISSUE THREAD

**Issue by wilywampa** [Shougo/neocomplete.vim#481]
# Problems summary

In some situations text is insert in the wrong place after the completion menu is shown. For example, changing `g:varname` to `get(g:, ...` instead inserts `get(g:varname,`

## Environment Information

 * OS: OSX 10.5.5
 * Vim version: 7.4.803
 * Unite 2b9f5f4c60a24f60d4ef0df28ada94b138ea1e83

## Minimal vimrc less than 50 lines

    set nocompatible noshowmode
    set hidden hlsearch incsearch
    syntax enable
    filetype plugin indent on
    set runtimepath+=/Users/jniehus/Documents/vimconfig/vimfiles/bundle/neocomplete
    let g:neocomplete#enable_at_startup = 1

## Reproducible ways from Vim starting

 1. Open a file and set filetype to `vim`.
 2. Insert text `let foo = g:neocomplete#sources`
 3. Move cursor to `g:` and insert `get(`
 4. Move cursor in front of `neocomplete` and try to enter `, ` or anything else.

## Screen shot (if possible)
![cursorpos](https://cloud.githubusercontent.com/assets/4472522/10154489/ad7c99dc-661c-11e5-817b-74d7b88a46ae.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by wilywampa** [comment]
Thanks!
