### ISSUE TITLE
Is there a recommended auto-closing plugin compatible with neocomplete?

### ISSUE THREAD

**Issue by kikito** [Shougo/neocomplete.vim#484]
Hi there,

Neocomplete is awesome. I would like to use it with an auto-closing plugin. I don't mind which one. I just need something which inserts `)` and moves the cursor back once when I type `(`.

It seems that neocomplete has ... "issues" with plugins of this kind. I have seen issues closed for delimitmate (#477, #243) and auto-pairs (#286)

My question is: Is there a recommended auto-close plugin (or set of functions) which work well with neocomplete out of the box? Or is this a problem without solution and one always needs to remap CR?

**Comment by Shougo** [comment]
I don't know about it.
Because, I don't use auto-closing plugins.

> My question is: Is there a recommended auto-close plugin (or set of functions) which work well with neocomplete out of the box? Or is this a problem without solution and one always needs to remap CR?

Most of the plugins remap `<CR>` to insert begin-end pairs like this:

```
if<CR>

to

if
  |
endif
```

If you need just `()` pairs, you should map them.

```vim
inoremap (  ()<Left>
```
