### ISSUE TITLE
Regression: working in combination with jedi-vim auto-selects LAST option

### ISSUE THREAD

**Issue by ngoonee** [Shougo/neocomplete.vim#485]
# Problems summary
Was working with jedi-vim+neocomplete pulled on Jul 15, when I pulled on Oct 7th this now happens:-

from bli

will bring up a popup, I can then select blinker using Ctrl-N

when I hit space after that, it inserts `import __version__` rather than just `import ` where `__version__` is the last possible selection

Based on other issues previously reported here, I have tested what happens with Ctrl-X,Ctrl-O instead of Ctrl-N to select `blinker`. In that case it works as expected.

## Environment Information
 * OS: Arch Linux 64-bit
 * Vim version: 7.4.884-1
 * latest git versions of neocomplete and jedi-vim as of now

## Minimal vimrc less than 50 lines

   " Your vimrc
set nocompatible
filetype plugin on

" Enable neocomplete
let g:neocomplete#enable_at_startup = 1
"let g:neocomplete#enable_auto_select = 1

" Options for python
augroup python_autocmds
    autocmd!
    au FileType python set fo-=t
    au FileType python setlocal omnifunc=jedi#completions
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python =  '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
    "let g:neocomplete#force_omni_input_patterns.python =  '\h\w*\|[^. \t]\.\w*'
augroup END

## Reproducable ways from Vim starting

 1. Edit a python file
 2. Type from encodings<Space>
 3. Last selection will be selected

## Screen shot (if possible)

**Comment by ngoonee** [comment]
For reference, this probably has something to do with https://github.com/davidhalter/jedi-vim/issues/465

They have a new 'smart_auto_mappings' option.

Is there a way to use jedi without also using jedi-vim? As this seems to cause quite a bit of problems with neocomplete.

**Comment by Shougo** [comment]
I have updated the documentation.

> Is there a way to use jedi without also using jedi-vim? As this seems to cause quite a bit of problems with neocomplete.

You can create the source for neocomplete using jedi.

If you want to use 'smart_auto_mappings' feature with neocomplete, jedi-vim must fix `jedi#complete_opened()`.
Because, neocomplete sets completeopt "noinsert" or "noselect" value, but it is not supported in jedi-vim.
It is jedi-vim problem.

```
						*'completeopt'* *'cot'*
'completeopt' 'cot'	string	(default: "menu,preview")
			global
			{not available when compiled without the
			|+insert_expand| feature}
			{not in Vi}
	A comma separated list of options for Insert mode completion
	|ins-completion|.  The supported values are:

	   menu	    Use a popup menu to show the possible completions.  The
		    menu is only shown when there is more than one match and
		    sufficient colors are available.  |ins-completion-menu|

	   menuone  Use the popup menu also when there is only one match.
		    Useful when there is additional information about the
		    match, e.g., what file it comes from.

	   longest  Only insert the longest common text of the matches.  If
		    the menu is displayed you can use CTRL-L to add more
		    characters.  Whether case is ignored depends on the kind
		    of completion.  For buffer text the 'ignorecase' option is
		    used.

	   preview  Show extra information about the currently selected
		    completion in the preview window.  Only works in
		    combination with "menu" or "menuone".

	   noinsert Do not insert any text for a match until the user selects
		    a match from the menu. Only works in combination with
		    "menu" or "menuone". No effect if "longest" is present.

	   noselect Do not select a match in the menu, force the user to
		    select one from the menu. Only works in combination with
		    "menu" or "menuone".
```

It should be checked like "longest" value.
