### ISSUE TITLE
g:force_omni_input_patternsを指定すると一番下の候補が選択される

### ISSUE THREAD

**Issue by NigoroJr** [Shougo/neocomplete.vim#486]
こんにちは。Vim 7.4.775以降でmonster.vimとmarching.vimの両方のプラグインにて`g:force_omni_input_patterns`に指定した文字を入力したとき、一番下の候補が勝手に選択されるようになりました。

両プラグインとも、`g:force_omni_input_patterns`を指定しない場合はこれが起こりません。 #485 と関係があるのでしょうか？

## 環境
* Gentoo Linux
* Vim 7.4.827

1. 以下のvimrcを使い、`vim -u vimrc foo.rb`
2. `File.`と入力する
3. `File.zero?`と、最後の候補が選択される。

```vim
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))

set updatetime=500
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'osyo-manga/vim-monster', {
    \ 'depends': ['Shougo/neocomplete.vim', 'Shougo/vimproc.vim'],
    \ }
let g:neocomplete#enable_at_startup = 1

" With the following lines commented out, the last candidate is not selected
let g:neocomplete#force_omni_input_patterns = {
     \ 'ruby': '[^. *\t]\.\w*\|\h\w*::'
     \ }

let g:monster#completion#rcodetools#backend = 'async_rct_complete'

call neobundle#end()
filetype plugin indent on
```

**Comment by Shougo** [comment]
再現しました。

> 両プラグインとも、g:force_omni_input_patternsを指定しない場合はこれが起こりません。 #485 と関係があるのでしょうか？

はい。その通りです。両プラグインとも、completeopt の noinsert, noselect に対応していないのでこの現象が起こります。
こちらでは直せないので、作者に報告してください。

問題が起こっている場所は各ソースコードを `<C-p>` で検索すれば明白です。
対策としては、&completeopt に noinsert か noselect がセットされていることを確認し、
セットされていたら `<Down>` や `<C-p>` をしないようにコードを変更すればよいです。

noinsert, noselect の追加により自動補完プラグインには余計な対応が必要となりますが、
いちいちキーマッピングでハックしなくてもよく、非同期に処理させるにもうってつけで
パフォーマンスもよくなるので悪い機能ではないのです。

以上となります。

**Comment by NigoroJr** [comment]
なるほど、了解しました。ありがとうございました。
