### ISSUE TITLE
The autocomplation does not work

### ISSUE THREAD

**Issue by The33Coder** [Shougo/neocomplete.vim#489]
Hi
I installed neocomplete but i don't have the possibility to autocomplete.
![untitled](https://cloud.githubusercontent.com/assets/12548652/10602868/3228db82-771b-11e5-88ef-c4fdbc5cb4e4.gif)
If I press C-y the pop up menu close and nothing is completed.
I'm on mac 10.10, I use vim 7.4.769 and I have lua.
In my vimrc I have
```
set nocompatible
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'Shougo/neocomplete.vim'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'ervandew/supertab'
call vundle#end()
filetype plugin indent on

" -- Encoder in UTF-8
scriptencoding utf-8
set fileencoding=utf-8
set encoding=utf-8
set backspace=2 
set omnifunc=syntaxcomplete#Complete

" --- SuperTab
let g:SuperTabDefaultCompletionType = 'context'

" --- neocomplete
let g:neocomplete#enable_at_startup = 1 
let g:neocomplete#enable_auto_delimiter = 1
let g:neocomplete#enable_auto_close_preview = 1
let g:neocomplete#enable_smart_case = 1

```

Any idea for help me ?

**Comment by Shougo** [comment]
> If I press C-y the pop up menu close and nothing is completed.

It is feature.  You have completed "for" candidate in the screenshot.
No problem.

**Comment by Shougo** [comment]
You should study Vim's completion.
