### ISSUE TITLE
Error occurs if the buffer contains a long word

### ISSUE THREAD

**Issue by kota65535** [Shougo/neocomplete.vim#492]
## Probrem summary
Error occurs if the editing buffer contains long words about 100 characters like hashes.
At first, I thought  this is the same probrem as #69, so I tried setting "g:neocomplete#max_keyword_width". But the error keeps arising...

## Environment
* Mac OS X Yosemite
* Vim/7.4

## vimrc
```vim
set nocompatible

if has('vim_starting') "{{{
  set rtp+=$HOME/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/neocomplete.git'
call neobundle#end()

filetype plugin indent on       " restore filetype

" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#max_keyword_width = 10
```

## Reproducable ways from Vim starting
1. paste the text below.
```
4d623987c63729b578752961445d44257f546f6c223063f358889a5623185343bdaceff80bc91aa91dac04b632cd8532e602da3ae0010a8
dcd42dbc5d3eff058fe6d0a39e1273750c493c4b6d209f75d013d813cfacd2053762fa5986f7bfa460625fa809c3a5e452e96e0c038b23
```
2. type the 3 characters of the head of the long string.
3. error occurs.

## Screenshot
![screenshot](https://cloud.githubusercontent.com/assets/10975834/11002826/6de1ac82-84f2-11e5-9e05-242b045e3503.gif)

**Comment by Shougo** [comment]
Fixed.
