### ISSUE TITLE
[MacVim] Extra newline added when suggestion selected using <enter> key

### ISSUE THREAD

**Issue by subhojit777** [Shougo/neocomplete.vim#493]
When a suggestion is selected using <enter> key, an extra newline is added. As mentioned in the issue, this appears only in MacVim (GUI)/Mac's Vim (CLI), but in Ubuntu I am not having this issue. This is the part of `.vimrc` that adds custom setting to NeoComplete:
```
" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\h\w*\|\h\w*::'

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return neocomplete#close_popup() . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()
```

Any idea what is happening in Mac's Vim but not in Ubuntu's Vim.

![macvim-bug](https://cloud.githubusercontent.com/assets/1435641/11015416/8a33ecd2-8584-11e5-8f25-94feef4b1bea.gif)

**Comment by Shougo** [comment]
Please read the issue template.
I think it is plugins or configuration conflict.

https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by wsdjeg** [comment]
@subhojit777 maybe you can have a look at my vimrc,Enter works well in my vim.
if you want, i can split related configuration，and share it here！
https://github.com/wsdjeg/DotFiles/blob/master/vimrc

**Comment by subhojit777** [comment]
@wsdjeg @Shougo Thanks. There was some problem indeed in my vimrc. I was able to rectify it :) Great plugin :+1:

**Comment by wsdjeg** [comment]
it is really better than YCM or any other complete plugin
