### ISSUE TITLE
[neocomplete] filter name : 'matcher_length' is not found.

### ISSUE THREAD

**Issue by Velconia** [Shougo/neocomplete.vim#496]
[neocomplete] filter name : 'matcher_length' is not found.
Error detected while processing function neocomplete#init#enable..neocomplete#init#_others..neocomplete#init#_variables..neocomplete#util#is_windows..<SNR>41_get_prelude..<SNR>43_im
port..<SNR>43__import:                                                                                                                                                 
E605: Exception not caught: vital: module not found: Prelude                                                                                                                                          
Error detected while processing function neocomplete#init#enable..neocomplete#init#_others..neocomplete#init#_variables..neocomplete#util#is_windows..<SNR>41_get_prelude:                                                                                                                                    
E171: Missing :endif 

After I type enter in vim, it will disappear, and never show up again until I enter vim next time, I was wondering if this is a bug of neocomplete?

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please read the issue template.

https://github.com/Shougo/neocomplete.vim/issues/236

And neocomplete is installed correctly?
I recommend you to reinstall it.

**Comment by Shougo** [comment]
No response.
