### ISSUE TITLE
Getting omni completion to appear consistently with other completion options

### ISSUE THREAD

**Issue by razor-x** [Shougo/neocomplete.vim#498]
I'm trying to work out how to get omni completion `[O]` to appear consistently with other completion results `[B]`, `[nsnip]`, etc. I'm not sure if the behaviour I'm seeing below is a feature or bug.   

I'll use javascript as my test case.

### `.vimrc`

```vim
if 0 | endif

if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  set rtp+=$HOME/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'shougo/neobundle.vim'
NeoBundle 'shougo/neocomplete.vim'
NeoBundle 'shougo/neosnippet.vim'
NeoBundle 'shougo/neosnippet-snippets'
call neobundle#end()

filetype plugin indent on

" Enable neocomplete.
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#auto_completion_start_length = 2

" JavaScript omni completion.
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS

" Start manual completion with Ctrl-Space.
inoremap <expr> <C-Space> neocomplete#start_manual_complete()

" Tab completion.
imap <expr> <Tab> pumvisible() ? "<C-N>" : "<Tab>"

" Close popup on enter.
inoremap <expr> <CR> neocomplete#close_popup() . "<CR>"
```

### `test.js`

```js
'conman'
```

I'll start typing `console` and expect to see `[O]`, `[B]`, and `[nsnip]` in the list.

1. Above config

   I only get `[B]` and `[nsnip]`.

   <img width="282" alt="screenshot at 11-10-00" src="https://cloud.githubusercontent.com/assets/721372/11320156/083f9c42-9044-11e5-96da-f744035066a2.png">

   I can get `[O]` to appear after `Ctrl-Space`.

   <img width="295" alt="screenshot at 11-10-13" src="https://cloud.githubusercontent.com/assets/721372/11320157/266b409a-9044-11e5-8738-0ed80fd22c4f.png">

2. Same as (1) above after setting

   ```vim
   let g:neocomplete#auto_completion_start_length = 1
   ```

   <img width="289" alt="screenshot at 11-11-56" src="https://cloud.githubusercontent.com/assets/721372/11320163/43647360-9044-11e5-943e-c01cd3b6b1f8.png">

   <img width="303" alt="screenshot at 11-12-16" src="https://cloud.githubusercontent.com/assets/721372/11320175/94cc5088-9044-11e5-9200-eefa00b6c630.png">

3. After setting

   ```vim
   let g:neocomplete#auto_completion_start_length = 2
   if !exists('g:neocomplete#sources#omni#input_patterns')
     let g:neocomplete#sources#omni#input_patterns = {}
   endif
   let g:neocomplete#sources#omni#input_patterns.javascript = '\h\w*\|[^. \t]\.\w*'
   ```

   I only get `[O]` at first.

   <img width="109" alt="screenshot at 11-15-12" src="https://cloud.githubusercontent.com/assets/721372/11320177/b4ff7efc-9044-11e5-9a61-c55f43956c20.png">

   Pressing `Ctrl-Space` adds `[B]` and `[nsnip]`.

   <img width="294" alt="screenshot at 11-41-47" src="https://cloud.githubusercontent.com/assets/721372/11320180/e4e412f4-9044-11e5-8e08-11efca436958.png">

  Typing two letters still works the same.

   <img width="109" alt="screenshot at 11-44-59" src="https://cloud.githubusercontent.com/assets/721372/11320198/63205fe2-9045-11e5-94e9-94c010e28455.png">

   If I type `con` then use `Backspace`, `[B]` and `[nsnip]` will suddenly appear.

   <img width="295" alt="screenshot at 11-43-02" src="https://cloud.githubusercontent.com/assets/721372/11320187/106518ec-9045-11e5-86b4-139d7152871b.png">

4. After setting

   ```vim
   let g:neocomplete#auto_completion_start_length = 1
   if !exists('g:neocomplete#sources#omni#input_patterns')
     let g:neocomplete#sources#omni#input_patterns = {}
   endif
   let g:neocomplete#sources#omni#input_patterns.javascript = '\h\w*\|[^. \t]\.\w*'
   ```

   Now I see all three options.

   <img width="294" alt="screenshot at 11-41-47" src="https://cloud.githubusercontent.com/assets/721372/11320189/16b25a7a-9045-11e5-8925-46e64a9f9c28.png">

**Comment by Shougo** [comment]
They are features.

1, 2: You must change the omni source pattern.  It is not matched by default.

3: The default omni match length is 0, but others is `g:neocomplete#auto_completion_start_length`.
So, omni pattern is matched in the first.

4: The default omni match length is 0, but others is `g:neocomplete#auto_completion_start_length`.
So, they are matched in the same time.
