### ISSUE TITLE
Autocomplete gibberish appears and becomes text upon prepending a word

### ISSUE THREAD

**Issue by apeduru** [Shougo/neocomplete.vim#499]
##Problem Summary
See gif below but some sort of jedi/neocomplete hybrid gibberish appears when I attempt to prepend a word. Whatever appears also becomes permanent text that must be manually deleted afterwards. Occurs on multiple occasions. 

##Minimal Vimrc (including jedi-vim settings)
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_auto_select = 0
let g:neocomplete#enable_underbar_completion = 1
let g:neocomplete#sources#syntax#min_keyword_length = 0
let g:neocomplete#enable_fuzzy_completion = 1
let g:neocomplete#enable_refresh_always = 1
let g:neocomplete#enable_auto_delimiter = 1
let g:neocomplete#max_list = 10

autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS

inoremap <expr> <C-g> neocomplete#undo_completion()
inoremap <expr> <C-l> neocomplete#complete_common_string()
inoremap <expr> <C-h> neocomplete#smart_close_popup()."\<C-h>"

"Cycle through suggestions with tab
inoremap <expr> <TAB> pumvisible() ? "\<C-n>": "\<TAB>"

"On Enter (carriage return) autocomplete highlighted suggestion
inoremap <expr> <CR>  pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>" 

autocmd FileType python setlocal omnifunc=jedi#completions
if !exists('g:neocomplete#force_omni_input_patterns')
	let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

let g:jedi#auto_vim_configuration = 0
let g:jedi#completions_enabled = 0
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#popup_on_dot = 1
let g:jedi#popup_select_first = 1
let g:jedi#show_call_signatures = "1"
if has('python3')
	let g:jedi#force_py_version = 3
endif

##Environment 
OS: Ubuntu 14.04.3 LTS
Vim: 7.4

##Screenshot
![output](https://cloud.githubusercontent.com/assets/8324048/11516563/05d85f3c-9852-11e5-8c4c-a482a7771c3b.gif)

**Comment by Shougo** [comment]
`g:jedi#show_call_signatures` conflicts with neocomplete.
You should disable it.
```vim
let g:jedi#show_call_signatures = "1"
```
I recommend for you to install echodoc.
https://github.com/Shougo/echodoc.vim
