### ISSUE TITLE
Lazy-Loading neocomplete.vim in NeoBundle.vim?

### ISSUE THREAD

**Issue by phongvcao** [Shougo/neocomplete.vim#500]
I am trying to lazy-load `neocomplete.vim` in `NeoBundle.vim` by only enabling `neocomplete.vim` (`:NeoCompleteEnable`) and calling `neocomplete#start_manual_complete()` when `<Tab>` is actually pressed. Right now my `.vimrc` looks something like this:

```vim
NeoBundleLazy 'Shougo/neocomplete.vim', { 'on_cmd' : 'NeoCompleteEnable' }
function EnableAndComplete()
    if !neocomplete#is_enabled()
        :NeoCompleteEnable
    endif
    call neocomplete#start_manual_complete()
endfunction

inoremap <expr><Tab> pumvisible() ? "\<C-n>" : EnableAndComplete()
```

which looks like making sense but doesn't work. Is there anyway to lazy-load `neocomplete.vim` on pressing `<Tab>` using `NeoBundle.vim`?

**Comment by NigoroJr** [comment]
Trying out your snippet, it seems to be working fine for me. There are couple other ways to do it such as:

* `'on_map': '<Tab>'`
* `'on_func': 'neocomplete#start_manual_complete()'`

You'll probably need to call `neocomplete#initialize()` if you use either of the above (someone can correct me if I'm wrong), making it something along the lines of:

```viml
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/neocomplete.vim', {
      \ 'on_map': '<Tab>',
      \ }

inoremap <expr><Tab> pumvisible() ? "\<C-n>" : neocomplete#start_manual_complete()

if neobundle#tap('neocomplete.vim')
  function! neobundle#hooks.on_post_source(bundle)
    call neocomplete#initialize()
  endfunction

  call neobundle#untap()
endif

call neobundle#end()
filetype plugin indent on
```

Note that `NeoBundle` now defaults to lazy-loading. Let me know if this works or not.

**Comment by phongvcao** [comment]
@NigoroJr thank you for your suggestion. I just got it working by changing `call neocomplete#start_manual_complete()` to `return neocomplete#start_manual_complete()` as follow:

```
NeoBundleLazy 'Shougo/neocomplete.vim', { 'on_cmd' : 'NeoCompleteEnable' }
function EnableAndComplete()
    if !neocomplete#is_enabled()
        :NeoCompleteEnable
    endif
    return neocomplete#start_manual_complete() " change 'call' to 'return'
endfunction

inoremap <expr><Tab> pumvisible() ? "\<C-n>" : EnableAndComplete()
``` 

In my previous above code, for some reason my `<C-j>` mapping only puts in `0` which is the return value of `EnableAndComplete()`. Now it will return the return value of `neocomplete#start_manual_complete()` & the auto-completion with lazy-loading is working again. Problem solved!

**Comment by NigoroJr** [comment]
@phongvcao Great! :)
