### ISSUE TITLE
how to use  Fuzzy matching?

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neocomplete.vim#501]
for example:
```java
public class Test{
   this._//here can complete the methons of current class,
//if i want match getClass(),i just need to type gc or any other two char 
//,no need to type all the chars. how to get this func in neocomplete?
}
```

**Comment by wsdjeg** [comment]
![2015-12-03 23-28-55](https://cloud.githubusercontent.com/assets/13142418/11564748/bdc23f0e-9a15-11e5-9f6f-6fec8eb294a3.png)
![2015-12-03 23-29-11](https://cloud.githubusercontent.com/assets/13142418/11564755/c4e74590-9a15-11e5-8071-4013b51dbe8e.png)

**Comment by NigoroJr** [comment]
Are you talking about forcing an omni completion? If so, read the docs on [`g:neocomplete#force_omni_input_patterns`](https://github.com/Shougo/neocomplete.vim/blob/80a65c78989475b59611cd7af37c272986cca563/doc/neocomplete.txt#L444).

**Comment by Shougo** [comment]
Unfortunately, omni completion is not fuzzy.
If you want to get the fuzzy candidates, you should create the deoplete sources.

**Comment by wsdjeg** [comment]
the above the what YCM does for omni

**Comment by wsdjeg** [comment]
i have read it does not work

**Comment by Shougo** [comment]
Hmmm....
YouCompleteMe uses refresh_always feature.
It may support it.  But neocomplete does not use it.

**Comment by wsdjeg** [comment]
this feature is most useful,is there any possiable to support it?

**Comment by Shougo** [comment]
OK.  I will do it.

**Comment by Shougo** [comment]
Implemented.

**Comment by wsdjeg** [comment]
thank you for working so long time at night

**Comment by wsdjeg** [comment]
seems not work
![2015-12-05 08-38-04](https://cloud.githubusercontent.com/assets/13142418/11604762/98e8af3a-9b2b-11e5-92d1-c3a00c4c25dd.png)
![2015-12-05 08-38-23](https://cloud.githubusercontent.com/assets/13142418/11604763/a03f1616-9b2b-11e5-9a8e-a181213514b5.png)
![2015-12-05 08-38-27](https://cloud.githubusercontent.com/assets/13142418/11604764/a74851f2-9b2b-11e5-9440-639a301e2466.png)

**Comment by Shougo** [comment]
Unfortunately, it is feature.
Because, neocomplete uses the previous cache.

**Comment by Shougo** [comment]
In `g:neocomplete#force_omni_input_patterns`, all neocomplete features are disabled.

**Comment by wsdjeg** [comment]
haha i hava found it is really better than YCM,and it can complete more than one source at the same time , i will try to format my setting

**Comment by Shougo** [comment]
> haha i hava found it is really better than YCM,and it can complete more than one source at the same time , i will try to format my setting

Yes, it is my intended behavior from the first time.

**Comment by wsdjeg** [comment]
i wil read the doc to get some useful setting,i want refresh the list after i type BS,and i find it can put the most used result at the top, it is very useful.
after finishing setting i will share it here.

**Comment by wsdjeg** [comment]
strange behavior
after a `this`
i type dot
show me 
![2015-12-05 11-00-12](https://cloud.githubusercontent.com/assets/13142418/11605612/7e678b5e-9b3f-11e5-862e-5d5135b995cd.png)
then i type `wt`
show me 
![2015-12-05 11-00-19](https://cloud.githubusercontent.com/assets/13142418/11605637/1d551a74-9b40-11e5-93bd-e540de68d624.png)
then type BS
![2015-12-05 11-00-39](https://cloud.githubusercontent.com/assets/13142418/11605649/66f4a136-9b40-11e5-8109-dfacab3ae1d4.png)

![2015-12-05 11-00-30](https://cloud.githubusercontent.com/assets/13142418/11605642/355a7eac-9b40-11e5-98f2-eb0d9162ca6b.png)

THE POP will not be refreshed

also if i start a new line the completetion will be the old one
![2015-12-05 11-00-55](https://cloud.githubusercontent.com/assets/13142418/11605659/97bd8904-9b40-11e5-8946-fa49dc4dccf4.png)

**Comment by Shougo** [comment]
Fixed.  Please update neocomplete.

**Comment by wsdjeg** [comment]
here is some diff between neocomplete and origin omnifunc 
![2015-12-05 12-33-02](https://cloud.githubusercontent.com/assets/13142418/11606029/756723ae-9b4c-11e5-9b66-1c5560222855.png)
![2015-12-05 12-33-08](https://cloud.githubusercontent.com/assets/13142418/11606030/81f5ca3a-9b4c-11e5-86ff-e1f05a8680a4.png)
![2015-12-05 12-33-20](https://cloud.githubusercontent.com/assets/13142418/11606031/8208231a-9b4c-11e5-9cac-1ac63bbff660.png)
![2015-12-05 12-33-23](https://cloud.githubusercontent.com/assets/13142418/11606032/8217aac4-9b4c-11e5-941f-47e0458050f5.png)

**Comment by wsdjeg** [comment]
is it due to my vimrc?

**Comment by wsdjeg** [comment]
here is the omni i am using
https://github.com/artur-shaik/vim-javacomplete2

**Comment by Shougo** [comment]
@wsdjeg Please read the issue template.
I don't want to try javacompete2 though....

1st is neocomplete problem.
2nd and 3rd are javacomplete2 problem.  It is direct omni completion call.

**Comment by wsdjeg** [comment]
hi @Shougo only 1st has issue,others works well,i think it is due to neocomplete delete the output of completion ,from the first dot to the end.

**Comment by Shougo** [comment]
Please create minimal .vimrc and reproduce ways.

**Comment by wsdjeg** [comment]
ok ,i will open an new issue base on the issue template

**Comment by Shougo** [comment]
OK.  Please do it.
