### ISSUE TITLE
completion deleted by neocomplet,when the compltion contains dot.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neocomplete.vim#503]
# Problems summary

## Environment Information
 * OS: ubuntu
 * Vim version: 
![2015-12-06 12-30-25](https://cloud.githubusercontent.com/assets/13142418/11611680/2930c322-9c15-11e5-964d-98fcb31d9621.png)

## Minimal vimrc less than 50 lines
```vim
        NeoBundle 'Shougo/neocomplete'
        NeoBundle 'artur-shaik/vim-javacomplete2'
        autocmd FileType java set omnifunc=javacomplete#Complete
        let g:neocomplete#data_directory='~/.cache/neocomplete'
        let g:acp_enableAtStartup = 0
        let g:neocomplete#enable_at_startup = 1
        " Use smartcase.
        let g:neocomplete#enable_smart_case = 1
        let g:neocomplete#enable_camel_case = 1
        let g:neocomplete#enable_ignore_case = 1
        let g:neocomplete#enable_fuzzy_completion = 1
        " Set minimum syntax keyword length.
        let g:neocomplete#sources#syntax#min_keyword_length = 3
        let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

        " Define dictionary.
        let g:neocomplete#sources#dictionary#dictionaries = {
                    \ 'default' : '',
                    \ 'vimshell' : $HOME.'/.vimshell_hist',
                    \ 'scheme' : $HOME.'/.gosh_completions'
                    \ }

        " Define keyword.
        if !exists('g:neocomplete#keyword_patterns')
            let g:neocomplete#keyword_patterns = {}
        endif
        let g:neocomplete#keyword_patterns['default'] = '\h\w*'


        " AutoComplPop like behavior.
        let g:neocomplete#enable_auto_select = 0

        if !exists('g:neocomplete#sources#omni#input_patterns')
            let g:neocomplete#sources#omni#input_patterns = {}
        endif
        let g:neocomplete#sources#omni#input_patterns.java = '[^. *\t]\.\w*\|\h\w*::'
        let g:neocomplete#force_omni_input_patterns = {}
        "let g:neocomplete#force_omni_input_patterns.java = '^\s*'
        inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
        " <C-h>, <BS>: close popup and delete backword char.
        inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
        inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
        inoremap <expr><C-y>  neocomplete#close_popup()
        inoremap <expr><C-e>  neocomplete#cancel_popup()
        inoremap <expr><leader><Tab> neocomplete#start_manual_complete('omni')
```
## Reproducable ways from Vim starting

 1.crate a single Java file 
```java
class Test{
     @Override
      _//here is cursor
}
```
 2.type c-x c-o will show me the methods can be override and complete whole method
 3.but when use neocomple omni source ,the complition will be deleted from first dot to the end 
for example in origin omnifunc
the completion is 
![2015-12-05 12-33-20](https://cloud.githubusercontent.com/assets/13142418/11606031/8208231a-9b4c-11e5-9cac-1ac63bbff660.png)
but in neocomplete only can show me the chars before the first dot
![2015-12-05 12-33-02](https://cloud.githubusercontent.com/assets/13142418/11606029/756723ae-9b4c-11e5-9b66-1c5560222855.png)

## Screen shot (if possible)

**Comment by Shougo** [comment]
Fixed.  Please test it.

**Comment by wsdjeg** [comment]
thanks,it works well,
i think it should be know by @artur-shaik,now the plugin can support Fuzzy matching same as after a dot,
also we can use Fuzzy matching after `@` or at the next line of `@Override`
here is two pic
![2015-12-06 13-46-59](https://cloud.githubusercontent.com/assets/13142418/11611947/1325d5c6-9c20-11e5-88dd-a3cd40986a27.png)
![2015-12-06 13-47-57](https://cloud.githubusercontent.com/assets/13142418/11611946/13236ef8-9c20-11e5-8cc5-28b49059a208.png)
![2015-12-06 13-48-00](https://cloud.githubusercontent.com/assets/13142418/11611948/132a2090-9c20-11e5-853d-0d7353794cb5.png)
![2015-12-06 13-48-23](https://cloud.githubusercontent.com/assets/13142418/11611949/132ba94c-9c20-11e5-9f9d-b67c8c0ee264.png)

**Comment by wsdjeg** [comment]
only litter issue we need match the first char of the output completion ,but i think there must be an option related to it,i think i can find it ,so closing

**Comment by wsdjeg** [comment]
got it
![2015-12-06 14-00-58](https://cloud.githubusercontent.com/assets/13142418/11611989/d5dfea9c-9c21-11e5-9d3c-3aecf1376ae3.png)
