### ISSUE TITLE
Cannot use this plugin 'lua/dyn' 

### ISSUE THREAD

**Issue by rmohta** [Shougo/neocomplete.vim#506]
# Problems summary
Unable to use this plugin with Vim 7.4 on Windows 10. The version shows 'lua/dyn' and not lua. I have encountered the same error when using _vim73-kaoriya-win64_ as referenced in the README.md
## Expected
Plugin to work
## Environment Information
 * OS: Windows 10
 * Vim version: 7.4.965

## Minimal vimrc less than 50 lines

   " Your vimrc
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/neocomplete.vim
set fo+=aw
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
set tw=10 " just for testing purposes

## Reproducable ways from Vim starting

 1. Download installer from https://bintray.com/veegee/generic/vim_x64
 2. Copy the above entries in $HOME/_vimrc
 3. Start gvim.exe or vim.exe

## Error Message during startup
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 11 2015 11:37:42)
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 11 2015 11:37:42)
neocomplete does not work with this version of Vim.
It requires Vim 7.3.885 or later with Lua support ("+lua").

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/4585024/11915039/415eba7a-a652-11e5-9580-87e7cd4765b7.png)

![image](https://cloud.githubusercontent.com/assets/4585024/11915099/488dade0-a654-11e5-8ccf-dad3b22cb1f4.png)

:

**Comment by Shougo** [comment]
Please read the `:version` result.

In Vim 7.3, lua51.dll is needed in the Vim directory.
In Vim 7.4, lua52.dll is needed in the Vim directory.

The lua dlls(64bit) is installed in the Vim directory?
If not, if_lua does not work.  It is not neocomplete issue.

**Comment by Shougo** [comment]
I have tested the veegee's binary and lua52.dll is not installed.
You must install it.

**Comment by chantisnake** [comment]
![capture](https://cloud.githubusercontent.com/assets/10100995/13339725/d20b54bc-dbf8-11e5-8af8-d760ae019e5a.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10100995/13339729/d6953b38-dbf8-11e5-97cb-069c6afd3625.PNG)
I have haed lua52.dll, but it is still not working...

**Comment by chantisnake** [comment]
is there any way that I can troubleshoot this?

**Comment by chantisnake** [comment]
@Shougo

**Comment by wsdjeg** [comment]
it is not an issue about neocomplete,you shou use vim_use mail list

**Comment by UncleBill** [comment]
@chantisnake  Have you try lua53.dll? Maybe yours was compiled with lua 5.3
I use this https://bintray.com/micbou/generic/vim/view and lua53.dll

**Comment by chantisnake** [comment]
@UncleBill Thanks, it is not working for now...

**Comment by Shougo** [comment]
@chantisnake This is not the Q/A site for Vim features...
But some advices are here:

You should check your `:version` output.
If you use 32bit Vim, you need 32bit lua DLL.
If you use 64bit Vim, you need 64bit lua DLL.
You must install dynamic linked Lua version dll.
It is displayed in `:version`.

**Comment by chantisnake** [comment]
i have figured it out. Sorry for wasting your time.

**Comment by wsdjeg** [comment]
> i have figured it out.

great to hear that

**Comment by ereOn** [comment]
@chantisnake Glad you figured it out. Could you share what was wrong for us that aren't so lucky ?

**Comment by chantisnake** [comment]
It really depends on which distribution of vim that you are using.

I uses vim-tux, it works with lua53 dll.

You can install both of them via Choco

‵‵‵
choco install vim-tux
choco install lua53
‵‵‵
