### ISSUE TITLE
completion order

### ISSUE THREAD

**Issue by chuan137** [Shougo/neocomplete.vim#507]
# Completion order inconsistent

## Environment Information
 * OS:
 * Vim version:

## Minimal vimrc less than 50 lines

```
set runtimepath+=~/.vim/b/neobundle.vim/
call neobundle#begin(expand('~/.vim/b/'))
"{{{
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/vimproc.vim', {'build': {'mac': 'make', 'unix': 'make'}}
NeoBundle 'Shougo/neocomplete.vim', {
      \ 'depends' : ['Shougo/context_filetype.vim', 'Shougo/neco-vim', 'Shougo/neco-syntax'],
      \ }

if neobundle#tap('neocomplete.vim')
  let g:neocomplete#enable_at_startup=1
  function! neobundle#tapped.hooks.on_source(bundle)
    let g:neocomplete#enable_fuzzy_completion = 1
    let g:neocomplete#max_list = 20
    let g:neocomplete#sources = {}
    let g:neocomplete#sources._ = ['file', 'omni', 'buffer', 'syntax']
    let g:neocomplete#sources.vim = g:neocomplete#sources._ + ['vim']
  endfunction
  call neobundle#untap()
endif

"}}}
call neobundle#end()
filetype plugin indent on
NeoBundleCheck
```
## Reproducable ways from Vim starting

If I type *neobundle*, the top items in matching list are

    NeoBundleUpdate
    NeoBundleReinstall
    NeoBundleRecipe 
    ...
    ...
    NeoBundle

The exact matching **NeoBundle** is a lot deeper in the list.
However when I backspace deleting a character, the order of the list suddenly changes and "NeoBundle" pop to the top. How are the orders of matching items decided?

Thanks

**Comment by wsdjeg** [comment]
maybe it is due to `match_head`

if you type into Neobundle i think the NeoBundle will be the first one

**Comment by chuan137** [comment]
what is match_head? did not find it in doc.

And when I type Neobundle, it is the same

**Comment by chuan137** [comment]
Ok, I update my mini vimrc and tested it. I found

~~let g:neocomplete#enable_fuzzy_completion = 1~~

and

let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_camel_case = 1

makes the behaviour expected. It seems fuzzy completion is not very consistent.

**Comment by Shougo** [comment]
@chuan137 It is matcher_head.

> The exact matching NeoBundle is a lot deeper in the list.

This is feature.  Because, it is not sorted.

If you press "ne", neocomplete creates candidates and sort them.
But if you press "neobundle...", neocomplete functions are not called.
So they are not sorted.

> However when I backspace deleting a character, the order of the list suddenly changes and "NeoBundle" pop to the top. How are the orders of matching items decided?

Because, if you press `<BS>`, neocomplete re-creates the candidates and sorts them.

**Comment by Shougo** [comment]
@chuan137 I have added `g:neocomplete#enable_refresh_always` feature.
You can enable it.

**Comment by chuan137** [comment]
awsome, I will try it out
