### ISSUE TITLE
LaTeX: start file name completion for \includegraphics

### ISSUE THREAD

**Issue by huesersohn** [Shougo/neocomplete.vim#509]
Is it possible to get file name completion for LaTeX commands like `\includegraphics` etc.? Using vimtex I get completion for `\cite` and `\ref` after typing `{` and would like typing `\includegraphics{` to trigger file name completion. I asked [there](https://github.com/lervag/vimtex/issues/308) first, but lervag said I should open an issue with neocomplete. Does the file name source provide any means to configure when it starts completion?

**Comment by Shougo** [comment]
It is just omni pattern problem.
