### ISSUE TITLE
we should not use neopairs.vim and neosnippet.vim together.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neocomplete.vim#510]
hi @Shougo I find if I install neopairs.vim .the feature of auto expand args provided by neosnippet will not work ,I think this shoud be add into doc

**Comment by Shougo** [comment]
Why did you created it in neocomplete.vim?

I have added it in neosnippet doc.

**Comment by wsdjeg** [comment]
oh, sorry, I just am thinking all of them are your plugin.
