### ISSUE TITLE
feature: set 'mark' when using multiple omnifunc

### ISSUE THREAD

**Issue by davidosomething** [Shougo/neocomplete.vim#512]
If you define multiple omnifunc

```
  let g:neocomplete#sources#omni#functions.javascript = [
        \   'javascriptcomplete#CompleteJS',
        \   'tern#Complete',
        \ ]
```

They are all marked as [O]

Is there an easy way to change the mark, e.g.

```
  let g:neocomplete#sources#omni#functions.javascript = [
        \   'javascriptcomplete#CompleteJS',
        \   'tern#Complete': { 'mark': 'TernJS' }
        \ ]
```

so the PUM shows

```
omniItem    [O]
ternItem    [TernJS]
```

'rank' would also be useful to add to make configuration easier, so you can prioritize omnifuncs

**Comment by Shougo** [comment]
Unfortunately, rejected.
I think this feature is not useful.

> 'rank' would also be useful to add to make configuration easier, so you can prioritize omnifuncs

You can prioritize them by the array order.
