### ISSUE TITLE
complete_common_string() doesn't work

### ISSUE THREAD

**Issue by dominickng** [Shougo/neocomplete.vim#514]
After commit 20ed0a1bffa85c5a29cd12f106818134cd0ff590, complete_common_string() doesn't seem to do anything. I have the following mapping in my vimrc:

```
   set nocompatible

   set runtimepath+=~/path/to/neocomplete.vim/

  set fo+=aw
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_auto_select = 0
  set tw=10 " just for testing purposes

  inoremap <expr><Tab>
    \ neocomplete#complete_common_string() != '' ?
    \   neocomplete#complete_common_string() :
    \ pumvisible() ? "\<C-n>" : "\<TAB>"
```

Prior to 20ed0a1bffa85c5a29cd12f106818134cd0ff590, this command would complete common string if one was present, and otherwise advance through the completion menu or insert a tab. Now, it does nothing. Should I modify the command in some way?

## Reproduce

Using Vim 7.4.899 on Linux.

1. type a long word
2. try to type it again. completion menu should pop up
3. press tab. it should auto complete

It doesn't auto complete.

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by dominickng** [comment]
To be more explicit, all you need to do is put the mapping I provided into the dummy file in the template and try and trigger a completion....

**Comment by Shougo** [comment]
Fixed.

**Comment by dominickng** [comment]
Thanks!
