### ISSUE TITLE
Omni completion not triggered by g:neocomplete#sources#omni#input_patterns

### ISSUE THREAD

**Issue by wilywampa** [Shougo/neocomplete.vim#515]
Since https://github.com/Shougo/neocomplete.vim/commit/33ef6422753f469bdebfa23184b02a05b348cb33 omni completion is sometimes not starting automatically. The problem occurs if the popup menu was visible before typing a character that matches `g:neocomplete#sources#omni#input_patterns` (and in other cases, but that's the most repeatable).

The expected behavior is for neocomplete so suggest omni completion items after typing a `.`. Instead, nothing happens. I'm seeing the same problem with two unrelated omni functions (clang_complete and jedi-vim).

Here's an example where it doesn't work when the popup menu is visible (after typing `vector.`) but does work without the menu visible (after typing `v.`). Backspacing and entering the `.` again makes the omni completions show up.

![neocomplete](https://cloud.githubusercontent.com/assets/4472522/12383745/cbf6b1d0-bd66-11e5-9b85-17fe1f534700.gif)

I'm using Vim 7.4.909 with this .vimrc:
```vim
set nocompatible hidden backspace=indent,eol,start
set history=5000 undofile undolevels=1000 undoreload=10000
filetype plugin on
syntax enable

let g:neocomplete#sources#omni#input_patterns = {'cpp':
            \ '\([^.[:digit:] *\t]\|\w\d\)\%(\.\|->\)\w*\|\h\w*::\w*'}
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_use_library = 1
let g:clang_make_default_keymappings = 0
let g:clang_library_path = '/Library/Developer/CommandLineTools/usr/lib'
let g:neocomplete#enable_at_startup=1

silent! if plug#begin('$HOME/.vim_sandbox_plugged')
Plug 'Shougo/neocomplete.vim'
Plug 'Rip-Rip/clang_complete'
call plug#end()
endif
```

**Comment by Shougo** [comment]
Fixed.
