### ISSUE TITLE
Slow NeoCompleteClean

### ISSUE THREAD

**Issue by felixSchl** [Shougo/neocomplete.vim#516]
I experienced vim taking a long time to shut down, sometimes not so bad, other times up to the point where I had to close the tmux pane because it became completely unresponsive. So, whenever I remebered to, I would exit vim using `:10verbose qal` to see what was going on and it was in all cases where vim was slow that the last line was related to cleaning, calling some neocomplete clean command `s:clean`. Now, when I start a fresh session and just run `:NeoCompleteClean`, I experienced the same lag, but once it was finished, successive calls where fast. I ran the command with `20verbose`, so I could see what's happening. The lines that it spends most time on, repeatedly over and over again, are these IO operations: https://github.com/Shougo/neocomplete.vim/blob/5adbcdccea200b83b1145378e49600758e227e32/autoload/neocomplete/commands.vim#L64-L66
I wonder if we can reduce these by putting in a directory and just removing the entire directory? Granted, I have not had the exposure and there's probably reason to the `isdirectory` check, but a simple file system unlink on a single directory is going to be way faster than globbing, stating and deleting hundreds of files.

**Comment by Shougo** [comment]
Fixed.

**Comment by felixSchl** [comment]
ace, thanks!

**Comment by svermeulen** [comment]
Nice!  This fixes it for me too.
