### ISSUE TITLE
<Cr> can not close popupmene

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neocomplete.vim#518]
![2016-01-31 08 54 52](https://cloud.githubusercontent.com/assets/13142418/12699506/70988b28-c7f8-11e5-8a4b-1cb575273f96.png)
even if I exec `:inoremap <cr> <c-y>`

**Comment by wsdjeg** [comment]
but the popupmenu can be closed by type `<c-y>` directly,I think maybe it is due to how my terminal send `ctrl`.
also type `<exc>`, `a`,the popupmenu will aotuopen

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
will try again,thanks a lot
