### ISSUE TITLE
Won't complete with multibyte characters

### ISSUE THREAD

**Issue by lervag** [Shougo/neocomplete.vim#519]
Hi Shougo. I'm using neocomplete to autocomplete omni sources from vimwiki. It works generally very well, but I've found a case where things don't work as expected: multibyte characters. I've enabled the option and defined the input_pattern correctly, and I've done some debugging to try to find what is happening. First, an example:

I have a vimwiki file called: `test-æøå-letters.wiki`, as well as `test-oea-letters.wiki`. The omni complete for vimwiki returns corresponding files for the pattern `\[\[\S*`, for instance, if I type: `[[test`, then neocomplete correctly shows both the file names for completion. If I now continue with `æ`, then the completion stops with no candidates.

I've found that this happens because `s:use_previous_result(...)` returns 0. However, I think it should not return 0 in this case, as there should not be a reason to recalculate candidates in this case. In particular, the recalculation will fail because the current string is now `[[testæ`, and so the omnifunc will no longer find any matches.

In particular, these lines enforce the recalculation:

```vim
        \ && substitute(a:context.input, '\w\+$', '', '')
        \    ==# substitute(a:context.prev_line, '\w\+$', '', '')
```

Because `\w` only matches `[0-9A-Za-z_]`.

**Comment by lervag** [comment]
I'm curious: What is this particular test supposed to do? Could one use `\S\+$` instead of `\w\+$`?

**Comment by lervag** [comment]
Oh, and sorry: I spent some time reading your source code to understand this issue: I very much like your style of coding!

**Comment by Shougo** [comment]
OK.  Fixed.

**Comment by lervag** [comment]
Great, thanks!
