### ISSUE TITLE
Variable for whether text in popup is selected or not

### ISSUE THREAD

**Issue by dhalima3** [Shougo/neocomplete.vim#521]
# Problems summary
I want to differentiate the behavior of enter <CR> when the text is selected or not.  

For example when I press enter in the situation below, I will be on the next line (which is expected with the configuration I have.)

### Before <CR>
![image](https://cloud.githubusercontent.com/assets/546242/13200016/03bf5a4a-d806-11e5-8c96-2ffd6d646d2f.png)

### After <CR>
![image](https://cloud.githubusercontent.com/assets/546242/13200019/0c574668-d806-11e5-9cb0-25015ff29440.png)

In the next situation, when the first word in the popup is selected and I press enter, I am expecting "management," but I am only getting the text that I type in before I press enter.  

### Before <CR>
![image](https://cloud.githubusercontent.com/assets/546242/13200023/266fba12-d806-11e5-8521-768f4d9f5db9.png)

### After <CR>
![image](https://cloud.githubusercontent.com/assets/546242/13200024/31a9db7e-d806-11e5-97e4-ed69df3163a3.png)

### Expected After <CR>
![image](https://cloud.githubusercontent.com/assets/546242/13200033/6b01c0a8-d806-11e5-93ff-efdbadc6e6df.png)

To handle these 2 cases appropriately, I am wondering if there's a variable I can use to tell whether or not a selection in the popup has been made or not.  I have tried looking in the documentation but can't find if this exists or not.  

## Environment Information
 * OS: Mac OS X
 * Vim version: Vim 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
" <CR> close popup and save indent or expand snippet
function! CleverCr()
    if pumvisible()
        if neosnippet#expandable()
            let exp = "\<Plug>(neosnippet_expand)"
            return exp . neocomplete#smart_close_popup()
        else
            return neocomplete#smart_close_popup() . "\<CR>"
        endif
    else
        return "\<CR>"
    endif
endfunction
" <CR> close popup and save indent or expand snippet
imap <expr> <CR> CleverCr()
" Tab completion (shift Tab for going backwards) for Neocomplete
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<TAB>"
" <Down> and <Up> cycle like <Tab> and <S-Tab>
inoremap <expr> <Down>  pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>    pumvisible() ? "\<C-p>" : "\<Up>"
" <ESC> takes you out of insert mode and also gets rid of suggestions window
inoremap <expr> <Esc>   pumvisible() ? "\<C-y>\<Esc>" : "\<Esc>"
" Cap maximum suggestions
let g:neocomplete#max_list = 15

" Neosnippet
" Enable snipmate compatibility mode
let g:neosnippet#enable_snipmate_compatibility = 1
" Tell Neosnippet about the other snippets
let g:neosnippet#snippets_directory='~/.vim/bundle/vim-snippets/snippets'
" Plugin key-mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
imap <expr><TAB> pumvisible() ? "\<C-n>" :
 \ neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

```

**Comment by wsdjeg** [comment]
please read doc
```vim
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
	function! s:my_cr_function()
	  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
	  " For no inserting <CR> key.
	  "return pumvisible() ? "\<C-y>" : "\<CR>"
	endfunction
```

**Comment by wsdjeg** [comment]
and 
```doc
neocomplete#smart_close_popup()
		Insert candidate and re-generate popup menu for neocomplete.
		Unlike |neocomplete#close_popup()|, this function changes
		behavior by |g:neocomplete#enable_auto_select| smart.
		Note: This mapping is conflicted with |SuperTab| or |endwise|
		plugins.
		Note: This key mapping is for <C-h> or <BS> keymappings.
		You should not use it for <CR>.
```

**Comment by dhalima3** [comment]
Ah thank you.  <silent> is what I'm looking for.
