### ISSUE TITLE
Smart/camel case completion uses the wrong case

### ISSUE THREAD

**Issue by dominickng** [Shougo/neocomplete.vim#522]
# Problems summary

With smart case completion enabled and a complete_common_string / complete mapping on <TAB>, neocomplete will prompt for a smart-case completion when you type the lower case variant of a word. This is expected. However, when you <TAB> to insert the completion, it is inserted as lower case.

## Expected

The smart-case completion should be inserted, not the lower case one (see reproduce steps)

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: 7.4.899

## Provide a minimal .vimrc with less than 50 lines (Required!)

```
set nocompatible      
set runtimepath+=~/path/to/neocomplete
                                                                               
set fo+=aw
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
let g:neocomplete#enable_smart_case = 1
set tw=10

inoremap <expr><Tab>
\ neocomplete#complete_common_string() != '' ?
\   neocomplete#complete_common_string() :
\ pumvisible() ? "\<C-n>" : "\<TAB>"
```

## The reproduce ways from Vim starting (Required!)

 1. In Insert mode, type `CamelCaseVariant`
 2. Press Enter a few times. Type `camelca` until the completion menu appears. Note that `CamelCaseVariant` is in the menu (from smart case)
 3. Type `<TAB>` to complete. Note that `camelcasevariant` is inserted, instead of `CamelCaseVariant`

**Comment by Shougo** [comment]
Fix.
