### ISSUE TITLE
Complete Option Priorities

### ISSUE THREAD

**Issue by amadeus** [Shougo/neocomplete.vim#524]
This is not so much a bug, however I can't figure out how to solve this issue based on the docs.

I would like options coming from the buffer itself to be a higher priority than other input source. Here's an example screenshot, where the completion options that include values from my current document, appear at the bottom of the completion list:

![example](https://dl.dropboxusercontent.com/s/qnjjh825j3qp4xv/file.js_2016-03-07_14-56-44.png?dl=0)

How can I make these appear at the top of the list?

**Comment by Shougo** [comment]
Please read the documentation...
`:help neocomplete-source-attribute-rank`

```vim
call neocomplete#custom#source('buffer', 'rank', 1000)
```
