### ISSUE TITLE
Foldmethod check invasive/crippling

### ISSUE THREAD

**Issue by toejough** [Shougo/neocomplete.vim#526]
# Problems summary
In a python file, neocomplete pops up a foldmethod error every time it is triggered.  Every single time.  You have to hit 'enter' three times to get past it, and then the next thing you type that triggers neocomplete triggers the foldmethod error again.

This has made neocomplete unusable for me.

## Expected

A one-time error (maybe even one-time per file, or per vim instance) is sufficient to let me know that neocomplete thinks I should be doing things differently.  I expect that if I move through an error message like this once, I am not reprompted for a while.

It's also not obvious why neocomplete cares about my foldmethod, so generally, I don't expect to see this error message at all.

## Environment Information
 * OS: OSX - 10.11.3
 * Vim version: 
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 10 2016 10:48:49)
MacOS X (unix) version
Included patches: 1-1525
Compiled by Homebrew
Huge version without GUI.
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

I use spf13-vim.  This is reproducible without any additional config.

## The reproduce ways from Vim starting (Required!)

 1. start vim with a new python file
 2. enter insert mode
 3. type something that triggers neocomplete (such as `"""`)

## Screen shot (if possible)
![screen shot 2016-03-11 at 10 36 06 am](https://cloud.githubusercontent.com/assets/5317312/13707393/6aaeaa64-e777-11e5-9095-247c358ddb48.png)

![screen shot 2016-03-11 at 10 36 22 am](https://cloud.githubusercontent.com/assets/5317312/13707392/6aacdf2c-e777-11e5-8386-6650a75947d2.png)

![screen shot 2016-03-11 at 10 35 47 am](https://cloud.githubusercontent.com/assets/5317312/13707394/6ab09ec8-e777-11e5-9a05-433ca37b7edf.png)

## Upload the log messages by `:redir` and `:message`

`:redir` produced an 'invalid argument' error

`:message` produced:

![screen shot 2016-03-11 at 10 54 05 am]
(https://cloud.githubusercontent.com/assets/5317312/13707450/ab8c56bc-e777-11e5-8cc0-d43e8cd86c13.png)

## Other
I also opened an issue for this with [spf31-vim](https://github.com/spf13/spf13-vim/issues/901).

**Comment by asvc** [comment]
Very recently I've started receiving `[neocomplete] foldmethod = "expr" is detected` error while NeoComplete is used with [SimplyFold](https://github.com/tmhedberg/SimpylFold). Looks like this:

<img width="723" alt="screen shot 2016-03-12 at 00 15 40" src="https://cloud.githubusercontent.com/assets/300146/13708128/e9db7982-e7e7-11e5-909b-dc39e947c087.png">

**Comment by Shougo** [comment]
> It's also not obvious why neocomplete cares about my foldmethod, so generally, I don't expect to see this error message at all.

https://github.com/Shougo/neocomplete.vim/issues/525

Please see the problem.

**Comment by Shougo** [comment]
Fixed.  It should be once.

**Comment by asvc** [comment]
Still there:

<img width="882" alt="screen shot 2016-03-12 at 11 23 37" src="https://cloud.githubusercontent.com/assets/300146/13720481/f3d545c8-e844-11e5-945f-3daef1b019f4.png">

**Comment by Shougo** [comment]
The check is still needed.
Please read https://github.com/Shougo/neocomplete.vim/issues/525

**Comment by asvc** [comment]
Understood, thank you.
