### ISSUE TITLE
Errors on 7.4.1577+

### ISSUE THREAD

**Issue by starwing** [Shougo/neocomplete.vim#531]
neocomplete errors on 7.4.1577+, see screenslots.
directly in Vim, press i and press <ESC>, has errors.

![20160316203642](https://cloud.githubusercontent.com/assets/114483/13812407/f28584a6-ebb6-11e5-88c6-dcac29b1590a.jpg)

**Comment by k-takata** [comment]
It's a bug of Vim: vim/vim#690, vim/vim#691

**Comment by Shougo** [comment]
I cannot reproduce the error in Vim 7.4.1583.
It is the Vim bug.
