### ISSUE TITLE
Sluggish completion after `set dict`

### ISSUE THREAD

**Issue by lifepillar** [Shougo/neocomplete.vim#533]
# Problems summary

Completion is very sluggish if I source a file that sets `dictionary` before starting to type anything. If I source such a file after I have modified the buffer, then the dictionary is not considered for completion (and Neocomplete is not sluggish).

## Expected

Smooth and swift completion under all circumstances.

## Environment Information
 * OS: OS X
 * Vim version: 7.4.1655

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath+=~/path/to/neocomplete.nvim/
let g:neocomplete#enable_at_startup = 1
```

You also need a `test.vim` file with the following content:

```
setl dict=/usr/share/dict/words
```

## The reproduce ways from Vim starting (Required!)

 1. `vim -u minimal-vimrc`
 2. `:so test.vim`.
 3. Enter Insert mode and start typing. Neocomplete hangs for a while, apparently searching the dictionary. After a while, dictionary completions appear.

Try also this:

1. `vim -u minimal-vimrc`.
2. Modify the buffer somehow.
3. `:so test.vim`.
4. Enter Insert mode and start typing. Neocomplete is not slow, but it uses only buffer completion, not the dictionary.

**Comment by Shougo** [comment]
You should install vimproc.
It makes cache the dictionary asynchronous.

> Enter Insert mode and start typing. Neocomplete is not slow, but it uses only buffer completion, not the dictionary.

You can execute `:NeoCompleteDictionaryMakeCache` command.

**Comment by lifepillar** [comment]
>You should install vimproc.

Ok, I will try.

>You can execute `:NeoCompleteDictionaryMakeCache` command.

Thanks, that works.
