### ISSUE TITLE
Don't show misspelled and deleted words

### ISSUE THREAD

**Issue by nicknikolov** [Shougo/neocomplete.vim#534]
## Problem summary
I sometimes misspell stuff and delete it right after. Neocomplete however remembers those words and keeps them alive. In the screenshot you can see how I misspelled length a few times and it keeps suggesting me those mistakes. Can I somehow get rid of those suggestions (those words are nowhere in my code)

## Screenshot 

![screen shot 2016-04-05 at 19 25 25](https://cloud.githubusercontent.com/assets/1440420/14293390/58a03120-fb64-11e5-9658-329812b7580c.jpg)

**Comment by Shougo** [comment]
You can re-make cache by `NeoCompleteMemberMakeCache`.

**Comment by nicknikolov** [comment]
Thanks!
