### ISSUE TITLE
emmet-vim and NeoCommenter issue

### ISSUE THREAD

**Issue by asins** [Shougo/neocomplete.vim#535]
# Problems summary

I installed the emmet-vim and NeoComplete. There was a problem when you press ctrl+n after completion snippet ctrl+y+, completion words, bug the outcome is not what I want.

## Expected

e.g.  in xx.html file:

1. `tab<cursor>`   press `ctrl+n` NeoComplete Completion Code : `table<cursor>`
![emmet-vim-neocommenter](https://cloud.githubusercontent.com/assets/898354/14282429/e031f7b6-fb70-11e5-9100-8015ff4b6053.png)
2. press `ctrl+y+,` emmet-vim completion snippet, Output: `<tab><cursor></tab>`. 

I thought it would be `<table><cursor></table>`, but results were not, **why?**

I do not know if this is the problem of emmet-vim or NeoComplete, sorry!

## Environment Information
 * OS: OS X 10.11.4
 * Vim version:  7.4   Included patches: 1-1707  

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
Plug 'mattn/emmet-vim', { 'for': [ 'css', 'html', 'less', 'sass', 'scss', 'xml', 'xsd', 'xsl', 'xslt', 'mustache' ] }
"   Emmet-Vim {{{2
let g:user_emmet_settings = {
\    'variables' : {
\        'lang' : 'zh-cn',
\    },
\    'html' : {
\        'expandos' : {
\            'ol': 'ol>li',
\            'list': 'ul>li*3',
\        },
\        'filters' : 'html',
\        'default_attributes': {
\            'a': {'href': ''},
\            'link': [{'rel': 'stylesheet'}, {'href': ''}],
\        },
\    }
\ }
"   }}}

Plug 'Shougo/neocomplete.vim'
"   NeoComplete {{{2
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Use camel case completion.
let g:neocomplete#enable_camel_case = 1
" Use fuzzy completion.
let g:neocomplete#enable_fuzzy_completion = 1
" 设置缓存目录
let g:neocomplete#data_directory = s:get_cache_dir("neocomplete")
let g:neocomplete#enable_auto_delimiter = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
" Set auto completion length.
let g:neocomplete#auto_completion_start_length = 2
" Set manual completion length.
let g:neocomplete#manual_completion_start_length = 0
" Set minimum keyword length.
let g:neocomplete#min_keyword_length = 3
" buffer file name pattern that disables neocomplete.
let g:neocomplete#sources#buffer#disabled_pattern = '\.log\|\.log\.\|.*quickrun.*\|\.cnx\|Log.txt\|\.user.js'
" buffer file name pattern that locks neocomplete. e.g. ku.vim or fuzzyfinder
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*\|\*unite\*\|Command Line'
let g:neocomplete#sources#buffer#cache_limit_size = 300000
let g:neocomplete#fallback_mappings = ["\<C-x>\<C-o>", "\<C-x>\<C-n>"]

" <TAB>: completion.
" inoremap <expr><TAB>  pumvisible() ? '<C-n>' : '<TAB>'
"   }}}
```

## The reproduce ways from Vim starting (Required!)

Nothing

## Screen shot (if possible)
![test2](https://cloud.githubusercontent.com/assets/898354/14414934/48e5992a-ffcc-11e5-9621-1f0740c2ed98.gif)

press `tab`，select `table`, when press `Ctrl+y+,` output not `<table>...</table>`, is `<tab></tab>`, Why?

## Upload the log messages by `:redir` and `:message`

i ask [emmet-vim issuse](https://github.com/mattn/emmet-vim/issues/325), say need close popup window~

**Comment by Shougo** [comment]
This is emmet-vim feature.
You must close popup menu to use emmet-vim.

**Comment by asins** [comment]
add config in my vimrc. more needs one step, bug then solve the problem.

```vim
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
	return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
```

By the way, the method of the README.md to the configuration will not solve the problem.
```vim 
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? "\<C-y>" : "\<CR>"
endfunction
```

Because emmit-vim at the beginning of using C-y shortcut keys, so the set delay.
