### ISSUE TITLE
[neocomplete] You should disable it or install FastFold plugin.

### ISSUE THREAD

**Issue by Erichain** [Shougo/neocomplete.vim#536]
I just set this plugin as the README said.

But when I start to edit a file, it will show this warning.

**[neocomplete] You should disable it or install FastFold plugin.**

This is the configuration in my `.vimrc`.

```vim
" Auto complete plugin setup
"let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
"let g:neocomplete#enable_smart_case = 1
   
" Setup for gitgutter
let g:gitgutter_enabled = 1
let g:gitgutter_sign_column_always = 1
let g:gitgutter_max_signs = 500
let g:gitgutter#signs_enable = 1
   
" Set the delay of changes
set updatetime=250
```

**This is my system info**

 * OS: OS X EI Capitan
 * Vim version: 7.4.1525

> I am so sorry that I really don't know how to reproduce this issue in your vim:(

**Comment by Shougo** [comment]
```
Q: Freeze for a while and close opened folding when I begin to insert.
https://github.com/Shougo/neocomplcache.vim/issues/368

A: I think you use 'foldmethod' is "expr" or "syntax". It is too heavy to use
neocomplete (or other auto completion.) You should change 'foldmethod'
option or install FastFold plugin.

https://github.com/Konfekt/FastFold
```

**Comment by Erichain** [comment]
Thank you, I will have a try later.

**Comment by HustLion** [comment]
I've install `Konfekt/FastFold` but the error still shows, how can I deal disable the warning?

I configured this:

```
Plug 'https://github.com/plasticboy/vim-markdown'
Plug 'konfekt/fastfold'
nmap zuz <Plug>(FastFoldUpdate)
let g:fastfold_savehook = 1
let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']
let g:markdown_folding = 1
let g:fastfold_force = 1
```

**Comment by Shougo** [comment]
I have removed foldmethod detection.

> I've installed Konfekt/FastFold but the error still shows, how can I disable the warning?

But you should know your foldmethod is expr or syntax and it is too slow for auto completion.

**Comment by HustLion** [comment]
@Shougo Thanks for your quick reply. I was using [vim-markdown](https://github.com/plasticboy/vim-markdown) and I wanted to use its feature of automatic folding by header level, so I guess the syntax fold method is inevitable for this use case.
