### ISSUE TITLE
How can i combine it with clang_complete??

### ISSUE THREAD

**Issue by OsmanthusTree** [Shougo/neocomplete.vim#537]
# Problems summary
I want neocomplete to combine with clang_complete so that clang_complete will not be 
triggered manually any more ( and I hate YouCompleteMe because it is too heavy )

## Environment Information
 * OS:ArchLinux
 * Vim version:7.41689

**Comment by Shougo** [comment]
You should use vim-marching.
https://github.com/osyo-manga/vim-marching
