### ISSUE TITLE
Installation instruction says to install into ~/.vim, not ~/.vim/bundle

### ISSUE THREAD

**Issue by ijt** [Shougo/neocomplete.vim#538]
The installation instructions say to put neocomplete.vim in the wrong place: ~/.vim. That doesn't work. Putting it into ~/.vim/bundle works.

**Comment by Shougo** [comment]
This is the normal plugin installation process.
I recommend to use the plugin managers though.

`:help plugin`

**Comment by Shougo** [comment]
> The installation instructions say to put neocomplete.vim in the wrong place: ~/.vim. That doesn't work. Putting it into ~/.vim/bundle works.

This is your environment problem.  I don't know why...
