### ISSUE TITLE
終了時のキャッシュチェックをオプションにできないでしょうか？

### ISSUE THREAD

**Issue by yama-ver2** [Shougo/neocomplete.vim#539]
こんにちは。
不具合ではなく要望寄りの報告ですみません。

neocompleteを利用していて、Vimの終了に3秒ほどかかるようになっていたのでやや不便に感じていました。
調べたところ、bufferやtagソースなどで、終了時にautocmdでキャッシュのチェックを行っており、キャッシュが5000ファイルほど溜まった結果、上のような状態になっていました。
キャッシュを削除した後はすぐ終了するようになりました。

`neocomplete#helper#clean`を見ると、キャッシュファイルをスキャンして、元ファイルが削除されていたらキャッシュを削除するようですが、これは終了時に毎回行うのは少しコストが高くないでしょうか？

私はあまり不要なファイルアクセスをしてほしくないので、

```vim
au! VimLeavePre * au! neocomplete VimLeavePre
```

で終了時の処理を無効にしてしまっていますが、標準で有効性を選択できるオプションがあるか、もしくは、自動キャッシュチェックのタイミングを数日に1回などにできればありがたいです。

Windows 10 Home 32-bit
kaoriya Vim 7.4.1721

**Comment by Shougo** [comment]
確かに無意味だったので削除しました。

**Comment by yama-ver2** [comment]
ありがとうございます。
キャッシュを溜め込んでも終了が重くなる心配がなくなりました。
