### ISSUE TITLE
Increasing completion time

### ISSUE THREAD

**Issue by kazufukurou** [Shougo/neocomplete.vim#541]
# Problems summary
After each save of buffer changes completion become more laggy. Also number of completion variants decreases.

## Expected
Completion time should be stable.

## Environment Information
 * OS: Linux
 * Vim version: 7.4.1814

I use 2 tag files:
~/.vim/tags (size 1.9Mb)
~/repos/project/tags (size 24kb)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
execute pathogen#infect()
Helptags
syntax on
filetype plugin indent on

set tags+=~/.vim/tags
call neocomplete#custom#source('buffer', 'disabled', 1)
let g:neocomplete#enable_debug = 1
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#skip_auto_completion_time = 0.3
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#sources#tags#cache_limit_size=2000000
```

## The reproduce ways from Vim starting (Required!)
 1. open a file
 2. change something using completion
 3. save
 4. repeat 2,3

## Upload the log messages by `:redir` and `:message`
when vim just started
```
'cur_text =         button.se'
'start get_complete_sources'
0.001440
'tag'
0.058854
'dictionary'
0.059249
'member'
0.124991
```
and after a while
```
'cur_text =         button.se'
'start get_complete_sources'
0.001418
'tag'
1.210760
'Skipped.'
1.744978
```

**Comment by Shougo** [comment]
Please install vimproc plugin.

https://github.com/Shougo/vimproc.vim

**Comment by kazufukurou** [comment]
It didn't resolve the issue. Does it make popup completion asynchronous? Also I noticed vim RAM usage increase after each buffer save.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim
