### ISSUE TITLE
[neocomplete] Vim(let):E121: Undefined variable: words

### ISSUE THREAD

**Issue by chacken** [Shougo/neocomplete.vim#542]
# Problems summary
Getting error "undefined variable: words" when typing . after a package variable name

## Expected
list of functions

## Environment Information
 * OS: OSX El Capitan
 * Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  4 2016 17:30:35)
MacOS X (unix) version
Included patches: 1-1816
Compiled by _spotlight@Traviss-Mac-369.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+channel         -gettext         +netbeans_intg   +timers
+cindent         -hangul_input    +odbeditor       +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +transparency
+cmdline_compl   +job             +perl/dyn        +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
+farsi           +mouse_netterm   +tag_binary

## Provide a minimal .vimrc with less than 50 lines (Required!)

```
call pathogen#infect()

filetype plugin on

let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

syntax enable
set nocompatible
set tabstop=2
set expandtab
syn on
set hls
set nu
set cursorline
set showtabline=2
set textwidth=80
set ml

nmap ,, :tabnew<CR>
nmap ,. :tabnext<CR>
nmap ., :tabpre<CR>

map <leader>t :FufFile<CR>

set wildmode=list:longest
set shortmess=atI
set mouse=a
match ErrorMsg '\%>80v.\+'

colorscheme molokai

set t_Co=256
```

## The reproduce ways from Vim starting (Required!)

`package main

import (
	"errors"
	"fmt"
	"github.com/labstack/echo"
	"io/ioutil"
	"time"
)

func main() {
	e := echo.
}`
 1. type echo
2. type .
3. error

## Screen shot (if possible)
https://www.dropbox.com/s/u5ghik5zn4jv1q9/Screenshot%202016-05-06%2012.29.48.png?dl=0

## Upload the log messages by `:redir` and `:message`
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"server.go" 13L, 120C
[neocomplete] Error occurred calling omnifunction: go#complete#Complete
[neocomplete] function neocomplete#handler#_do_auto_complete[48]..neocomplete#complete#_ge
t_results[23]..neocomplete#complete#_set_results_words[25]..23[1]..<SNR>74_set_complete_re
sults_words, line 11
[neocomplete] Vim(let):E121: Undefined variable: words

**Comment by Shougo** [comment]
It seems the plugin error.
But I cannot reproduce it.

Please create the correct minimal .vimrc without pathogen.
You can use `set rtp+=` instead of `call pathogen#infect()`

It seems vim-go error.  But I cannot test it.

**Comment by RIscRIpt** [comment]
I just had this issue (error: `[neocomplete] Vim(let):E121: Undefined variable: words`).
Searching for the solution I came across with the same issue #432. And Shougo [recommended](https://github.com/Shougo/neocomplete.vim/issues/432#issuecomment-120689240) to install latest `gocode` there.
So I remembered that I didn't install any go binary, so running `:GoInstallBinaries` fixed this issue.

And I had a success reproducing this issue:

1. Close any opened (g)vim;
2. Remove (rename) your `$GOPATH/bin` folder:
    * If you don't have `$GOBIN`: `cd $GOPATH; mv bin bin.bak`;
    * Else `cd $GOBIN/..; mv bin bin.bak`;
3. Run (g)vim and try to write some go code.

**Comment by Shougo** [comment]
OK, thanks.

**Comment by rajeshduggal** [comment]
@chacken Were you able to fix this? I was having the same error earlier today.
An hour ago, I followed these instructions from @Shougo 's deoplete requirements...
https://github.com/Shougo/deoplete.nvim#requirements
pip3 install --user pynvim

And so far I haven't seen the "Vim(let):E121: Undefined variable: words" error in the last hour so far.

Can someone also confirm that this pip3 install step is what's needed to resolve this bug please?

If this is indeed the fix, then perhaps the https://spacevim.org/quick-start-guide/ install section...
"curl -sLf https://spacevim.org/install.sh | bash"
...should also include this pip3 install step as part of the deoplete installation.
