### ISSUE TITLE
How to disable the common string complete?

### ISSUE THREAD

**Issue by x565178035** [Shougo/neocomplete.vim#545]
# Problems summary
When I use NeoComplete to write Latex, The " Whole Line Complete " is not useful. How can I disable this function?

I tried the solution like [333](https://github.com/Shougo/neocomplete.vim/issues/333), but it doesn't work :(

Here is my vimrc
```
Plug 'Shougo/neocomplete.vim',{'for':language_ex}
    let g:neocomplete#enable_debug = 0
    let g:acp_enableAtStartup = 0
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#enable_auto_select = 0
    " let g:neocomplete#sources#syntax#min_keyword_length = 2
    " let g:neocomplete#sources#auto_completion_start_length = 3
    let g:neocomplete#max_list=30
    let g:neocomplete#sources#dictionary#dictionaries = {
        \ 'default' : '',
        \ 'arduino' : $VIM.'/vimfiles/dict/arduino.dict',
        ...
    \ }
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS

    inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
    inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
    inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
    function! s:my_cr_function()
      return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
      " For no inserting <CR> key.
      "return pumvisible() ? "\<C-y>" : "\<CR>"
    endfunction

    inoremap <C-h> neocomplete#smart_close_popup()."\<C-h>"
    inoremap <BS> neocomplete#smart_close_popup()."\<C-h>"

Plug 'jiangmiao/auto-pairs'
let g:AutoPairsMapBS=0

```

## Screen shot (if possible)
The function which I discribed is like this.
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-6-2/91076273.jpg)

**Comment by x565178035** [comment]
It was conflict with vim-latex and I use `let g:Tex_SmartKeyBS=0` fixed it!

**Comment by Shougo** [comment]
I think your Vim version is too old.
The old Vim has the bug.  You should update it.

**Comment by x565178035** [comment]
I think this version(7.4) is not very old in windows. I known Vim 8.0  has been released. I'm not sure if it can be used in windows. Here are some details about my Vim version.

![](http://7xrn7f.com1.z0.glb.clouddn.com/16-6-6/25466572.jpg)

**Comment by Shougo** [comment]
No.  It is very old.
The latest version is 7.4.1902.
You should use the daily build
https://github.com/vim/vim-win32-installer/releases

**Comment by x565178035** [comment]
Thanks a lot! Now I can deal this problem in a better way.

**Comment by CNMan** [comment]
@Shougo please add `https://github.com/vim/vim-win32-installer/releases` to ` 	README.md`

**Comment by Shougo** [comment]
I have added it.
