### ISSUE TITLE
Strip the leading '^I' from foldmethod warning message

### ISSUE THREAD

**Issue by Coacher** [Shougo/neocomplete.vim#546]
# Problems summary
Neocomplete messages re foldmethod look like this:
```
[neocomplete] foldmethod = "expr" is detected.
[neocomplete]   foldmethod=expr
[neocomplete] ^ILast set from /usr/share/vim/vimfiles/ftplugin/gap.vim
[neocomplete] You should disable it or install FastFold plugin.
```

Notice the leading `^I` on line 3.

## Expected
Messages should be nice and clean.

## Environment Information
 * OS: Gentoo
 * Vim version: 1902

**Comment by Shougo** [comment]
Fixed

**Comment by Coacher** [comment]
Thank you very much.
