### ISSUE TITLE
Russian words do not autocomplete in Markdown files

### ISSUE THREAD

**Issue by for-coursera** [Shougo/neocomplete.vim#547]
# Problems summary

As said, neocomplete doesn't seem to work for Russian words in Markdown files (works everywhere else).

## Expected

Let's say I have three English words in a Markdown buffer: table, tabulate, tabulator. Then, as soon as I enter "ta", neocomplete pops up with a suggestion list consisting of these three words.

However, the same isn't true for Russian in a Markdown buffer. Let's say I have three Russian words there: стол, стоять, столешница. Then, again, as I enter "ст" a popup menu is expected. However, it doesn't appear (yet `<C-x><C-n>` works fine).

## Environment Information

 * OS: OS X 10.8.5
 * Vim version: Vi IMproved 7.4 (2013 Aug 10, compiled Feb 21 2016 13:41:34)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" my whole .vimrc (stripped for that particular test case)
" Set hotkeys
" make <Tab> and <S-Tab> complete the next and previous item
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
" <enter> to select a suggestion 
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Load plugins
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/Shougo/neocomplete.vim'
call plug#end()

" Configure plugins
" enable Russian autocompletion
let g:neocomplete#enable_multibyte_completion = 1
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns._ = '[A-Za-zа-яА-Я_][0-9A-Za-zа-яА-Я_]*'
" use neocomplete 
let g:neocomplete#enable_at_startup = 1
" use smartcase
let g:neocomplete#enable_smart_case = 1
" set minimum syntax keyword length
let g:neocomplete#sources#syntax#min_keyword_length = 3
" set auto select
let g:neocomplete#enable_auto_select = 1
let g:neocomplete#enable_fuzzy_completion = 0
let g:neocomplete#enable_auto_close_preview = 1
```
## The reproduce ways from Vim starting (Required!)

 1. `:set filetype=markdown`
 2. start typing

## Screenshots

* Typing English:

![EN](http://i.imgur.com/tzeCIna.png)

* Typing Russian

![RU](http://i.imgur.com/0SyTpVK.png)

## Additional data

TAR'ed .vim directory (with only vim-plug and neocomplete) and the above-quoted .vimrc can be found [here](https://yadi.sk/d/4tlO9D7Pshgpa).

**Comment by Shougo** [comment]
Fixed.
