### ISSUE TITLE
Custom dictionarry

### ISSUE THREAD

**Issue by vissieGP** [Shougo/neocomplete.vim#548]
# Problems summary
Hi. Sorry I have been Googling the internet for hours... I can not figure out how to add a custom dictionary. So lets create a example where I would like to add 2 custom dictionaries. One is a spell check, English, on all the time. One is a OpenSCAD dictionary that will be active when I open a stl file.

## Expected
I added the following in my _vimrc:
```vim
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : 'C:/Program Files (x86)/Vim/vimfiles/dict/spell.dict',
        \ }
```
In my dict file, I have one value. I can not get neocomplete to pick that one file up.
I have tried to load cache, not sure what else to do.

## Environment Information
 * OS: Windows 7, 64 bit
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)
```
let g:screen_size_by_vim_instance = 1
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Define dictionary.
let g:neocomplete#data_directory = 'C:/Date/Test/cache'
			\
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : 'C:/Program Files (x86)/Vim/vimfiles/dict/spell.dict',
        \ }
```

## The reproduce ways from Vim starting (Required!)

 1. Add the custom dictionary
 2. Type that word, see if it comes up

**Comment by Shougo** [comment]
@vissieGP Please upload the spell.dict.

And did you read the neocomplete documentation about `g:neocomplete#sources#dictionary#dictionaries`?

```vim
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : 'C:/Program Files (x86)/Vim/vimfiles/dict/spell.dict',
        \ }
```

It means in only vimshell filetype, neocomplete loads the dictionary file (spell.dict).
I think you are beginner for Vim and you should set `dictionary` option.

**Comment by vissieGP** [comment]
Hi.
I have spend the whole day today reading the doc file. Again googling as much as I can.
I do not see myself as a beginner, no. But sure, I have not played with dictionaries or vim coding per say.

This is what I learned today.

If I add a custom dictionary:
set dictionary+=C:\Data\Vim\vissie.txt

I can call it using <C-x>\<C-k>. That works.

If I try the same with neocomplete:
let g:neocomplcache_dictionary_filetype_lists = {
	 \ 'default' : '',
	 \ '_' : 'C:\Data\Vim\vissie.txt'
	 \ } 
All I just get nothing.
All I ever get seems to be [B] buffer results cumming back from neocomplete.

My "new" config file:

filetype plugin on
set omnifunc=syntaxcomplete#Complete

let g:neocomplete#enable_at_startup 	  = 1
" Use smartcase.
let g:neocomplete#enable_smart_case       = 1
let g:neocomplete#enable_auto_delimiter   = 1
let g:neocomplete#enable_fuzzy_completion = 1
let g:neocomplete#enable_refresh_always   = 1
" Search from neocomplete, omni candidates, vim keywords.
let g:neocomplete#fallback_mappings = ["\<C-x>\<C-o>", "\<C-x>\<C-k>"]
let g:neocomplete#data_directory = 'C:\Data\Vim\cache'
let g:neocomplcache_dictionary_filetype_lists = {
	 \ 'default' : '',
	 \ '_' : 'C:\Data\Vim\vissie.txt'
	 \ } 

"set dictionary+=C:\Data\Vim\vissie.txt

" Enable omni completion.
autocmd   FileType   css             setlocal   omnifunc=csscomplete#CompleteCSS
autocmd   FileType   html,markdown   setlocal   omnifunc=htmlcomplete#CompleteTags
autocmd   FileType   javascript      setlocal   omnifunc=javascriptcomplete#CompleteJS
autocmd   FileType   python          setlocal   omnifunc=pythoncomplete#Complete
autocmd   FileType   xml             setlocal   omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

" For perlomni.vim setting.
" https://github.com/c9s/perlomni.vim
let g:neocomplete#sources#omni#input_patterns.perl = '\h\w*->\h\w*\|\h\w*::'

**Comment by Shougo** [comment]
`g:neocomplcache_dictionary_filetype_lists` is not neocomplete variable.
Please use `g:neocomplete#sources#dictionary#dictionaries` instead.

Please read `:help g:neocomplete#sources#dictionary#dictionaries`.

```vim
let  g:neocomplete#sources#dictionary#dictionaries = {
     \ '_' : 'C:\Data\Vim\vissie.txt'
     \ } 
```

**Comment by vissieGP** [comment]
Hi. yes, that works! Thank you so much! I can not tell you how nice this is now!!

:help g:neocomplete#sources#dictionary#dictionaries -> just fyi, this only give me a error : Sorry, no help for... But I did read the doc file in ..vimfiles\doc\neocomplete.txt

So, last open item. The above will give me my (multiple) dictionaries that will show up in all files.

How do I select a custom dictionary for a specific file type?

I installed and enabled context_filetype.

I added the following in my _vimrc:

if !exists('g:context_filetype#same_filetypes')
  let g:context_filetype#filetypes = {}
endif
let g:context_filetype#filetypes.scad = 'scad'

let g:context_filetype#filetypes.scad =
	\ [{'filetype' : 'scad', 'start': '^\s*scad ', 'end' : '}'}]

let g:neocomplete#data_directory = 'C:\Data\Vim\cache'
let  g:neocomplete#sources#dictionary#dictionaries = {
     \ '_' : 'C:\Data\Vim\dic\vissie.txt' ,
     \ 'scad' : 'C:\Data\Vim\dic\openscad.txt'
     \ }

As you can see, I am trying to associate all files ending with .scad, to load the dictionary file located in 'C:\Data\Vim\dic\openscad.txt' .

Again, thx for your help getting this far!

**Comment by Shougo** [comment]
> How do I select a custom dictionary for a specific file type?

` g:neocomplete#sources#dictionary#dictionaries` key is the filetype.

> As you can see, I am trying to associate all files ending with .scad, to load the dictionary file located in 'C:\Data\Vim\dic\openscad.txt' .

You should use `:set filetype`.
Your context filetype configuration is wrong.

`autocmd BufRead,BufNewFile *.scad set filetype=scad`

**Comment by vissieGP** [comment]
Hi.
Yes, that worked perfectly. I had to add this to my ~/.vim/ftdetect/openscad.vim file.
And now it works like a dream.

That was my last question. All is working as I wanted it too.

Again, thx for great code and sharing your knowledge and helping me to get this sorted out!!

Vissie

**Comment by vissieGP** [comment]
Hi. Sorry, actually I do have one more question.

Is there a way that I can link word together? So from a coding point of view. Lets say I code in Python.
I will have standard functions with methods below every function. Here is a example:
path.abspath
path.altsep
path.basename
path.commonprefix
path.curdir
path.defpath
os.path.abspath
os.path.altsep
os.path.basename
os.path.commonprefix
os.path.curdir
conn.close
conn.commit
conn.rollback
conn.cursor
conn.xid

So is there a way, if I have typed in say conn and I hit the . that I can get a list of all the sub methods below that. So close, commit, rollback etc....? 

So I have lists of all these inter dependencies. So I was just wondering.

Vissie

**Comment by Shougo** [comment]
> Is there a way that I can link word together? So from a coding point of view. Lets say I code in Python.

You can change `g:neocomplete#keyword_patterns` for it.
But it changes buffer source behavior.
So, this feature is not supported.
