### ISSUE TITLE
Smart/camel case completion only completes an upper case variant

### ISSUE THREAD

**Issue by dominickng** [Shougo/neocomplete.vim#550]
# Problems summary

This is similar to #522.

With smart case completion enabled and a complete_common_string / complete mapping on <TAB>, neocomplete will prompt for a smart-case completion when you type the lower case variant of a word. This is expected. However, if you have both an UPPER/camelcase and lower case completion previously typed (i.e. available for completion), only the UPPER/camelcase case variant appears in the completion menu, and when you <TAB> to insert the completion, it is inserted as UPPER/camelcase only.

## Expected

The lower-case completion should be available, not just the UPPER case one (see reproduce steps)

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: 7.4.1816

## Provide a minimal .vimrc with less than 50 lines (Required!)

```
set nocompatible      
set runtimepath+=~/path/to/neocomplete
                                                                               
set fo+=aw
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 0
let g:neocomplete#enable_smart_case = 1
set tw=10

inoremap <expr><Tab>
\ neocomplete#complete_common_string() != '' ?
\   neocomplete#complete_common_string() :
\ pumvisible() ? "\<C-n>" : "\<TAB>"
```

## The reproduce ways from Vim starting (Required!)

 1. In Insert mode, type `CamelCaseVariant`
 2. Press Enter a few times. Type `camelcasevariant`
 3. Press Enter a few times. Type `camelca` until the completion menu appears. Note that `CamelCaseVariant` is in the menu, but not `camelcasevariant`, which was also previously typed
 3. Type `<TAB>` to complete. Note that `CamelCaseVariant` is inserted, and `camelcasevariant` is unavailable

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed
