### ISSUE TITLE
exit under specific circumstance

### ISSUE THREAD

**Issue by mengesb** [Shougo/neocomplete.vim#553]
# Problems summary
The following syntax causes mvim to exit suspended (:sus)
```hcl
variable "something" { default = "/home/a/lsyncd-${sha1(aws_instance.)}"
```

The second I hit that period `.`, it exits. I've tested several iterations of this and it seems to be central around the following text:

```
/home/a/lsyncd-${sha1(aws_instance.)}
```

Using any other root path doesn't do it except for a subdirectory of `/home` on a mac.

## Expected
completion functions as normal and vim doesn't exit/suspend

## Environment Information
 * OS: MacOSX El Capitan (latest)
 * Vim version: 7.4 for MacOS X patches 1-2196

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" ================ Custom Settings ========================
so ~/.yadr/vim/settings.vim
```

## The reproduce ways from Vim starting (Required!)

 1. `vi file`
 2.  type `/home/a/lsyncd-${sha1(aws_instance.)}`

## Screen shot (if possible)
<img width="606" alt="mvim death" src="https://cloud.githubusercontent.com/assets/1378071/17635892/e7c33d40-608e-11e6-9559-3e9dd8d79328.png">

## Upload the log messages by `:redir` and `:message`
`:redir`: nothing
`:message`:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"file" 1L, 37C
"file" 1L, 37C
E42: No Errors
1 change; before #9  12:52:17
1 change; before #8  12:52:15
1 change; before #7  12:52:12
1 change; before #6  12:52:12
1 change; before #5  12:52:09
1 change; before #4  12:52:04
1 change; before #3  12:52:00
1 change; before #2  12:51:56
"file" 1L, 37C written
E42: No Errors
E475: Invalid argument:
Press ENTER or type command to continue
```

**Comment by mengesb** [comment]
So a little more of an update.

I went into the neocomplete.vim file loaded via the usual .yadr method, and modified [autoload/neocomplete.vim#L88](../tree/master/autoload/neocomplete.vim#L88) lines 88 and 89 to disable ignore_source_files and the problem went away

```vim
let g:neocomplete#ignore_source_files =
      \ get(g:, 'neocomplete#ignore_source_files', [])
```

Not sure where exactly this has an issue however with that enabled, I'm getting this issue

**Comment by mengesb** [comment]
Seems when I comment out the whole of [neocomplete/autoload/neocomplete/sources/file.vim](../blob/master/autoload/neocomplete/sources/file.vim) my problem goes away

**Comment by mengesb** [comment]
It seems to be borking in particular on a `/home/<anything>/${text.`

Once I hit that `.`, it dies!

It is really specific to `/home` as the starting path, there has to be a subdirectory, whether it exists or not, and then `${.`. Seems the sequence `/home/a/${.` is the smallest form required

**Comment by mengesb** [comment]
So for the moment, I've added to my `~/.vimrc.after` the following syntax to help: `au filetype terraform NeoCompleteLock` since this is where I'm doing the expression `/home/a/${.`

Not sure if this was something going on a long while ago, however it seems to be an odd issue to say the least.

**Comment by Shougo** [comment]
It seems Vim's bug.
But I cannot reproduce the problem in Vim 7.4.2204.

Please test the minimal .vimrc.
I cannot understand what is `~/.yadr/vim/settings.vim`.
This is not minimal .vimrc.

```vim
set nocompatible
set runtimepath+=~/work/neocomplete.vim/

let g:neocomplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
I have fixed it.
I cannot reproduce the problem though.
