### ISSUE TITLE
Plugin stuck in infinite loop

### ISSUE THREAD

**Issue by rmolin88** [Shougo/neocomplete.vim#555]
# Problems summary
 - Vim freezes and doesnt respond until `<c-c>` is pressed.
 - Seems to happen when dealing with binary files

## Environment Information
 * OS: Win7
 * Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 13 2016 21:13:28)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2207
Compiled by veegee@VEEGEE-WIN10
Huge version with GUI.  Features included (+) or not (-):
+acl             +channel         +comments        +diff            +ex_extra        -footer          +keymap          +localmap        +multi_byte      +path_extra      +python3/dyn     +smartindent     -tag_any_white   +title           +viminfo         -xim
+arabic          +cindent         +conceal         +digraphs        +extra_search    +gettext/dyn     +lambda          +lua/dyn         +multi_lang      -perl            +quickfix        +startuptime     -tcl             +toolbar         +vreplace        -xpm_w32
+autocmd         +clientserver    +cryptv          +directx         +farsi           -hangul_input    +langmap         +menu            -mzscheme        +persistent_undo +reltime         +statusline      -termguicolors   +user_commands   +wildignore      -xterm_save
+balloon_eval    +clipboard       +cscope          -dnd             +file_in_path    +iconv/dyn       +libcall         +mksession       +netbeans_intg   -postscript      +rightleft       -sun_workshop    -tgetent         +vertsplit       +wildmenu        
+browse          +cmdline_compl   +cursorbind      -ebcdic          +find_in_path    +insert_expand   +linebreak       +modify_fname    +num64           +printer         +ruby/dyn        +syntax          -termresponse    +virtualedit     +windows         
++builtin_terms  +cmdline_hist    +cursorshape     +emacs_tags      +float           +job             +lispindent      +mouse           +ole             +profile         +scrollbind      +tag_binary      +textobjects     +visual          +writebackup     
+byte_offset     +cmdline_info    +dialog_con_gui  +eval            +folding         +jumplist        +listcmds        +mouseshape      +packages        +python/dyn      +signs           +tag_old_static  +timers          +visualextra     -xfontset        
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjGXOUYHRAMD64/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA  -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=230 -DDYNAMIC_RUBY_DLL=\"x64-msvcr120-ruby230.dll\" -DFEAT_HUGE /Fd.\ObjGXOUYHRAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64 /nodefaultlib libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib   /nodefaultlib:python27.lib /nodefaultlib:python35.lib    WSock32.lib  /PDB:gvim.pdb -debug

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" My minimal .vimrc
				let g:neocomplete#enable_cursor_hold_i=1
				let g:neocomplete#skip_auto_completion_time="1"
				let g:neocomplete#sources#buffer#cache_limit_size=5000000000
				let g:neocomplete#max_list=8
				let g:neocomplete#auto_completion_start_length=2
				let g:neocomplete#enable_auto_close_preview=1

				let g:neocomplete#enable_at_startup = 1
				let g:neocomplete#enable_smart_case = 1
				let g:neocomplete#data_directory = s:personal_path . 'neocomplete'
				" Define keyword.
				if !exists('g:neocomplete#keyword_patterns')
					let g:neocomplete#keyword_patterns = {}
				endif
				let g:neocomplete#keyword_patterns['default'] = '\h\w*'
				" Recommended key-mappings.
				" <CR>: close popup and save indent.
				inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
				function! s:my_cr_function()
					return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
				endfunction
				" <TAB>: completion.
				inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
				" <C-h>, <BS>: close popup and delete backword char.
				inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
				" Enable heavy omni completion.
				if !exists('g:neocomplete#sources#omni#input_patterns')
					let g:neocomplete#sources#omni#input_patterns = {}
				endif
				let g:neocomplete#sources#omni#input_patterns.tex =
					\ '\v\\%('
					\ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
					\ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
					\ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
					\ . '|%(include%(only)?|input)\s*\{[^}]*'
					\ . ')'
				let g:neocomplete#sources#omni#input_patterns.php =
				\ '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
				let g:neocomplete#sources#omni#input_patterns.perl =
				\ '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

				if !exists('g:neocomplete#force_omni_input_patterns')
					let g:neocomplete#force_omni_input_patterns = {}
				endif
				let g:neocomplete#force_omni_input_patterns.c =
							\ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
				let g:neocomplete#force_omni_input_patterns.cpp =
							\ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
				let g:neocomplete#force_omni_input_patterns.objc =
							\ '\[\h\w*\s\h\?\|\h\w*\%(\.\|->\)'
				let g:neocomplete#force_omni_input_patterns.objcpp =
							\ '\[\h\w*\s\h\?\|\h\w*\%(\.\|->\)\|\h\w*::\w*'

				" all new stuff
				if !exists('g:neocomplete#delimiter_patterns')
					let g:neocomplete#delimiter_patterns= {}
				endif
				let g:neocomplete#delimiter_patterns.vim = ['#']
				let g:neocomplete#delimiter_patterns.cpp = ['::']

" my binary file settings:
	augroup Binary
		au!
		au BufReadPre  *.bin,*.hsr,*.pdf let &l:bin=1
		au BufReadPost *.bin,*.hsr,*.pdf if &bin | %!xxd
		au BufReadPost *.bin,*.hsr,*.pdf setlocal ft=xxd | endif
		au BufWritePre *.bin,*.hsr,*.pdf if &bin | %!xxd -r
		au BufWritePre *.bin,*.hsr,*.pdf endif
		au BufWritePost *.bin,*.hsr,*.pdf if &bin | %!xxd
		au BufWritePost *.bin,*.hsr,*.pdf setlocal nomod | endif
	augroup END
```

## The reproduce ways from Vim starting (Required!)
 1. Edit a cpp file
 2. Load a binary file
 3. Switch buffers to previous file (cpp) and vim freezes. Try to edit cpp again and vim freezes.

## Upload the log messages by `:redir` and `:message`
 - vim log file showing the issue [here](https://drive.google.com/file/d/0B65GtWgJn1tFclNqRDZWMHZpYzQ/view?usp=drivesdk)
 - My full vimrc can be found [here](https://github.com/rmolin88/vimrc). Its the _vimrc file.

**Comment by Shougo** [comment]
> Load a binary file

What is the binary file and cpp file?
Please upload them.  I will test.

And the uploaded vimrc is not minimal vimrc.
Please read other issues and upload minimal vimrc.

**Comment by Shougo** [comment]
```vim
" my binary file settings:
    augroup Binary
        au!
        au BufReadPre  *.bin,*.hsr,*.pdf let &l:bin=1
        au BufReadPost *.bin,*.hsr,*.pdf if &bin | %!xxd
        au BufReadPost *.bin,*.hsr,*.pdf setlocal ft=xxd | endif
        au BufWritePre *.bin,*.hsr,*.pdf if &bin | %!xxd -r
        au BufWritePre *.bin,*.hsr,*.pdf endif
        au BufWritePost *.bin,*.hsr,*.pdf if &bin | %!xxd
        au BufWritePost *.bin,*.hsr,*.pdf setlocal nomod | endif
    augroup END
```

This is too slow for big binary file.
