### ISSUE TITLE
Omnicomplete never triggers

### ISSUE THREAD

**Issue by mjedmonds** [Shougo/neocomplete.vim#556]
# Problems summary
I can never get omnicomplete to activate. My configuration is fairly straightforward, and I haven't been able to spot anything that could be causing it.

## Expected
Omnicompletion to work

## Environment Information
 * OS: OS X 10.10
 * Vim version: MacVim 7.4.105

## Provide a minimal .vimrc with less than 50 lines (Required!)

```
"-----------------------------------------------------------------------
" Neocomplete
"-----------------------------------------------------------------------
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Auto close the preview window
let g:neocomplete#enable_auto_close_preview = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
"let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
      \ 'default' : '',
      \ 'vimshell' : $HOME.'/.vimshell_hist',
      \ 'scheme' : $HOME.'/.gosh_completions'
      \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
  let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  ""return neocomplete#close_popup() . "\<CR>"
  " For no inserting <CR> key.
  return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
" Close popup by <Space>.
inoremap <expr><Space> pumvisible() ? "\<C-y>" : "\<Space>"

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" disable buffer completion
"call neocomplete#custom#source('buffer', 'disabled', 1)

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'
let g:neocomplete#sources#omni#input_patterns.tex =
        \ '\v\\%('
        \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
        \ . '|hyperref\s*\[[^]]*'
        \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|%(include%(only)?|input)\s*\{[^}]*'
        \ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . ')'

"-----------------------------------------------------------------------

```

The full vimrc is available [here](https://github.com/mjedmonds/.dotfiles/blob/master/vim/.vimrc).

## The reproduce ways from Vim starting (Required!)

 1. Open a cpp, or a tex with content
 2. Attempt to do something that should trigger omnicompletion (e.g. start typing an object's member
 3. Watch as only buffer completion triggers

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/6476860/18138749/1a31ed66-6f63-11e6-9acd-8936c7412849.png)

## Upload the log messages by `:redir` and `:message`
Both are empty.

**Comment by Shougo** [comment]
Do you know `omnifunc` feature?
The feature is not magic.
I think you have not install the omnifunc plugins.
You should install vim-clang(for C++) and vimtex(for TeX).
https://github.com/lervag/vimtex
Can you show me the candidates manually(by `<C-x><C-o>`)?

Note: your uploaded minimal vimrc is not minimal.
I cannot reproduce it.

**Comment by Shougo** [comment]
Additional note:

> Attempt to do something that should trigger omnicompletion (e.g. start typing an object's member

The pattern does not matched the object's member.
They match only `.` or `::`.

```vim
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'
```

**Comment by mjedmonds** [comment]
Yes, I know omnifunc requires plugins. I had forgotten `vim-clang`, but I have vimtex installed (and it doesn't work their either).

As for the reproduction, that is my entire vimrc related to neocomplete; here is my complete vimrc: [.vimrc](https://github.com/mjedmonds/.dotfiles/blob/master/vim/.vimrc)

As to the object's member, I was referring to the example in the screenshot (note that the screenshot does not template TestClass as it should, the same thing happens with `a` properly declared. My understanding is that the pattern should show func1 from omnicomplete on the `a.func` line. Am I incorrect in thinking so?

**Comment by Shougo** [comment]
> Yes, I know omnifunc requires plugins. I had forgotten vim-clang, but I have vimtex installed (and it doesn't work their either).

You should ask the author for vimtex problem.

> My understanding is that the pattern should show func1 from omnicomplete on the a.func line. Am I incorrect in thinking so?

Yes.  Because:

> The pattern does not matched the object's member.
> They match only . or ::.

They should be:

```vim
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)\w*'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::\w*'
```
