### ISSUE TITLE
gvim hangs if the custom dictionary is a large file

### ISSUE THREAD

**Issue by CNMan** [Shougo/neocomplete.vim#558]
[english.zip](https://cnlic.com/share/uploads/english.zip)

```vim
set dictionary+=e:\system32\vim\dict\english.dict
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let  g:neocomplete#sources#dictionary#dictionaries = {
     \ '_' : 'e:\system32\vim\dict\english.dict' ,
     \ }
```

**Comment by Shougo** [comment]
It is feature.
You should install vimproc.
https://github.com/Shougo/vimproc.vim

**Comment by CNMan** [comment]
still hangs after install vimproc, and cause high cpu usage. 
Can you provide the latest vimproc windows binaries for testing? thanks.

**Comment by Shougo** [comment]
You must build vimproc.

The binary is:
https://github.com/Shougo/vimproc.vim/releases
