### ISSUE TITLE
neocomplete and vim version 8

### ISSUE THREAD

**Issue by gvdeynde** [Shougo/neocomplete.vim#559]
# Problems summary
Neocomplete's init function doesn't detect vim 8

## Expected
Neocomplete should detect (I assume vim 8 is superior to required 7.x patchlevel) 

## Environment Information
 * OS: Win64
 * Vim version: 8.0.17

**Comment by Shougo** [comment]
What is your problem?
And please upload the error messages.
I have tested Vim 8.0.5 and neocomplete works.
You should check if_lua is enabled.

**Comment by gvdeynde** [comment]
neocomplete does not work with this version of Vim.
neocomplete requires Vim 7.3.885 or later with Lua support ("+lua").

Vim version 8.0.17
+lua/dyn support

But :echo has("lua") returns 0. Apparently, my Vim can't find Lua. 

My bad. Apologies.

**Comment by wblakecaldwell** [comment]
I was able to get this working in vim 8:

    wget https://www.lua.org/ftp/lua-5.3.3.tar.gz \
        && tar zxvf lua-5.3.3.tar.gz \
        && cd lua-5.3.3 \
        && make linux \
        && sudo make install

and when you build vim, you need to set this environment variable:

    export LUA_PREFIX=/usr/local

full instructions here: https://github.com/wblakecaldwell/vim-setup/blob/master/GoDevSetup-Linux.md
