### ISSUE TITLE
Why does neocomplete care about my foldmethod?

### ISSUE THREAD

**Issue by megapctr** [Shougo/neocomplete.vim#562]
See this block: https://github.com/Shougo/neocomplete.vim/blob/4bf7526a1c8cca9f8614e8a09178f334eaca0481/autoload/neocomplete/handler.vim#L221-L236

I see this warning a lot, it's annoying. Also, I don't experience any issues with folds.

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/536
