### ISSUE TITLE
neocomplete configuration with only dictionary (spellcheck language) suggestions

### ISSUE THREAD

**Issue by Remiol** [Shougo/neocomplete.vim#567]
Hi Shougo,

I have neocomplete installed since many years but I don't use it very much.
I want to use it only with dictionary (=language) suggestions in autopopup" mode .
I'm not enable to do this.
(no buffer words, no file words, no key words... only dictionary suggestions (with fuzzy match))

Can you please help me?

(Dictionary suggestions --> the current spellcheck dictionary)

**Comment by Remiol** [comment]
sorry, forgot to write "in autopopup" mode

**Comment by Shougo** [comment]
Please chenge `g:neocomplete#sources` value.

**Comment by Remiol** [comment]
Sorry, I still don't understand it. 
g:neocomplete#sources._ = ['dictionary'] ?
It doesn't seem to work

**Comment by Shougo** [comment]
> let  g:neocomplete#sources._ = ['dictionary'] 

It works.  But you must config it.

> (Dictionary suggestions --> the current spellcheck dictionary)

You want to complete words by spellcheck?
You should use `:help i_CTRL-X_s`.
auto completion is not implemented.  Because it is too sloooow!

**Comment by Remiol** [comment]
Oepss... why is this stuff so difficult :) I find it easier to write python code than vim code.

Config it? You mean
let g:neocomplete#sources.vim = ['dictionary']
or something like that?

I want to to use only <ctrl-x><ctrl-k> 
auto completion of <ctrl-x><ctrl-k> very well in supertab, but it does not fuzzy matching.

**Comment by Shougo** [comment]
> I find it easier to write python code than vim code.

You should use deoplete.nvim instead.

> Config it?

Please read the documentation.

`:help neocomplete-source-dictionary`

**Comment by Shougo** [comment]
> It doesn't seem to work

I cannot reproduce it.  We have not ESP skills.
Please create the minimal vimrc with the reproduce ways.
I will test it.

**Comment by Remiol** [comment]
Neovim? I don't use it because the software doesn't have a graphical interface and I can't use the setting I created in menu.vim
let g:neocomplete#sources._ = ['dictionary'] gives an error on my system
E121: Undefined variable: g:neocomplete#sources
Well no problem.. After a morning searching I give it up.

**Comment by Shougo** [comment]
Oh, you are Vim script beginner....
Please define the variable before use it.

```vim
let g:neocomplete#source = {}
let g:neocomplete#sources._ = ['dictionary'] 
```

Please read the neocomplete documentation.

**Comment by Remiol** [comment]
Yes, maybe a vim beginner but some manuals are not clear enough (for me) to understand all. I've read the neocomplete documentation many times but it didn't resolve my problem and still above code gives the same error. Sure, for you it must be all easy, you've created the manual :)

**Comment by Shougo** [comment]
I have miss spelled.

```vim
let g:neocomplete#sources = {}
let g:neocomplete#sources._ = ['dictionary']
```

You should learn Vim script before using the plugins.

**Comment by Remiol** [comment]
Oh maybe but I've written over 5000 lines of code in vimscript but I always had troubles to understand your comments. Btw the art of writing manuals is to make them clear for everyone, not only for yourself and Bram Molenaar.

**Comment by Shougo** [comment]
> Btw the art of writing manuals is to make them clear for everyone, not only for yourself and Bram Molenaar.

The PR is wellcome.

**Comment by Shougo** [comment]
> Oh maybe but I've written over 5000 lines of code in vimscript but I always had troubles to understand your comments. 

Oh, I have written over 100000 lines of code in vim script.

**Comment by Remiol** [comment]
Bravo Shougo, that's why your knowledge is deeper than mine. ;) There are people who are speaking japanese and there are people who are speaking chinese.. Everybody has something to learn. My english is not perfect but I won't correct your wellcome and tell you that in english you write 'welcome' and not 'wellcome' (till now). You're never to old to learn. Please don't diminish others with your knowledge. One thing is sure... I dedicated of all plugins I have most time to your plugin (over the last 4, 5 years) and I never could make it work as I wanted. Even youcompleteme was easier to understand (but very slow to use on my system).

**Comment by Shougo** [comment]
I have not much time to improve the documentation.
And neocomplete development is already done.
My main work is for deo-plugins.

> Even youcompleteme was easier to understand (but very slow to use on my system).

YouCompleteMe is easier
Really?

It has the many issues.  It is hard to configuration/installation.
https://github.com/Valloric/YouCompleteMe/issues

My plugins have many features/configuration and huge documentation.
But you don't have to use all features.

> I dedicated (of all plugins I have) most time to your plugin (over the last 4, 5 years) and I never could make it work as I wanted.

It is not easy to configure as you wanted.
To configure Vim as you wanted is very hard, too.

**Comment by Remiol** [comment]
I've tried YouCompleteMe a few years without problems (I just followed the indications).

Sure even Vim is not easy to configure. 
I'm not a professional programmer, studied engineering, learned a bit of fortran and basic. Worked in in the informatica branch for many years (commercial functions). Programming is a bit of hobby and I noted that the scripts I've written helped me to make my life easier.  Sure, even vimscript is not an easy script language. I noted that writing the same stuff in Python was much easier and there is a lot of documentation available about Python. However vim is in my opinion still the best text editor and the work Bram has done is incredible. What do you think of Neovim?

**Comment by Shougo** [comment]
I use neovim everyday.
I think neovim is better.

And I have created some Python based plugins for neovim.

**Comment by Remiol** [comment]
Thanks for your opinion. Is Neovim faster? What makes it better? I didn't note a lot of differences but I'm not a plugin writer :)
Do you know if there will be a graphical interface in neovim? Do you know if we ever can use menu.vim within neovim?

**Comment by Shougo** [comment]
neovim is faster for me.

> What makes it better?

You should search for neovim.

> Do you know if there will be a graphical interface in neovim? Do you know if we ever can use menu.vim within neovim?

Some GUI clients are exists.  But I use neovim for CUI only.
neovim in CUI is better than Vim in CUI.
