### ISSUE TITLE
neocomplete with jedi-vim slow when first complete numpy

### ISSUE THREAD

**Issue by dengxqi** [Shougo/neocomplete.vim#568]
# Problems summary
neocomplete with jedi-vim slow when first complete numpy, code like:

```python
import numpy as np
np.
```

after press dot, it is slow and need to wait about 2~3s, this happened when first used, after that the completion will be fast, so is there any way to make the first completion process fast?

## Expected
make the first completion process fast?

## Environment Information
 * OS: win 7 
 * Vim version: vim 8.0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:acp_enableAtStartup = 0
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
```

**Comment by Shougo** [comment]
This is jedi-vim problem.  I cannot fix it.
