### ISSUE TITLE
Popup triggered in weird situations

### ISSUE THREAD

**Issue by hgfischer** [Shougo/neocomplete.vim#569]
# Problems summary

Append (A) triggers autocomplete on weird situations, and it is annoying. For example, in the code bellow, if I go to the line with `do` and press `A` (shift+a) the cursor goes to the end of the line and the popup opens. My intention is just to press space and start adding something.

![screenshot from 2017-01-05 11-46-16](https://cloud.githubusercontent.com/assets/120860/21678437/04a63fde-d33f-11e6-92e2-1f82a5f9571c.png)

## Expected

I don't expect autocomplete to work on a text that was already there on the buffer while I'm just moving around in command mode, or switching to edit mode. In other words, could I make it open only when I press TAB after N characters just typed?

## Environment Information
 * OS: Debian 8, Ubuntu 14.04 LTS, Ubuntu 16.04 LTS, Max OS X (last 2 versions)
 * Vim version: tested on 7.4 and 8

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
syntax on
filetype plugin indent on
set shortmess=at 
let g:acp_enableAtStartup = 1
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
  "return pumvisible() ? "\<C-y>" : "\<CR>"
endfunction
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><Space> pumvisible() ? "\<C-y>" : "\<Space>"
hi Normal ctermbg=none
set nofoldenable
nmap <F4> :TagbarToggle<CR>
let g:syntastic_enable_signs = 1
let g:syntastic_echo_current_error = 1
let g:syntastic_enable_highlighting = 1
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
hi IndentGuidesOdd  ctermbg=black
hi IndentGuidesEven ctermbg=darkgrey
let g:indent_guides_auto_colors=0
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_guide_size=1
let g:indent_guides_start_level=2
```

## The reproduce ways from Vim starting (Required!)

 1. Use the following config
 2. Create a shell script with similar content to the picture
 3. Press shift+a on the `do` line

## Screen shot (if possible)
![screenshot from 2017-01-05 11-46-16](https://cloud.githubusercontent.com/assets/120860/21678437/04a63fde-d33f-11e6-92e2-1f82a5f9571c.png)

## Upload the log messages by `:redir` and `:message`

[empty] - no errors

**Comment by Shougo** [comment]
> In other words, could I make it open only when I press TAB after N characters just typed?

You should disable the auto completion.

`let g:neocomplete#disable_auto_complete = 1`

**Comment by hgfischer** [comment]
But this disables it completely. Not even TAB works.

**Comment by Shougo** [comment]
This is my mapping.

```vim
" <TAB>: completion.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ neocomplete#start_manual_complete()
function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}
```

**Comment by hgfischer** [comment]
Thanks @Shougo 

This seems to do the work on cursor movement, but it seems the `start_manual_complete()` is doing nothing. The popup is not displayed. Any suggestions?

Also, why not update the recommended settings on the README with this info?

**Comment by Shougo** [comment]
> This seems to do the work on cursor movement, but it seems the start_manual_complete() is doing nothing. The popup is not displayed. Any suggestions?

I cannot reproduce it.
Please create the minimal vimrc and upload the reproduce ways.

> Also, why not update the recommended settings on the README with this info?

Updated.
