### ISSUE TITLE
Inserting an undesirable completion with pymode after hitting dot

### ISSUE THREAD

**Issue by Sunno** [Shougo/neocomplete.vim#570]
# Problems summary
When I hit dot sometimes the plugin inserts first choice of completion automatically and I have to delete it manually, it should not insert any completion at all, just shows choices. It only happens with pymode and neocomplete together.

It stops happening if g:neocomplete#disable_auto_complete is 1, but in that case I lose some completions.

## Expected
Show only completion choices without inserting any text. Maybe if I could disable dot completion or rely to active dot completion it could be fixed.

## Environment Information
 * OS: Manjaro Linux
 * Vim version: 8.0.0170-1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Pymode
let g:pymode_rope_complete_on_dot = 1
let g:pymode_rope_autoimport_import_after_complete = 0
let g:pymode_rope_autoimport = 0
let g:pymode_rope = 1
 
" Neocomplete
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_auto_select = 0
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
```

## The reproduce ways from Vim starting (Required!)

 1. vim in the console
 2. open a file
 3. write the number of an object (it happens with "self")
 4. sometimes neocomplete inserts a text

**Comment by Shougo** [comment]
Please disable pymode auto completion.
It conflicts with neocomplete.

```vim
let g:pymode_rope_complete_on_dot = 0
```
