### ISSUE TITLE
Plugin doesn't complete new words from buffers

### ISSUE THREAD

**Issue by ciases** [Shougo/neocomplete.vim#571]
# Problems summary
Hello!
I've got a problem with new words completion, plugin doesn't suggest words form other buffers.

For example, I've got two files opened: `index.html` and `styles.css`. I add button tag with class `clear-button` to html file, then switch to css and try to add some styles. I type `.cle` and hit `Ctrl+n` but vim doesn't suggest me `clear-button` option. I don't see `clear-button` option even if I don't type dot `.` sign, i.e. `cle` only.

## Expected
After I type `.cle` in second buffer and hit `Ctrl+n`, vim suggest me `clear-button` option from first buffer.

## Environment Information
 * OS: Ubuntu 14.04 (x64)
 * Vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  9 2016 23:23:57)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible

call plug#begin()

"autocomplete
Plug 'Shougo/neocomplete.vim'

"snippets
Plug 'Shougo/neosnippet.vim'
Plug 'ciases/neosnippet-snippets'

call plug#end()

filetype plugin indent on
set hidden
set encoding=utf-8                      " Set encoding to UTF-8.
set fileencoding=utf-8                  " Set file encoding to UTF-8.
syntax enable
set showcmd     "show incomplete cmds down the bottom

set iskeyword+=-

" Neocomplete settings
let g:neocomplete#enable_at_startup = 1

" Enable omni completion.
augroup omni_completion
    autocmd!
    autocmd FileType css,less,scss setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
augroup END
```

## The reproduce ways from Vim starting (Required!)

 1. Create basic `html` file (first buffer), add button tag `<button class="clear-button">Clear</button>`.
 2. Create basic css file (second buffer).
 3. Add styles for `.clear-button` selector in second buffer: type `.cle` and hit `Ctrl+n`. There is no `clear-button` option from first buffer.

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/14925066/22405120/a9343eee-e64e-11e6-8e43-2ec9df77db61.png)

**Comment by Shougo** [comment]
context_filetype.vim plugin is needed.

**Comment by ciases** [comment]
I still got some problems. It works not as expected. Plugin suggest something only at second attemp, for example, when I type `space` and then delete it. I recorded video.

Here is my minimal `_vimrc`:

```vim
set nocompatible

call plug#begin()

Plug 'tpope/vim-sensible'

"autocomplete
Plug 'Shougo/neocomplete.vim'
Plug 'Shougo/context_filetype.vim'

"snippets
Plug 'Shougo/neosnippet.vim'
Plug 'ciases/neosnippet-snippets'

call plug#end()

filetype plugin indent on
set wildmenu
set iskeyword+=-
syntax enable

let g:neocomplete#enable_at_startup = 1

augroup add_dict
    autocmd!
    autocmd filetype javascript set dictionary+=$VIMFILES/bundle/vim-dict/dict/javascript.dic
    autocmd filetype html set dictionary+=$VIMFILES/bundle/vim-dict/dict/html.dic
    autocmd filetype css set dictionary+=$VIMFILES/bundle/vim-dict/dict/css.dic
augroup END

augroup omni_completion
    autocmd!
    autocmd FileType css,less,scss setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
augroup END

imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
```
This is a [link to mp4 video](http://rgho.st/private/6ssDmvCQZ/1bb6b0d05da18db6621a79b2ec516c1a)

**Comment by Shougo** [comment]
It is feature.
Because, omni completion overwrites them.

**Comment by ciases** [comment]
Oh! Ok. Thanks for quick feedback!
