### ISSUE TITLE
how to add member complete source from file

### ISSUE THREAD

**Issue by hyaray** [Shougo/neocomplete.vim#574]
I'm sorry to trouble you, there is few introduction of member complete?
default member complete source is buffer?
I want add member complete from my own file.
If I create a file 'js.txt' for member complete, content like 

> window:document,alert(),close()

and if I input 'window.' in JavaScript file, it can show 3 complete for me.

problem is:
1. what's the correct format of the file 'js.txt'?
2. how to config in vimrc？

**Comment by Shougo** [comment]
You cannot do it.
Because member source is not omnifunc.
It is not extensible.
