### ISSUE TITLE
g:neocomplete#sources#dictionary#dictionaries，can javascript add multi dict files?

### ISSUE THREAD

**Issue by hyaray** [Shougo/neocomplete.vim#575]
let g:neocomplete#sources#dictionary#dictionaries = {
            \ 'default' : '',
            \ 'javascript' : $VIM.'/dict/js.dict',
            \ 'javascript' : $VIM.'/dict/css.dict',
            \ }

I want 'js.dict' and 'css.dict' both loaded in filetype 'javascript', is it supported?

**Comment by Shougo** [comment]
```vim
let g:neocomplete#sources#dictionary#dictionaries = {
\ 'default' : '',
\ 'javascript' : $VIM.'/dict/js.dict,' .  $VIM.'/dict/css.dict',
\ }
```
