### ISSUE TITLE
Enabling AutoComplPop like behavior

### ISSUE THREAD

**Issue by horak** [Shougo/neocomplete.vim#578]
# Problems summary
What must I do to enable the AutoComplPop like behavior? I'm coming from the default config as detailed in the readme. 

## `.vimrc`
I have enabled this:
```
" AutoComplPop like behavior.
let g:neocomplete#enable_auto_select = 1
```

and commented out this:
```
" Disable AutoComplPop.
"let g:neocomplete#enable_auto_select = 0
```

## Environment Information
 * OS: OSX 10.12.1
 * Vim version: 8.0

is anything else necessary?

**Comment by Shougo** [comment]
> What must I do to enable the AutoComplPop like behavior? I'm coming from the default config as detailed in the readme.

I don't understand.
What is your desired auto completion behavior?
You don't have to enable the AutoComplPop behavior.

**Comment by horak** [comment]
Ah, I see the point of confusion; sorry about my phrasing. I wanted autocomplete to popup automatically, but I was merely missing lua. All set. Thanks for hard work!
