### ISSUE TITLE
vim get segmentation fault in OS X when neocomplete enabled

### ISSUE THREAD

**Issue by mingsu** [Shougo/neocomplete.vim#580]
# Problems summary
VIM get segmentation fault when neocomplete enable

## Environment Information
 * OS: macOS Sierra Version 10.12.4
 * Vim version: 8.0

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 25 2017 18:09:47)
Included patches: 1-586
Compiled by ming@mac.lan
Huge version with X11-Athena GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      +xfontset
-dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "\~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/usr/local/share//vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/X11/include   
Linking: gcc  -L/usr/X11/lib   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim -lXaw -lXmu -lXext -lXpm -lXt -lX11 -lSM -lICE -lm -lncurses  -liconv  -L/usr/local/lib -lluajit-5.1  -L/usr/lib/python2.7/config -lpython2.7 -framework CoreFoundation -u _PyMac_Error /System/Library/Frameworks/Python.framework/Versions/2.7/Python   -lruby.2.4.1 -lobjc    

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/neocomplete.nvim/
let g:neocomplete#enable_at_startup = 1
```

## The reproduce ways from Vim starting (Required!)

 1. once neocomplete enabled

**Comment by Shougo** [comment]
I have tested neocomplete in Vim 8.0.586.
But it is not crashed.

I think you can check where the code is crashed.
And you can get the core dump and the crash report(stack trace).

**Comment by Shougo** [comment]
More users test is needed.
I think Mac OS X user is huge.
But I don't get crash report from them.

**Comment by mingsu** [comment]
@Shougo 
I have used neocomplete in Vim 8.0 within debian, which works fine.
But I use the same setup for maxOS, the vim crashs once neocomplete enabled.

Could you pls tell me how to get **the core dump and the crash report (stack trace)**.

**Comment by Shougo** [comment]
http://www.todesking.com/blog/2014-06-20-debugging-segmentation-fault-with-gdb-on-osx/

**Comment by mingsu** [comment]
https://github.com/Valloric/YouCompleteMe/issues/1391
Is this issue related to mine? what do you think?

**Comment by Shougo** [comment]
> I think you can check where the code is crashed.

If your Vim is crashed after execute ruby commands, it is from Ruby.
But you have not shown the information.
I have not ESP skills.

**Comment by mingsu** [comment]
I solved my problem now.
I used to install vim from the source, and compiled by myself.
Just now, I reinstalled vim by

`brew install vim --with-lua --enable-rubyinterp --with-features=huge --with-x --enableluainterp`

The error was removed.

**Comment by Shougo** [comment]
OK.
