### ISSUE TITLE
Is there a function that can check whether any menu entry in completion menu is selected (highlighted) or not?

### ISSUE THREAD

**Issue by z0rc** [Shougo/neocomplete.vim#582]
I did check documentation, but didn't find answer on this question.

My vim configuration has `let g:neocomplete#enable_auto_select=0` and I'm looking for a way to automatically determine, if any completion menu entry is selected at current moment.

Unfortunately `neosnippet#expandable_or_jumpable()` isn't suitable here. `pumvisible()` allows to check, if completion menu is present, but I need to check, if completion menu is present and menu entry is selected.

This might be a general Vim question. Sorry for trouble, if so.

**Comment by Shougo** [comment]
This is Vim feature.
You should ask it in vim issues.
