### ISSUE TITLE
Ability to prioritize function parameters and showing them on entering (

### ISSUE THREAD

**Issue by sassanh** [Shougo/neocomplete.vim#583]
Is it possible to:
1. Have an option to prioritize function parameters.
2. Show function parameters when user enters (.
For example when entering `serializers.SerializerMethodField(` (python rest framework) would be great to show `method_field` as first completion suggestion and when entering `serializers.SerializerMethodField(me` would be great to have `method_field` as first suggestion (currently it's `map` then `max`, etc for me, `method_field'` is 6th)

**Comment by Shougo** [comment]
> Have an option to prioritize function parameters.

I don't think it is useful.  The usecase is not useful for me.

> Show function parameters when user enters `(`.

https://github.com/Shougo/echodoc.vim

**Comment by Shougo** [comment]
Hm.
Multipost: https://github.com/roxma/nvim-completion-manager/issues/75

**Comment by sassanh** [comment]
Yeah, I'm sorry, I posted this in wrong repository here.

**Comment by Shougo** [comment]
Oh...
