### ISSUE TITLE
Is there any way to set "default" filters for user-defined source?

### ISSUE THREAD

**Issue by machakann** [Shougo/neocomplete.vim#585]
# Problems summary

This is a question about the user-defined source. Currently I'm writing my neocomplete source, it returns items as already sorted order, thus I don't want them to be sorted again in default. Although I learned that there is `neocomplete#custom#source()` and I can realize it with;

```vim
call neocomplete#custom#source('mysource', 'sorters', [])
```

if I write this in my source code, then other users cannot customize it. Or I can tell users to write the line into their vimrc but it sounds like a bit tedious work. I would be happy if there is a way to just "recommend" filters without forcing. So is there any way to set default filters unique for a user-defined source? Do you have any idea about this?

## Expected

What I expect is, for example:

```vim
let s:source = {
  \ 'name': 'mysource',
  \ 'kind': 'keyword',
  \ 'default_sorters': [],
  \ 'default_matchers': ['matcher_for_mysource'],
  \ }

function! neocomplete#sources#mysource#define()
  return s:source
endfunction
```

An source author writes default filters for the source, and if user use `neobundle#custom#source()` then the default filters will be overwritten.

**Comment by Shougo** [comment]
```vim
let s:source = {
  \ 'name': 'mysource',
  \ 'kind': 'keyword',
  \ 'sorters': [],
  \ 'matchers': ['matcher_for_mysource'],
  \ }
```

**Comment by machakann** [comment]
Thank you!
