### ISSUE TITLE
Please, some guidance about how to configure completion keywords

### ISSUE THREAD

**Issue by unphased** [Shougo/neocomplete.vim#592]
I really need to be able to treat hyphens as part of a keyword for javascript. This is because a lot of CSS class names end up in javascript strings. 

I'm not able to figure it out. I have edited `plugged/neocomplete/autoload/neocomplete/init.vim` and updated it this way: 

```
  262   call neocomplete#util#set_default_dictionary(
  263         \'g:neocomplete#keyword_patterns',
! 264         \'javascript,css,stylus,scss,less',
  265         \'[@#.]\?[[:alpha:]_:-][[:alnum:]_:-]*')
```

and removed the `javascript` one from above. However, it doesn't seem like it is taking effect.

**Comment by Shougo** [comment]
You should check `g:neocomplete#keyword_patterns` value.
It should work.

But you should not change the neocomplete source code directly.
You should set `g:neocomplete#keyword_patterns.javascript` manually.
