### ISSUE TITLE
Results in popup are not filter out

### ISSUE THREAD

**Issue by veraus** [Shougo/neocomplete.vim#594]
# Problems summary
When I write Data. a popup appears showing a lot of options for autocomplete.
Then I continue writing Data.Tup however the popup is still showing the previous results without filtering the item that starts with Data.Tup

## Expected
The results that appear in the popup for autocompletion should be filtered while writing text.

## Environment Information
 * OS: Mac OS
 * Vim version: 8.0.648

## Provide a minimal .vimrc with less than 50 lines (Required!)
Plugin 'eagletmt/ghcmod-vim'
Plugin 'bitc/vim-hdevtools'
Plugin 'eagletmt/neco-ghc'
Plugin 'Shougo/neocomplete'

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/neocomplete.nvim/
let g:neocomplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
This is the minimal vimrc.
I cannot reproduce your problem.

```vim
set rtp+=~/.cache/dein/repos/github.com/eagletmt/neco-ghc/
set rtp+=~/.cache/dein/repos/github.com/Shougo/neocomplete.vim/

let g:neocomplete#enable_at_startup = 1

filetype plugin indent on
```

**Comment by veraus** [comment]
Thanks for the answer. With the minimal vimrc works. I found another plugin (I think it was vim dispatch) it started to work. The item can be closed.

**Comment by Shougo** [comment]
OK.
