### ISSUE TITLE
Third party libraries;

### ISSUE THREAD

**Issue by BlasphemyAngels** [Shougo/neocomplete.vim#596]
# Problems summary
Hi Shougo, how can teh neocomplete support the third party libraries? When I write python script, I installed some lib use 'pip'. But it didn't work.

## Environment Information
 * Vim version: 8.0

**Comment by Shougo** [comment]
I cannot understand your issue.
We have not ESP skills.

**Comment by BlasphemyAngels** [comment]
```py
import numpy
numpy.
```
For example, I use a lib named 'numpy', I installed it by the pip order. But when I write script by vim, It didn't complete when write the numpy. When I had wrote the dot, I press the <Tab> key, it didn't show anything.

**Comment by Shougo** [comment]
You must install jedi-vim plugin.
https://github.com/davidhalter/jedi-vim
