### ISSUE TITLE
neocomplete.vim with problem of 100% cpu usage

### ISSUE THREAD

**Issue by rainmoring** [Shougo/neocomplete.vim#599]
# Problems summary
I work in a strict computer env, and I'm not a Admin. I use spf-13 as vim env . I built vim by myself with lua and python support. Also lua is build by myself in my home.  My project which is based on openwrt, and when I use  neocomplete ,once I type -> ,or c^x c^o ,the compute do not response to me until I type c^c. I use 'top' to see the cpu usage ,I found it meet nearly one handred percent usage. 
![image 1](https://user-images.githubusercontent.com/13134522/30164188-3fb50908-940e-11e7-894f-a0b7eb843866.png)

And when I comment the neocomplete, it didn't happen any more 
And when I change my project to another little project ,it didn't happen any more

## Expected
a normal cpu usage and response

## Environment Information
 * OS: Ubuntu 14.04.5 LTS
 * Vim version: vim 8.0
Lua 5.3.4
readline 7.0

## Provide a minimal .vimrc with less than 50 lines (Required!)
 759          let g:acp_enableAtStartup = 0                                                                                                                                               
 760           let g:neocomplete#enable_at_startup = 1
 761             let g:neocomplete#enable_smart_case = 1
 762             let g:neocomplete#enable_auto_delimiter = 1
 763             let g:neocomplete#max_list = 15
 764            "let g:neocomplete#force_overwrite_completefunc = 1
 765             let g:neocomplete#sources#syntax#min_keyword_length = 3
 766 
 767             " Define dictionary.
 768             let g:neocomplete#sources#dictionary#dictionaries = {
 769                         \ 'default' : '',
 770                         \ 'vimshell' : $HOME.'/.vimshell_hist',
 771                         \ 'scheme' : $HOME.'/.gosh_completions'
 772                         \ }
 773 
 774             " Define keyword.
 775             if !exists('g:neocomplete#keyword_patterns')
 776                 let g:neocomplete#keyword_patterns = {}
 777             endif
 778             let g:neocomplete#keyword_patterns['default'] = '\h\w*'

## The reproduce ways from Vim starting (Required!)
Project based on openwrt, and when I use  neocomplete ,once I type -> ,or c^x c^o ,the compute do not response

**Comment by Shougo** [comment]
`C^xC^o` is omnifunc.
It is not neocomplete related problem.

You should check omnifunc by `:verbose setlocal omnifunc?`.

**Comment by rainmoring** [comment]
Now I know the reason.It beacause the tag is too big, and vim spend such a long time on search tag file. After many pratice ,evtually I found that about 5 miniters  later ,it responsed. And I think that's the answer.

Thanks for your replay.
