### ISSUE TITLE
"vim" is not found

### ISSUE THREAD

**Issue by wothard** [Shougo/neocomplete.vim#602]
# Problems summary
I use "space vim" and it include plugin neocomplete.vim, and then I open vim type some python code,
when I type code like "def" it show some selection let me choice. But the status show : 
[neocomplete] Vim path : "vim" is not found.You must add "vim" installed path in $PATH.

## Environment Information
 * OS: linux
 * Vim version:8.0.1366

## Provide a minimal .vimrc with less than 50 lines (Required!)

I use space vim and I can`t found $HOME/.vimrc

## Screen shot (if possible)
![screenshot_2017-12-05_09-34-07](https://user-images.githubusercontent.com/15395394/33585691-19bfd6da-d92b-11e7-9dca-151e02719fb4.png)

**Comment by Shougo** [comment]
"vim" command is needed in your `$PATH`.
But I recommend for you to use deoplete.nvim instead.

Note: Active development on neocomplete.vim has stopped. The only future changes will be bug fixes.

Please see Deoplete.nvim.
https://github.com/Shougo/deoplete.nvim
