### ISSUE TITLE
Onmi Window Doesn't Appear for PHP While Typing

### ISSUE THREAD

**Issue by phatsk** [Shougo/neocomplete.vim#606]
# Problems summary
When typing in a PHP file, I can start omni completion using `<C-x><C-o>` to get the popup menu with phpcomplete-extneded working with Neocomplete, but if I type my input pattern then nothing happens.

## Expected
Given this:
```php
$dt = new DateTime;
$dt->
```
The omni window should appear with the properties and methods of `DateTime`

## Environment Information
 * OS: MacOS
 * Vim version: NVIM v0.3.1-135-gbd51a0cd0

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
let g:neocomplete#sources#omni#input_patterns['php'] = '[^. \t]->\|\h\w*::'
let g:neocomplete#sources#syntax#min_keyword_length = 0
```

For phpcomplete-extended:
```vim
autocmd  FileType  php setlocal omnifunc=phpcomplete_extended#CompletePHP
```

## The reproduce ways from Vim starting (Required!)

 1. Start vim
 2. Edit a php file
 3. Add the following:
```php
$dt = new DateTime;
$dt->
```

**Comment by Shougo** [comment]
I have tested, but phpcomplete-extended does not work.
It is phpcomplete-extended problem.

But it seems not supported.

https://github.com/m2mdas/phpcomplete-extended/issues/69

I think you should use phpcd.vim instead.

**Comment by Shougo** [comment]
```vim
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
let g:neocomplete#sources#omni#input_patterns['php'] = '[^. \t]->\|\h\w*::'
```

It is not needed.  Because phpcomplete-extended has neocomplete source.
