### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by j5shi** [Shougo/neocomplete.vim#610]
# Problems summary
OK, this is not an real problem but a feature request. Neocomplete provided a way to complete the words found in context, for example, if there's a word "Neocomplete" somewhere is the current file, then it can help you to complete while you start to type "Neo..." or "neo..." or even "neO..." with an omnibox with the word "Neocomplete", **but I also wish to have the word "neocomplete", i.e. with all the letters lower-cased.**

**Comment by Shougo** [comment]
Sorry.  neocomplete development is already done.
I don't want to add more features in neocomplete.
