### ISSUE TITLE
"Extract the files and put them in your Vim directory" which files?

### ISSUE THREAD

**Issue by evandrocoan** [Shougo/neocomplete.vim#614]
![image](https://user-images.githubusercontent.com/5332158/66667858-5e83fa80-ec2a-11e9-9c7a-e4f5f8ed352d.png)

Related:
1. https://github.com/Shougo/deoplete.nvim/issues/1027 How to install this?

**Comment by Shougo** [comment]
It means all files in the repository.

But it is manual installation.  I don't recommend for you to use it.
You should use plugin manager instead.
