### ISSUE TITLE
E: Package 'vim-gnome' has no installation candidate

### ISSUE THREAD

**Issue by hacky1997** [Shougo/neocomplete.vim#615]
# Problems summary
Whenever try to install vim-gnome it throws E: Package 'vim-gnome' has no installation candidate error

## Environment Information
 * OS: Kali
 * Vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 09 2019 12:59:40)

**Comment by Shougo** [comment]
Thanks.  I have fixed the documentation.
