### ISSUE TITLE
lua array index in vim now starts with 1 starting with patch-8.2.1066

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/neocomplete.vim#616]
Refer to the following for discussions related to this on why it was important to have this breaking change.

* https://github.com/vim/vim/commit/bd84617d1a6766efd59c94aabebb044bef805b99 
* https://github.com/vim/vim/issues/6342
* https://github.com/vim/vim/pull/6347
* https://github.com/neovim/neovim/issues/12537

Related vim-lsp PR can be found at https://github.com/prabirshrestha/vim-lsp/pull/851which shows an example on how to fix it.

**Comment by Shougo** [comment]
Yes.  I have removed Vim 8.2.1066 support.
neocomplete is old plugin and deoplete is recommended instead.
