### ISSUE TITLE
Asking for username and password

### ISSUE THREAD

**Issue by Jeklah** [Shougo/neocomplete.vim#617]
# Problems summary
When running the install script I always run into it freezing on the plugin amirh/HTML-AutoCloseTag when it asks for username and pass.

## Expected
Plugin to be installed without credentials like the other plugins.

## Environment Information
 * OS: Ubuntu, Kali
 * Vim version: 3

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/neocomplete.nvim/
let g:neocomplete#enable_at_startup = 1
```

## The reproduce ways from Vim starting (Required!)

1. run the install script

**Comment by Shougo** [comment]
It is not neocomplete error.

**Comment by Jeklah** [comment]
I found this is due to the repo not being continued anymore. I changed the repo to one that it and I did not get this issue anymore.

**Comment by Shougo** [comment]
Yes.
