### ISSUE TITLE
Error with gVim version 7.4.51 on Windows 7

### ISSUE THREAD

**Issue by pmugit** [Shougo/neocomplete.vim#94]
Hi,

I am using tux gvim version 7.4.51 as shown in the documentation, but I get the following error:
neocomplete does not work this version of Vim.

It requires Vim 7.3.885 or above and "if_lua" enabled Vim.

The output of --version shows +lua/dyn, which I think means that its compiled with if_lua. 

Kindly let me know.

**Comment by wewea** [comment]
Hi Shougo, the solution is work,  I copy the lua51.dll and luajit to vim74. thank you. 
I think it's better to paste the link of kaoriya-vim in README

**Comment by CreativeKoen** [comment]
in which folder do you need to put the .dll and .exe files?
